### ISSUE TITLE
I have Created new Project using angular/cli command not create the project throw error Cannot find module 'ini'

### ISSUE THREAD

**Issue by sachinhd517** [HabitRPG/habitica#10094]
PS D:\Angular CRUD> ng new AngularCrud --skip-tests true
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
module.js:559
    throw err;
    ^

Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Sachinhd517\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:4:11)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

Package install failed, see above.
Package install failed, see above.

**Comment by paglias** [comment]
Hi @sachinhd517,

I'm sorry but I don't think this issue belongs to this repo, we don't use angular
