### ISSUE TITLE
Toolset error during npm install

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#10229]
Hi, i have followed your docs at http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally, everything works quite well, when i get to the point where i need to do npm install, it returns me error
```
`C:\Users\ADMIN\habitica\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\ADMIN\habitica\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\librdkafka.dll
C:\Users\ADMIN\habitica\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\zlib.dll
C:\Users\ADMIN\habitica\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\librdkafkacpp.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [C:\Users\ADMIN\habitica\node_modules\node-rdkafka\deps\librdk
afka.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ADMIN\habitica\node_modules\node-rdkafka
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> stackimpact@1.2.1 install C:\Users\ADMIN\habitica\node_modules\stackimpact
> node node-gyp-fallback.js

Pre-built version of StackImpact addon not found, trying to build.
node-gyp not found.
npm WARN @vue/test-utils@1.0.0-beta.12 requires a peer of vue-server-renderer@2.x but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-sinon-chai@1.3.3 requires a peer of sinon-chai@^2.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-rdkafka@2.3.1 (node_modules\node-rdkafka):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-rdkafka@2.3.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stackimpact@1.2.1 install: `node node-gyp-fallback.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stackimpact@1.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2018-04-06T16_16_08_926Z-debug.log

C:\Users\ADMIN\habitica>`
```
what to do?

**Comment by Mahendran-Nadesan** [comment]
Having an issue with the toolset as well. I've gotten past the initial error of it not even trying to install the dependencies; I didn't have nuget.exe on my PATH. Currently, can't install because 

`` fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory``

In your particular case, I'd guess you have to manually install the peers of vue-server-renderer@2.x, ajv@^6.0.0 and sinon-chai@^2.9.0 and see what happens?

**Comment by Alys** [comment]
The http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally instructions have been rewritten for Windows, Linux, and MacOS (Vagrant and Docker will be done too), so you might find that following them from the start gives you a better result now. Can you please try that and then comment here if it was successful or if you still have trouble?

**Comment by paglias** [comment]
We've removed stackimpact so I'm going to close this, feel free to comment if you still have problems
