### ISSUE TITLE
Progress graph icon above Todos does nothing

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1022]
Clicking the progress graph icon next to the iCal icon over Todos has no effect, for me (Firefox/Chrome). If this isn't implemented yet, should probably gray that out or hide it.

**Comment by handlinger** [comment]
It never works for me, either (same browsers). It did, however, work at one time.

**Comment by kalmduck** [comment]
This is the case for me, too.  Checking the console, I get the following error/stack trace:

Error in event handler for 'undefined': IndexSizeError: DOM Exception 1 Error: Index or size was negative, or greater than the allowed value.
    at P (chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:16:142)
    at null.<anonymous> (chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:18:417)
    at chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:1:182
    at miscellaneous_bindings:287:9
    at Event.dispatchToListener (event_bindings:356:21)
    at Event.dispatch_ (event_bindings:342:27)
    at Event.dispatch (event_bindings:362:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:346
Event.dispatch_

**Comment by kalmduck** [comment]
Following up, this problem seems to be gone for me.

**Comment by StanLindsey** [comment]
@handlinger & @SabreCat - can you confirm that this is fixed?

**Comment by SabreCat** [comment]
Now seeing the nifty graph! Closing.
