### ISSUE TITLE
TypeError in login-incentives: Cannot read property 'nextRewardAt' of undefined

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#10308]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: f9c89bba-abf8-4f20-a974-cf1550ff603f
  * Browser: Chrome Version 66.0.3359.117 (Official Build) (64-bit)
  * OS: redacted

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Loaded the site, Bailey modal popped up, noticed buttons did not contain any text.

![image](https://user-images.githubusercontent.com/5641207/39455453-3fc47a7e-4c95-11e8-8c1b-065f86bcc447.png)

After guessing and clicking one of the empty buttons, it looks like a bunch of other text also failed to load.

![image](https://user-images.githubusercontent.com/5641207/39455523-b9f2be6e-4c95-11e8-97ba-501e9e2db09f.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Failed to load resource: the server responded with a status of 502 (Bad Gateway)
moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.b91cfcde844f24cdc5d8.js:1:12941)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:243271)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:18284)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:348871)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:584639)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:342511)
x @ moment.js:293
vue.runtime.esm.js:1737 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (login-incentives.vue?fca4:74)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.evaluate (vue.runtime.esm.js:3245)
    at a.nextReward (vue.runtime.esm.js:3503)
    at a.s (login-incentives.vue?e357:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at Ti.get (vue.runtime.esm.js:3138)
    at new Ti (vue.runtime.esm.js:3127)
    at $t (vue.runtime.esm.js:2791)
ot @ vue.runtime.esm.js:1737
/#/tasks:1 Mixed Content: The page at 'https://habitica.com/#/tasks' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/Qc7Qe11.gif'. This content should also be served over HTTPS.

![image](https://user-images.githubusercontent.com/5641207/39455559-fcc8398a-4c95-11e8-8bbb-3ebb49c1de4f.png)

**Comment by khipkin** [comment]
The little pop-up notifications on the top right of the screen also contain no text.

![image](https://user-images.githubusercontent.com/5641207/39455620-58d70bc0-4c96-11e8-97fd-fa5e624d6e95.png)

No new errors in the console after that.

**Comment by khipkin** [comment]
This happened again when I was viewing my party page, although all text rendered this time (as far as I can tell). I got one of those "out of sync" error popups though.

moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.b91cfcde844f24cdc5d8.js:1:12941)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:243271)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:18284)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:348871)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:584639)
    at n (https://habitica.com/static/js/manifest.6efba0f57111f78a12fc.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.556d286a21777a872250.js:1:342511)
x @ moment.js:293
vue.runtime.esm.js:1737 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (login-incentives.vue?fca4:74)
    at Ti.get (vue.runtime.esm.js:3138)
    at Ti.evaluate (vue.runtime.esm.js:3245)
    at a.nextReward (vue.runtime.esm.js:3503)
    at a.s (login-incentives.vue?e357:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at Ti.get (vue.runtime.esm.js:3138)
    at new Ti (vue.runtime.esm.js:3127)
    at $t (vue.runtime.esm.js:2791)
ot @ vue.runtime.esm.js:1737
#/tasks:1 Mixed Content: The page at 'https://habitica.com/#/tasks' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/Qc7Qe11.gif'. This content should also be served over HTTPS.
fox_face.png:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
api/v3/groups/ca4cc164-0a61-4eb6-afd8-5301e3dfae8b/chat/seen:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 502
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.h.(anonymous function) (https://habitica.com/static/js/vendor.b91cfcde844f24cdc5d8.js:6:127456)

![image](https://user-images.githubusercontent.com/5641207/39457926-f5344e10-4ca5-11e8-97ef-8261961d6091.png)

Clicking on the URL *after* "(anonymous function)" brought me to this:

![image](https://user-images.githubusercontent.com/5641207/39457972-3aabc806-4ca6-11e8-9efe-c6823f4c2c98.png)

**Comment by khipkin** [comment]
I've been getting the error popups A LOT recently, but didn't look at the console before. It seems like it might be because I've checked in more than 500 (?) times and have no more rewards to unlock?

**Comment by khipkin** [comment]
https://github.com/HabitRPG/habitica/issues/10178#issuecomment-380428262 looks like the same error?

**Comment by TheHollidayInn** [comment]
Can you post your UserID?

**Comment by khipkin** [comment]
f9c89bba-abf8-4f20-a974-cf1550ff603f

**Comment by TheHollidayInn** [comment]
Do you have this gif used somewhere: http://i.imgur.com/Qc7Qe11.gif ?

**Comment by TheHollidayInn** [comment]
If so, can you change that to `https` to see if that helps.

**Comment by khipkin** [comment]
Umm sure, but I really really don't think that's the problem. That's just a warning, not an error.

**Comment by TheHollidayInn** [comment]
You have multiple issues above. I believe your 502s are an issue with breaking https (just a guess). That's the most important issue above.

**Comment by paglias** [comment]
I don't think HTTPS is related, some browsers are starting to enforce mixed content warning but that just means they won't load the image, it shouldn't break anything

**Comment by TheHollidayInn** [comment]
Just doing some basic debugging here to rule stuff out. The issue is here:

```
api/v3/groups/ca4cc164-0a61-4eb6-afd8-5301e3dfae8b/chat/seen:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 502
at t.exports (createError.js:16)
at t.exports (settle.js:18)
at XMLHttpRequest.h.(anonymous function) (https://habitica.com/static/js/vendor.b91cfcde844f24cdc5d8.js:6:127456)
```

Login incentives is like that for everyone based the mark. I'm just trying to see what would cause the 502s.

**Comment by khipkin** [comment]
Just had this recur. Got another big error popup on the upper right.

I don't know when I last reloaded the page, but there are tons of messages in the console.

Console:

vendor.d74eb5c80000a7c3241e.js:1 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.d74eb5c80000a7c3241e.js:1:12941)
    at Object.<anonymous> (https://habitica.com/static/js/app.4511849745acac465a43.js:1:244531)
    at n (https://habitica.com/static/js/manifest.1955d8479fd3e448b3b6.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.4511849745acac465a43.js:1:18284)
    at n (https://habitica.com/static/js/manifest.1955d8479fd3e448b3b6.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.4511849745acac465a43.js:1:349519)
    at n (https://habitica.com/static/js/manifest.1955d8479fd3e448b3b6.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.4511849745acac465a43.js:1:586425)
    at n (https://habitica.com/static/js/manifest.1955d8479fd3e448b3b6.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.4511849745acac465a43.js:1:343159)
x @ vendor.d74eb5c80000a7c3241e.js:1
6Slow network is detected. See <URL> for more details. Fallback font will be used while loading: <URL>
vendor.d74eb5c80000a7c3241e.js:1 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (app.4511849745acac465a43.js:1)
    at Ti.get (vendor.d74eb5c80000a7c3241e.js:6)
    at Ti.evaluate (vendor.d74eb5c80000a7c3241e.js:6)
    at a.nextReward (vendor.d74eb5c80000a7c3241e.js:1)
    at a.s (app.4511849745acac465a43.js:1)
    at a.t._render (vendor.d74eb5c80000a7c3241e.js:6)
    at a.r (vendor.d74eb5c80000a7c3241e.js:1)
    at Ti.get (vendor.d74eb5c80000a7c3241e.js:6)
    at new Ti (vendor.d74eb5c80000a7c3241e.js:6)
    at $t (vendor.d74eb5c80000a7c3241e.js:1)
ot @ vendor.d74eb5c80000a7c3241e.js:1
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=684700530.1471973948&jid=1816895253&_v=j67&z=237528259 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/party:1 The SSL certificate used to load resources from https://images-na.ssl-images-amazon.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
fox_face.png Failed to load resource: the server responded with a status of 403 (Forbidden)
/api/v3/notifications/see Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.d74eb5c80000a7c3241e.js:6 Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (vendor.d74eb5c80000a7c3241e.js:6)
    at t.exports (vendor.d74eb5c80000a7c3241e.js:12)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.d74eb5c80000a7c3241e.js:6:127491)
/api/v3/user/class/cast/valorousPresence Failed to load resource: the server responded with a status of 401 (Unauthorized)
vendor.d74eb5c80000a7c3241e.js:6 Uncaught (in promise) Error: Request failed with status code 401
    at t.exports (vendor.d74eb5c80000a7c3241e.js:6)
    at t.exports (vendor.d74eb5c80000a7c3241e.js:12)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.d74eb5c80000a7c3241e.js:6:127491)
11vendor.d74eb5c80000a7c3241e.js:1 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (app.4511849745acac465a43.js:1)
    at Ti.get (vendor.d74eb5c80000a7c3241e.js:6)
    at Ti.evaluate (vendor.d74eb5c80000a7c3241e.js:6)
    at a.nextReward (vendor.d74eb5c80000a7c3241e.js:1)
    at a.s (app.4511849745acac465a43.js:1)
    at a.t._render (vendor.d74eb5c80000a7c3241e.js:6)
    at a.r (vendor.d74eb5c80000a7c3241e.js:1)
    at Ti.get (vendor.d74eb5c80000a7c3241e.js:6)
    at Ti.run (vendor.d74eb5c80000a7c3241e.js:6)
    at Rt (vendor.d74eb5c80000a7c3241e.js:1)
ot @ vendor.d74eb5c80000a7c3241e.js:1
/api/v3/tasks/721f8306-74af-4875-8951-86dca7932d32/score/up Failed to load resource: the server responded with a status of 502 (Bad Gateway)
vendor.d74eb5c80000a7c3241e.js:6 Uncaught (in promise) Error: Request failed with status code 502
    at t.exports (vendor.d74eb5c80000a7c3241e.js:6)
    at t.exports (vendor.d74eb5c80000a7c3241e.js:12)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.d74eb5c80000a7c3241e.js:6:127491)
DevTools failed to parse SourceMap: https://habitica.com/static/js/app.4511849745acac465a43.js.map
DevTools failed to parse SourceMap: https://habitica.com/static/js/manifest.1955d8479fd3e448b3b6.js.map
DevTools failed to parse SourceMap: https://habitica.com/static/js/8.d8c82d2b3faec5773de8.js.map

![image](https://user-images.githubusercontent.com/5641207/39665499-3ec1b5f2-504a-11e8-9d50-7c1268b2ac42.png)
![image](https://user-images.githubusercontent.com/5641207/39665506-608b0936-504a-11e8-943c-7ba2e24cb8fe.png)

**Comment by khipkin** [comment]
Happened again. Had just cronned and was using skills and checking off dailies.

vendor.69b17596f5c5cefe04a5.js:1 TypeError: Cannot read property 'nextRewardAt' of undefined
    at a.nextReward (app.85ce03683b5003540623.js:1)
    at Ti.get (vendor.69b17596f5c5cefe04a5.js:6)
    at Ti.evaluate (vendor.69b17596f5c5cefe04a5.js:6)
    at a.nextReward (vendor.69b17596f5c5cefe04a5.js:1)
    at a.s (app.85ce03683b5003540623.js:1)
    at a.t._render (vendor.69b17596f5c5cefe04a5.js:6)
    at a.r (vendor.69b17596f5c5cefe04a5.js:1)
    at Ti.get (vendor.69b17596f5c5cefe04a5.js:6)
    at new Ti (vendor.69b17596f5c5cefe04a5.js:6)
    at $t (vendor.69b17596f5c5cefe04a5.js:1)
ot @ vendor.69b17596f5c5cefe04a5.js:1
habitica.com/:1 The SSL certificate used to load resources from https://images-na.ssl-images-amazon.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
/api/v3/user/class/cast/intimidate:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
vendor.69b17596f5c5cefe04a5.js:6 Uncaught (in promise) Error: Request failed with status code 401
    at t.exports (vendor.69b17596f5c5cefe04a5.js:6)
    at t.exports (vendor.69b17596f5c5cefe04a5.js:12)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.69b17596f5c5cefe04a5.js:6:127654)
/api/v3/tasks/dc30ba50-1fa4-4041-9969-6715749d7f74/score/up:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
vendor.69b17596f5c5cefe04a5.js:6 Uncaught (in promise) Error: Request failed with status code 502
    at t.exports (vendor.69b17596f5c5cefe04a5.js:6)
    at t.exports (vendor.69b17596f5c5cefe04a5.js:12)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.69b17596f5c5cefe04a5.js:6:127654)

![image](https://user-images.githubusercontent.com/5641207/40498905-2f0dbce2-5f35-11e8-88c9-3f54a4ae300e.png)

**Comment by zmbc** [comment]
I don't have any 502s, but I see the error "Cannot read property 'nextRewardAt' of undefined" nearly every time I re-order the todo list. The re-ordering operation also acts strangely when the error occurs; the todo I was dragging seems to be randomly offset from where I actually dragged it (anywhere from a few todos above to a few todos below).

Edit: Seems I'm experiencing #7645. However, it's still odd that the two are correlated for me (the reordering issue always coincides with this console error). Perhaps #7645 is causing this one?
