### ISSUE TITLE
Unclear that "Use my selected payment method for future purchases" for Amazon is mandatory

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10511]
As reported by Sitaara (ecf22ed4-3489-423c-a74f-a9fb05ab1fbf):

_"i'm trying to make a group but always apear "an unexpected error occured" or "the payment was not successful". I already tried other cards but happened the same thing."_

From Loggly, they were trying to use Amazon and error messages similar to below were shown there.

The same occurred when I tried to use Amazon to create a Group Plan and my error is below.

Using Stripe works.

```
{"method":"POST","originalUrl":"/api/v4/groups/create-plan",

"headers":{"connection":"Keep-Alive","content-type":"application/json;charset=utf-8","accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","host":"habitica.com","max-forwards":"10","referer":"https://habitica.com/group-plans",
"x-client":"habitica-web",
"x-api-user":"d904bd62-da08-416b-a816-ba797c9ee265","x-user-timezoneoffset":"-600",
"x-forwarded-proto":"https","x-forwarded-port":"443","x-original-host":"habitica.com","sec-websocket-extensions":"",
"x-original-url":"/api/v4/groups/create-plan","x-arr-ssl":"2048|256|C=GB, S=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO RSA Domain Validation Secure Server CA|OU=Domain Control Validated, OU=EssentialSSL Wildcard, CN=*.habitica.com","x-arr-log-id":"8df90e80-7f8c-4a8b-87b3-224794f75e6a","content-length":"234"},

"body":{"billingAgreementId":"B01-7977882-6130072","subscription":"group_monthly","coupon":null,"groupToCreate":{"type":"guild","privacy":"private","name":"test","leaderOnly":{"challenges":false},"description":"test"},"paymentType":"Amazon"},

"httpCode":500,"isHandledError":false,

"fullError":{"type":"BillingAgreementConstraintsExist","name":"BillingAgreementConstraintsExist","body":{"ErrorResponse":{"$":{"xmlns":"http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01"},"Error":{"Type":"Sender","Code":"BillingAgreementConstraintsExist","Message":"The BillingAgreementId B01-7977882-6130072 has constraints BuyerConsentNotSet and cannot be confirmed."},"RequestId":"9788ef15-8df2-4ade-bbad-bdaf0e5439df"}}},

"timestamp":"2018-07-08T22:31:39.830Z","level":"error",

"message":"BillingAgreementConstraintsExist: The BillingAgreementId B01-7977882-6130072 has constraints BuyerConsentNotSet and cannot be confirmed.\n at new <anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/lib/error.js:22:15)\n at Object.apiError (/usr/src/habitrpg/node_modules/amazon-payments/lib/error.js:31:10)\n at /usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:210:31\n at Parser.<anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:384:20)\n at emitOne (events.js:116:13)\n at Parser.emit (events.js:211:7)\n at SAXParser.onclosetag (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:348:26)\n at emit (/usr/src/habitrpg/node_modules/sax/lib/sax.js:615:33)\n at emitNode (/usr/src/habitrpg/node_modules/sax/lib/sax.js:620:3)\n at closeTag (/usr/src/habitrpg/node_modules/sax/lib/sax.js:861:5)\n at SAXParser.write (/usr/src/habitrpg/node_modules/sax/lib/sax.js:1294:29)\n at Parser.exports.Parser.Parser.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:403:31)\n at Parser.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:6:61)\n at Object.exports.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:433:19)\n at parseMwsResponse (/usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:195:12)\n at Request._callback (/usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:101:5)\n at Request.self.callback (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/request/request.js:185:22)\n at emitTwo (events.js:126:13)\n at Request.emit (events.js:214:7)\n at Request.<anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/request/request.js:1157:10)\n at emitOne (events.js:116:13)\n at Request.emit (events.js:211:7)"}
```

**Comment by Alys** [comment]
Labelled as needs investigation for staff to examine.

**Comment by SabreCat** [comment]
Also seeing `BadRequest: The payment was not successful` and `BillingAgreementNotModifiable: BillingAgreement B01-7138264-6306715 is not in draft state and cannot be modified with the request submitted by you.`

**Comment by SabreCat** [comment]
Relevant: https://pay.amazon.com/us/developer/documentation/apireference/201752850

Apparently we need to "Show the Amazon **Consent** widget to the buyer to obtain their consent"...

**Comment by paglias** [comment]
We do show the consent (or at least it used to work) because it's required for subscriptions as well

**Comment by SabreCat** [comment]
Based on our investigations, it seems that these errors occur when the user does not check the box shown at the bottom of this screenshot:

![image](https://user-images.githubusercontent.com/4501321/42598162-fdecc7d6-8520-11e8-82c6-b6b94ca5ae5d.png)

I'd say two things need to be done here:

* Clearly indicate to the user that their subscription will not work unless they check the box.
* Handle the error gracefully when the user fails to do so.
