### ISSUE TITLE
pinned items sorting can fail: VersionError

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10850]
@ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) reported in the Report a Bug guild about 18 hours before this issue was logged:

_"I bought the previous in the sequence, and the Astrologer Hat appeared in my pinned items, now every time I try to move it to the position I want (I was trying to have the pinned items in order of price there) I get this error:"_

![image](https://user-images.githubusercontent.com/1495809/48669112-f5465500-eb48-11e8-939e-dbd4b5303e14.png)

_"UPDATE : I pinned an other thing and now trying to move the Astrologer Hat I don't get the error"_

Then 3 hours after that:

_"Now I definitely have some kind of sorting bug on my pinned items, I move one, I wait for the sync to happen, and I see that a few items have scrambled around"_

I believe there's two problems here: VersionErrors and the path not valid message. The latter is produced with the `wrongItemPath` locales string and is probably the same issue recorded at https://github.com/HabitRPG/habitica/issues/10406 so I've added a note to that issue.

For the VersionErrors, Loggly has several errors like this one:

```
{"method":"POST",
"originalUrl":"/api/v4/user/move-pinned-item/gear.flat.shield_special_1/move/to/20",
"headers":{"connection":"Keep-Alive","accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate, br","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7","host":"habitica.com","max-forwards":"10","referer":"https://habitica.com/",
"user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
"origin":"https://habitica.com","x-user-timezoneoffset":"-60",
"x-api-user":"c073342f-4a65-4a13-9ffd-9e7fa5410d6b",
"x-client":"habitica-web",
"dnt":"1","x-forwarded-proto":"https","x-forwarded-port":"443","x-original-host":"habitica.com",
"x-original-url":"/api/v4/user/move-pinned-item/gear.flat.shield_special_1/move/to/20",
"x-forwarded-for":"...","x-arr-ssl":"...","x-arr-log-id":"f0f86a29-13f4-44b7-82dc-c60511bb93ba","content-length":"0"},
"body":{},
"httpCode":500,
"isHandledError":false,
"fullError":{"message":"No matching document found for id \"c073342f-4a65-4a13-9ffd-9e7fa5410d6b\" version 7993 modifiedPaths \"pinnedItemsOrder\"","name":"VersionError","version":7993,"modifiedPaths":["pinnedItemsOrder"]},
"timestamp":"2018-11-17T11:23:33.044Z",
"level":"error",
"message":"VersionError: No matching document found for id \"c073342f-4a65-4a13-9ffd-9e7fa5410d6b\" version 7993 modifiedPaths \"pinnedItemsOrder\"\n    at VersionError.MongooseError [as constructor] (/usr/src/habitrpg/node_modules/mongoose/lib/error/mongooseError.js:13:11)\n    at new VersionError (/usr/src/habitrpg/node_modules/mongoose/lib/error/version.js:18:17)\n    at generateVersionError (/usr/src/habitrpg/node_modules/mongoose/lib/model.js:347:10)\n    at model.Model.save (/usr/src/habitrpg/node_modules/mongoose/lib/model.js:407:27)\n    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/user.js:1700:16)\n    at args (/usr/src/habitrpg/website/transpiled-babel/libs/routes.js:17:39)\n    at Layer.handle [as handle_request] (/usr/src/habitrpg/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/habitrpg/node_modules/express/lib/router/route.js:137:13)\n    at _user.model.findOne.lean.exec.then.user (/usr/src/habitrpg/website/transpiled-babel/middlewares/language.js:100:14)\n    at <anonymous>"}
```

So it's possibly from the session being outdated but it's not reporting that on the client.

I've asked her to reload the next time she notices this and tell us if that doesn't seem to help. If it does help, this looks like the kind of thing that would benefit from a "reload or sync" message being shown to the player.

**Comment by majestic-owl448** [comment]
It is happening again when I try to move the Jeweled staff, which appeared in my pinned items a few hours ago after buying the previous in the sequence. other than the snack red message I have the code below in the console (I have cleaned it before that - but if you want I can give also the full content of when I just open the task page). For other sorting issues, sometimes there is a "an expected error occurred" but most times there is nothing that show that something is wrong other than the scrambling of the items, reloading fix it, but the items are far more scrambled than before.
```
xhr.js:178 POST https://habitica.com/api/v4/user/move-pinned-item/gear.flat.weapon_wizard_2/move/to/2 400 (Bad Request)
(anonymous) @ xhr.js:178
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:57
Promise.then (async)
r.request @ Axios.js:51
r.(anonymous function) @ Axios.js:71
(anonymous) @ bind.js:9
(anonymous) @ user.js:115
r @ runtime.js:62
(anonymous) @ runtime.js:296
t.(anonymous function) @ runtime.js:114
r @ runtime.js:62
e @ runtime.js:152
(anonymous) @ runtime.js:195
r @ runtime.js:194
n @ runtime.js:217
t.(anonymous function) @ runtime.js:114
S.async @ runtime.js:241
p @ user.js:114
value @ index.js:47
(anonymous) @ column.vue?5511:515
r @ runtime.js:62
(anonymous) @ runtime.js:296
t.(anonymous function) @ runtime.js:114
r @ runtime.js:62
e @ runtime.js:152
(anonymous) @ runtime.js:195
r @ runtime.js:194
n @ runtime.js:217
t.(anonymous function) @ runtime.js:114
S.async @ runtime.js:241
rewardSorted @ column.vue?5511:462
e @ vue.runtime.esm.js:2023
t.$emit @ vue.runtime.esm.js:2534
(anonymous) @ vuedraggable.js:61
(anonymous) @ vue.runtime.esm.js:1833
at @ vue.runtime.esm.js:1754
Promise.then (async)
ci @ vue.runtime.esm.js:1802
ut @ vue.runtime.esm.js:1846
t.$nextTick @ vue.runtime.esm.js:4513
l @ vuedraggable.js:60
(anonymous) @ vuedraggable.js:72
c @ Sortable.js:1326
_onDrop @ Sortable.js:985
handleEvent @ Sortable.js:1044
createError.js:16 Uncaught (in promise) Error: Request failed with status code 400
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.9d9b928f87198951289f.js:6:134053)
t.exports @ createError.js:16
t.exports @ settle.js:18
h.(anonymous function) @ xhr.js:77
Promise.then (async)
S.async @ runtime.js:241
rewardSorted @ column.vue?5511:462
e @ vue.runtime.esm.js:2023
t.$emit @ vue.runtime.esm.js:2534
(anonymous) @ vuedraggable.js:61
(anonymous) @ vue.runtime.esm.js:1833
at @ vue.runtime.esm.js:1754
Promise.then (async)
ci @ vue.runtime.esm.js:1802
ut @ vue.runtime.esm.js:1846
t.$nextTick @ vue.runtime.esm.js:4513
l @ vuedraggable.js:60
(anonymous) @ vuedraggable.js:72
c @ Sortable.js:1326
_onDrop @ Sortable.js:985
handleEvent @ Sortable.js:1044
```

**Comment by Alys** [comment]
I'm closing this because we're no longer seeing VersionErrors in the logs. The current behaviour of this bug is reported in https://github.com/HabitRPG/habitica/issues/10406
