### ISSUE TITLE
Party header sort order not working reliably

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10996]
@ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) is having a problem with the sort order in the party header and first reported it about four days ago. I haven't been able to replicate it or seen other reports but it's a consistent problem for ravenlune. Their browser is Chrome 72

**ravenlune**:
"when you pick a different sort option for your party header, is it supposed to keep resetting when you sync? Because it keeps doing that and I don't remember that before. Tried Clear Browser Data as usual."

"Further testing reveals something stranger...? Okay, so say right now I have party sort A. I keep trying to change it to party sort B but with every sync it changes back to A. I turn off all Tampermonkey userscripts, refresh, and now party sort B has stuck. I now try to change it to party sort C, but it keeps resetting to B. Now I deduce Tampermoneky is not the problem, so I turn it back on. But party sort A has returned...

And I am retrying different things and getting very confused now. Also, it sometimes seems that my header will not change, but when I click out of the pop-up and open it again, the pop-up saved what I tried to change it to. I don't know if that's actually just normal."

**Alys**: 
"What's supposed to happen is that when you select an option from the 'Sort by ...' dropdown or the 'Asc'/'Desc' dropdown, the list in the members pop-up is meant to change immediately but nothing else will happen. If you then click 'Apply Sort Options to Party Header' the settings from both those drop-downs are saved to your own account (so you'll see the purple sync bar appear at the top of the page and then disappear after a second or so) and the order displayed in the header is changed straight away.

"This should work the same way regardless of whether you use the 'View Party' button in the header or the 'Member List' badge in the party page to change the order. It will also work if you use the 'Member List' badge in any guild but that's a bug - that's not meant to have the 'Apply Sort Options to Party Header' link. Which of those three buttons are you clicking on to change the party sort?

"Were you seeing any error messages at the time, even if they seemed unrelated? E.g., 'notification not found' or any others?"

**ravenlune**:
"I can't remember any error messages. Any other ones that day were maybe hours before? So I was just clicking the party header on the tasks screen and changing it from there. It doesn't seem like there was anything else of interest."

**Alys**: 
"Are you still noticing sorting problems now?"

**ravenlune**:
"The party sort issue has been happening each day since I reported it. Though it has become more inconsistent in which sort option it resets back to."

**Alys**: 
"Please go to the Party page, then open the Developer Console or JavaScript Console in your browser, then reload the party page with your browser's refresh button. Once it's fully reloaded, try sorting the party header again. After you see the bug happening, copy everything that appears in the Console and paste it here."

**ravenlune**:
Here it is:
```
Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
cloudfront.loggly.com/js/loggly.tracker-latest.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at m.zone (https://habitica.com/static/js/vendor.319ae7fe05ff1475ca9a.js:1:12932)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:274482)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:19121)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:394018)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:647230)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:386862)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:646528)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:645869)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:645567)
    at n (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:101)
    at window.webpackJsonp (https://habitica.com/static/js/manifest.88081161d13c0335bf78.js:1:418)
    at https://habitica.com/static/js/app.3ed0bf8dd6a0a3ab0108.js:1:1
x @ moment.js:293
api.amplitude.com/:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
SBPageExtension.js:3 SBBrowserInjectChrome
SBPageExtension.js:2175 PAGEEXT FINISHED: browserInject=[object Object]
api.amplitude.com/:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by shanaqui** [comment]
Ravenlune has now commented that this issue has resolved since they joined a new party.

**Comment by shanaqui** [comment]
Report from them today:

> So, uhm, the party sort bug started happening again, no idea what caused it as I'm certain it stopped for a good while before today. I haven't started using any new extensions with Habitica, or any major changes to how I use the website.

**Comment by SabreCat** [comment]
I don't think any of the JS errors are relevant. ERR_BLOCKED_BY_CLIENT appears to be a privacy extension or setting stopping Habitica from accessing third-party error logging and analytics services. "Active resource loading limit" looks like a client-side loading throttle? New on me but probably unrelated to sorting issue.

**Comment by cyxlan** [comment]
I have Privacy Badger and uBlock Origin; disabling them does not help with this issue. The thing I mentioned in the first post about Tampermonkey is also irrelevant because disabling all my extensions that affect Habitica (Tampermonkey, Stylus and the Chat Extension beta) has no effect. It is just as inconsistent with or without.

ERR_BLOCKED_BY_CLIENT stops happening if I disable Privacy Badger and uBlock Origin, and Active resource loading limit stopped happening after disabling a Chrome flag.

**Comment by SabreCat** [comment]
redphoenix gave a look at this in her party, and reported the following:

>The sort seems to work extremely haphazardly--sometimes the ascending/descending order doesn’t work until the second time it’s selected
>I found that sync would reset the header on these selections, SOMETIMES: Join Date Asc, Login Date Asc, Tier Asc
>on the Sort by Class option, it did not display in the correct order on the first attempt, but i could not duplicate it a second time. Ditto for Sort by Tier

**Comment by sachin-saxena-dev** [comment]
@SabreCat @shanaqui is this issue resolved or is it still up for a fix?

**Comment by Tressley** [comment]
This issue looks to have been resolved. If you're still experiencing this problem, please feel free to reopen the issue with additional information (OS/browser, steps to reproduce, screen recordings).
