### ISSUE TITLE
Scroll bar does not exist on first load

### ISSUE THREAD

**Issue by GiacomoLaw** [HabitRPG/habitica#11080]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 1951d08e-56af-445e-8554-f70633b6eaa6
  * Browser: Chrome latest GA release
  * OS: Windows 10 Home latest GA release

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

![image](https://user-images.githubusercontent.com/9038673/54869309-8135eb00-4d8e-11e9-9146-21775f5252c5.png)

On the first load of the site, the scroll bar is not there. However, on reload it appears again.

Navigating to different parts of the site, without reloading the page, such as from tasks to party, does not fix the issue.

I don't think this is the same as #11015, as equipping an item does not cause it.

#### Errors
```
vue.runtime.esm.js:1878 Error: Input data should be a String
    at a.parse (index.js:518)
    at a.render (index.js:543)
    at s (markdown.js:6)
    at jn (vue.runtime.esm.js:6620)
    at An (vue.runtime.esm.js:6541)
    at Array.Tn (vue.runtime.esm.js:6522)
    at m (vue.runtime.esm.js:6009)
    at u (vue.runtime.esm.js:5896)
    at h (vue.runtime.esm.js:5993)
    at u (vue.runtime.esm.js:5894)
```

```
Uncaught (in promise) Error: Request failed with status code 502
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.h.(/anonymous function) (https://habitica.com/static/js/vendor.0c12dd6348e4ce721b9d.js:6:141126)
```

```
vue.runtime.esm.js:1878 TypeError: Cannot read property 'style' of undefined
    at adjustPagePadding (drawer.vue?9911:176)
    at a.mounted (drawer.vue?9911:186)
    at at (vue.runtime.esm.js:1847)
    at xe (vue.runtime.esm.js:4169)
    at Object.insert (vue.runtime.esm.js:3114)
    at O (vue.runtime.esm.js:6286)
    at a.__patch__ (vue.runtime.esm.js:6505)
    at a.t._update (vue.runtime.esm.js:3901)
    at a.r (vue.runtime.esm.js:4019)
    at Zi.get (vue.runtime.esm.js:4419)
```

#### Warnings
```
moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.0c12dd6348e4ce721b9d.js:1:13987)
    at Object.<anonymous> (https://habitica.com/static/js/app.10a234e010e25e49f2f5.js:1:286019)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.10a234e010e25e49f2f5.js:1:21302)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.10a234e010e25e49f2f5.js:1:402777)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.10a234e010e25e49f2f5.js:1:640575)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.10a234e010e25e49f2f5.js:1:395621)
```

Not sure if these are related.

---

Thanks in advance

**Comment by SabreCat** [comment]
502 would be a server error, `moment().zone` is a known but (currently) benign warning, not sure about `Input data`. Most likely culprit would be the error about `style` in `adjustPagePadding`--thanks for including those messages!

**Comment by GiacomoLaw** [comment]
No worries, thanks for the great tool!

**Comment by paglias** [comment]
`adjustPagePadding ` should be fixed on delta, never seen this one before `vue.runtime.esm.js:1878 Error: Input data should be a String`. @GiacomoLaw is it still happening?

**Comment by GiacomoLaw** [comment]
It happened to me once again, but not again since. Seems random.

**Comment by GiacomoLaw** [comment]
Happened now. Here are the errors:

```
vue.runtime.esm.js:1878 Error: Input data should be a String
    at a.parse (index.js:518)
    at a.render (index.js:543)
    at s (markdown.js:6)
    at jn (vue.runtime.esm.js:6620)
    at An (vue.runtime.esm.js:6541)
    at Array.Tn (vue.runtime.esm.js:6522)
    at m (vue.runtime.esm.js:6009)
    at u (vue.runtime.esm.js:5896)
    at h (vue.runtime.esm.js:5993)
    at u (vue.runtime.esm.js:5894)
```

And a warning:

```
moment.js:293 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at g.zone (https://habitica.com/static/js/vendor.0c12dd6348e4ce721b9d.js:1:13987)
    at Object.<anonymous> (https://habitica.com/static/js/app.95bc82dd1c48ebc80011.js:1:286269)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.95bc82dd1c48ebc80011.js:1:21302)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.95bc82dd1c48ebc80011.js:1:403027)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.95bc82dd1c48ebc80011.js:1:640825)
    at n (https://habitica.com/static/js/manifest.74429b7c07826e5a6c35.js:1:101)
    at Object.<anonymous> (https://habitica.com/static/js/app.95bc82dd1c48ebc80011.js:1:395871)
```

Thanks

**Comment by paglias** [comment]
thank you @GiacomoLaw ! If you see it happen again could you click on the link to the source file in the console' It should open a code file with some code highlighted, can you post a screenshot of what you see there? 

Also, was this on the tasks page or somewhere else?

**Comment by GiacomoLaw** [comment]
Main page, habitica.com. Sure, I will try to remember to do so.

Thanks

**Comment by GiacomoLaw** [comment]
@paglias got it, here you go:

![image](https://user-images.githubusercontent.com/9038673/55281350-08ed9d80-532b-11e9-87b1-bbc5d6d1c5b0.png)

**Comment by paglias** [comment]
thanks @GiacomoLaw, found the issue!

**Comment by GiacomoLaw** [comment]
@paglias awesome, what was it?

**Comment by paglias** [comment]
Passing a non string to the markdown render function. Not sure exactly where that happened but I'm making sure anything is previously casted to a String
