### ISSUE TITLE
Amazon subscription payment failure: BillingAgreementConstraintsExist - BuyerConsentNotSet and cannot be confirmed

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11193]
SuperJunebug (a47506a0-6228-473b-980c-6e5a6007ffc6) reports:

**I am trying to buy the yearlong subscription using my Amazon account, but I keep getting an "Unexpected Error Occurred" message.**

The Loggly error is below. No subscription was created in their account.

SuperJunebug's post is still visible in the Report a Bug guild, dated about 17 hours before this issue was logged, so if any follow up questions are needed, they can be reached easily by PM there.

```
{"method":"POST",
"originalUrl":"/amazon/subscribe",
"headers":{"host":"habitica.com", "content-length":"95", "origin":"https://habitica.com", "x-user-timezoneoffset":"xxx",
"user-agent":"xxxxx",
"content-type":"application/json;charset=UTF-8",
"accept":"application/json,
 text/plain,
 */*",
"x-api-user":"a47506a0-6228-473b-980c-6e5a6007ffc6",
"x-client":"habitica-web",
"referer":"https://habitica.com/user/settings/subscription",
"accept-encoding":"gzip, deflate, br",
"accept-language":"en-US, en;q=0.9",
"x-cloud-trace-context":"1f8f38c699005805fd6282cbdd4d9286/14516622885620864566",
"via":"1.1 google",
"x-forwarded-for":"xxxxx",
"x-forwarded-proto":"https",
"connection":"Keep-Alive"},
"body":{"billingAgreementId":"B01-2477436-7522636", "subscription":"basic_12mo", "paymentType":"Amazon"},
"httpCode":500,
"isHandledError":false,

"fullError":{"type":"BillingAgreementConstraintsExist",
	"name":"BillingAgreementConstraintsExist",
	"body":{"ErrorResponse":{"$":{"xmlns":"http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01"},
	"Error":{"Type":"Sender",
	"Code":"BillingAgreementConstraintsExist",
	"Message":"The BillingAgreementId B01-2477436-7522636 has constraints BuyerConsentNotSet and cannot be confirmed."},
	"RequestId":"cd9902be-4da6-4579-8c44-9aeb33281c53"}}},

"timestamp":"2019-05-25T16:48:01.648Z",
"level":"error",
"message":"BillingAgreementConstraintsExist: The BillingAgreementId B01-2477436-7522636 has constraints BuyerConsentNotSet and cannot be confirmed.
    at new <anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/lib/error.js:22:15)
    at Object.apiError (/usr/src/habitrpg/node_modules/amazon-payments/lib/error.js:31:10)
    at /usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:210:31
    at Parser.<anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at SAXParser.onclosetag (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/usr/src/habitrpg/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/src/habitrpg/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/src/habitrpg/node_modules/sax/lib/sax.js:861:5)
    at SAXParser.write (/usr/src/habitrpg/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:403:31)
    at Parser.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:6:61)
    at Object.exports.parseString (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/xml2js/lib/xml2js.js:433:19)
    at parseMwsResponse (/usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:195:12)
    at Request._callback (/usr/src/habitrpg/node_modules/amazon-payments/lib/amazon.js:101:5)
    at Request.self.callback (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:460:23)
    at Request.<anonymous> (/usr/src/habitrpg/node_modules/amazon-payments/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:460:23)"}
```

**Comment by paglias** [comment]
Have they checked out the checkbox to authorize recurring biling?

**Comment by SabreCat** [comment]
This error occurs when they haven't checked the box; absent any report otherwise, closing this for now!
