### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined

### ISSUE THREAD

**Issue by freyacodes** [HabitRPG/habitica#11229]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: de91221c-6b7e-4614-8854-c5c6a6d3ffe7 (habitica.com)
  * Browser: N/A
  * OS: 5.1.7-arch1-1-ARCH (Arch Linux)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Posting this here as per [the wiki](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux)
I have been trying to create a solution for #11227. I am getting this error whenever I run `npm start`:

```
buffer.js:200
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:200:11)
    at Object.<anonymous> (/home/fred/git/habitica/website/server/libs/encryption.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at loader (/home/fred/git/habitica/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/fred/git/habitica/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/fred/git/habitica/website/server/libs/email.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at loader (/home/fred/git/habitica/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/fred/git/habitica/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

This is the offending line in `encryption.js`:
`const key = Buffer.from(SESSION_SECRET_KEY, 'hex');`

Full log of the installation: https://hastebin.com/uwamokuham.txt

I skipped installing npm, nodejs, git, gcc and mongodb as they were already installed. 

Versions:
```
git --version; npm --version; node --version; gcc --version; mocha --version 
git version 2.21.0
6.9.0
v11.15.0
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

6.1.4
```

**Comment by freyacodes** [comment]
My bad. Forgot to copy the example config to its rightful place.
