### ISSUE TITLE
challenge's tasksOrder array must not have duplicated task IDs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11385]
I have found a challenge that has duplicate task IDs in its tasksOrder object, as shown below. It's possible that this is causing https://github.com/HabitRPG/habitica/issues/11295 which is a highly inconvenient bug so I'm marking this as a high priority.

The expected behaviour is that every challenge task should appear once and only once in the challenge's tasksOrder object.

For anyone who wants to work on this, it might be best if you post here first with your intended fix to see if Habitica's staff approve of it (or look in the comments to see if staff have already described a preferred fix).

Loggly shows two errors during creation of the challenge (below), both saying `E11000 duplicate key error collection: habitica.tasks index: _id_ dup key: { : "[task id]" }`, and the task IDs in the errors match the duplicates. Thus it seems like a problem during the creation of those two challenge tasks caused the API to try to add the same task twice. The MongoDB index prevented the duplicate tasks being created but the IDs of the tasks were still inserted into the tasksOrder array (changing tasksOrder is done in a separate database update to the creation of the task).

Here is the challenge's tasksOrder object showing the duplicates:
```
{
    "_id": "703b2ea6-42a2-4b79-ae76-f6c871044aa7",
    "tasksOrder": {
        "habits": [],
        "dailys": [],
        "todos": [
            "d754dd2c-82b1-4bdc-b79d-9b568f79da7e",
            "dfdb1d51-d1ac-454c-8774-f3247333606a",
            "c32b7485-5c1d-41bd-9ab3-0acfd192dc0b",
            "f259e4a8-621a-4751-9b56-118ed5624118",
            "a987787d-1d55-4db4-abf8-b241f71fe6cc",
            "20493e76-925d-470f-935d-7a4ffe4d4572",
            "65b29b7c-11f6-4796-9117-5ab997312c8c",
            "61b11af7-4d59-420f-9e35-2d1001a3a6a5",
            "05a5bbac-19bf-4edc-8685-889cf9b0ef2e",
            "2bcae3ef-10e7-4ac8-adc5-5cd2eff8ee59",
            "a99ea1bf-6258-4c11-a448-29b1dbad3742",
            "e3766974-92bb-41b7-bf0d-a21b1b749eb1",
            "bd3f6dfe-ef63-44dd-ad46-79739bf06e8b",
            "1c1723d5-4e76-4c29-9044-31012130c99f",
            "1c1723d5-4e76-4c29-9044-31012130c99f", [duplicate]
            "9540175b-9cfc-4775-a366-8b0cc8bb0492",
            "fe972675-958b-4ee7-a209-f99ca779277c",
            "d62d4ada-9974-4d1e-a749-5a418045bbe6",
            "2d9e89d6-a7ca-4fce-b300-bbbee313f238",
            "2d9e89d6-a7ca-4fce-b300-bbbee313f238", [duplicate]
            "d69a8ebb-63ae-4186-811a-a6ed0b158de7",
            "40a90e58-f7c1-4835-a06b-8fc81835b66c",
            "82dcfb1e-7ba5-407b-af2b-5c90b23a5f98",
            "5f379bf1-ffe3-495e-8c02-a67fdfb9448b",
            "00f5a614-ccba-4754-be5b-1b4bafa607bc",
            "825fbd3f-d489-48c9-bc17-c38dcf94eb7e",
            "d991a6bf-65da-4ffc-9653-7de4d14bf1ea",
            "2d7a265d-2bea-4056-8950-626e97b63c61",
            "bfc7c2ba-4cd6-4149-8936-212ed8e02114",
            "af978892-c277-476f-abfe-4d1bad10035d",
            "a204f555-8435-459c-95a6-38f344b5acc3",
            "eb1c7576-ff1a-442f-b824-f75d1aa214a7",
            "4fed2a99-f4fd-4695-b3b5-9749fd473fca"
        ],
        "rewards": []
    },
}
```
As a note to other admins, I'm about to fix that specific challenge in the database so if you examine it you won't see that bug.

Here are the errors from Loggly:
```
{"method":"POST","originalUrl":"/api/v4/tasks/challenge/703b2ea6-42a2-4b79-ae76-f6c871044aa7","headers":{"host":"habitica.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json, text/plain, */*","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate, br","x-client":"habitica-web","x-api-user":"2d8797a8-291d-4545-8bba-180d4e8701a6","x-user-timezoneoffset":"-60","content-type":"application/json;charset=utf-8","content-length":"961","referer":"https://habitica.com/challenges/703b2ea6-42a2-4b79-ae76-f6c871044aa7","x-cloud-trace-context":"6be0496c3a99e5bd8c3434fd0394e2ac/1871857669922801192","via":"1.1 google","x-forwarded-for":"86.24.196.156, 35.227.223.241","x-forwarded-proto":"https","connection":"Keep-Alive"},"body":{"0":{"type":"todo","text":"October 18th: No-Beard Day","_id":"1c1723d5-4e76-4c29-9044-31012130c99f","notes":"The first Saturday in September was Beard Day, and the 18th of October is its mirror-universe counterpart: No Beard Day. Beard Day is the one with the menacing little goatee, though, so I think we all know which is the evil twin here. If you're planning to celebrate Movember, today is an opportunity to get a fresh start before the hairy adventure ahead. If you have a magnificent beard you're very protective of, though, celebrate Chocolate Cupcake Day instead. Try not to get the icing in your face-fuzz.","tags":[],"priority":"1.0","reminders":[],"attribute":"str","collapseChecklist":false,"checklist":[],"date":"2019-10-18T18:28:00.000Z"}},"httpCode":500,"isHandledError":false,"fullError":{"driver":true,"name":"MongoError","index":0,"code":11000,
"errmsg":"E11000 duplicate key error collection: habitica.tasks index: _id_ dup key: { : \"1c1723d5-4e76-4c29-9044-31012130c99f\" }"},
"timestamp":"2019-09-23T18:28:43.103Z","level":"error","message":"MongoError: E11000 duplicate key error collection: habitica.tasks index: _id_ dup key: { : \"1c1723d5-4e76-4c29-9044-31012130c99f\" }\n    at Function.create (/usr/src/habitrpg/node_modules/mongodb-core/lib/error.js:43:12)\n    at toError (/usr/src/habitrpg/node_modules/mongodb/lib/utils.js:149:22)\n    at /usr/src/habitrpg/node_modules/mongodb/lib/operations/collection_ops.js:859:39\n    at handler (/usr/src/habitrpg/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)\n    at fn (/usr/src/habitrpg/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-mongodb-core.js:77:13)\n    at /usr/src/habitrpg/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:149:49\n    at AsyncHooksCLS.runWithContext (/usr/src/habitrpg/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:127:20)\n    at contextWrapper (/usr/src/habitrpg/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:149:25)\n    at /usr/src/habitrpg/node_modules/mongodb-core/lib/connection/pool.js:397:18\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)"}
```

```
{"method":"POST","originalUrl":"/api/v4/tasks/challenge/703b2ea6-42a2-4b79-ae76-f6c871044aa7","headers":{"host":"habitica.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json, text/plain, */*","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate, br","x-client":"habitica-web","x-api-user":"2d8797a8-291d-4545-8bba-180d4e8701a6","x-user-timezoneoffset":"-60","content-type":"application/json;charset=utf-8","content-length":"665","referer":"https://habitica.com/challenges/703b2ea6-42a2-4b79-ae76-f6c871044aa7","x-cloud-trace-context":"8d29f7ce535e39d2e1c6baf7ec93cd00/3893207610475662796","via":"1.1 google","x-forwarded-for":"86.24.196.156, 35.227.223.241","x-forwarded-proto":"https","connection":"Keep-Alive"},"body":{"0":{"type":"todo","text":"October 14th: Dessert Day","_id":"2d9e89d6-a7ca-4fce-b300-bbbee313f238","notes":"October 14th: Dessert Day is the perfect excuse to indulge in your favourite after-dinner treat. Eat it before dinner, or instead of dinner. If you've always bought it, why not experiment with making it yourself?","tags":[],"priority":"1.0","reminders":[],"attribute":"str","collapseChecklist":false,"checklist":[],"date":"2019-10-14T18:23:00.000Z"}},"httpCode":500,"isHandledError":false,"fullError":{"driver":true,"name":"MongoError","index":0,"code":11000,
"errmsg":"E11000 duplicate key error collection: habitica.tasks index: _id_ dup key: { : \"2d9e89d6-a7ca-4fce-b300-bbbee313f238\" }"},"
timestamp":"2019-09-23T18:24:21.502Z","level":"error","message":"MongoError: E11000 duplicate key error collection: habitica.tasks index: _id_ dup key: { : \"2d9e89d6-a7ca-4fce-b300-bbbee313f238\" }\n    at Function.create (/usr/src/habitrpg/node_modules/mongodb-core/lib/error.js:43:12)\n    at toError (/usr/src/habitrpg/node_modules/mongodb/lib/utils.js:149:22)\n    at /usr/src/habitrpg/node_modules/mongodb/lib/operations/collection_ops.js:859:39\n    at handler (/usr/src/habitrpg/node_modules/mongodb-core/lib/topologies/replset.js:1155:22)\n    at /usr/src/habitrpg/node_modules/mongodb-core/lib/connection/pool.js:397:18\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)"}
```

**Comment by cheng-shiqi** [comment]
How about we adding some checking code to prevent inserting duplicated task ID to the `taskOrder `objcect, to the `createTasks` function in the `habitica/website/server/libs/taskManager.js`? 
https://github.com/HabitRPG/habitica/blob/5b57d91a9b66b0cae015084d8f152283b356e51d/website/server/libs/taskManager.js#L109-L141

As we can see from the code above, The `createTasks`  function save `user/challenge/group` (line 130) before `task`(line 141). So if there is a duplicated ID, it will only be checked , by mongo, after saving task, before that it's already been pushed to the `taskOrder `in db.

I submited my fix in a draft [PR](https://github.com/HabitRPG/habitica/pull/11408#issue-325642288) for you guys to review. since my solution can not remove the duplicated IDs already add in the challenge, I guess it only partially fix this issue.

**Comment by Alys** [comment]
@cheng-shiqi Thanks for the PR! I've marked this issue as in progress for you.

Don't worry about the challenges that already contain duplicate task IDs in the tasksOrder arrays. Admins can find and remove those manually or with a script.
