### ISSUE TITLE
Trouble setting up local Habitica server for contributing

### ISSUE THREAD

**Issue by actuday6418** [HabitRPG/habitica#11789]
This question was asked first in stackoverflow and then referenced in the Habitica Blacksmith's guild. I'm in the process of setting up Habitica locally for contributing, and I get a ton of errors when running npm start in the Habitica directory, and also with npm install. I can't make the slightest sense of this and any help would be much appreciated. I'm running Linux Mint Tina with npm 6.13.4 and node 12.4.1 as recommended by the Habitica local setup guide for Ubuntu. 

 

       actuday@PUTER:~/Dev_Stuff/Habitica/habitica$ npm start
    
    > habitica@4.129.2 start /home/actuday/Dev_Stuff/Habitica/habitica
    > gulp nodemon
    
    [17:58:50] Using gulpfile ~/Dev_Stuff/Habitica/habitica/gulpfile.js
    [17:58:50] Starting 'nodemon'...
    [17:58:51] Finished 'nodemon' after 451 ms
    [17:58:51] [nodemon] 1.19.4
    [17:58:51] [nodemon] to restart at any time, enter `rs`
    [17:58:51] [nodemon] watching dir(s): *.*
    [17:58:51] [nodemon] watching extensions: js,mjs,json
    [17:58:51] [nodemon] starting `node ./website/server/index.js`
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! habitica@4.129.2 start: `gulp nodemon`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the habitica@4.129.2 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/actuday/.npm/_logs/2020-01-15T12_28_52_489Z-debug.log
    actuday@PUTER:~/Dev_Stuff/Habitica/habitica$ (node:12174) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
    (node:12174) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
    events.js:200
          throw er; // Unhandled 'error' event
          ^
    
    Error: write EPIPE
        at process.target._send (internal/child_process.js:806:20)
        at process.target.send (internal/child_process.js:676:19)
        at sendHelper (internal/cluster/utils.js:22:15)
        at send (internal/cluster/child.js:190:10)
        at EventEmitter.cluster._getServer (internal/cluster/child.js:89:3)
        at listenInCluster (net.js:1367:11)
        at Server.listen (net.js:1442:7)
        at Object.<anonymous> (/home/actuday/Dev_Stuff/Habitica/habitica/website/server/server.js:29:8)
        at Module._compile (internal/modules/cjs/loader.js:955:30)
        at Module._compile (/home/actuday/Dev_Stuff/Habitica/habitica/node_modules/pirates/lib/index.js:99:24)
        at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Object.newLoader [as .js] (/home/actuday/Dev_Stuff/Habitica/habitica/node_modules/pirates/lib/index.js:104:7)
        at Module.load (internal/modules/cjs/loader.js:811:32)
        at Function.Module._load (internal/modules/cjs/loader.js:723:14)
        at Module.require (internal/modules/cjs/loader.js:848:19)
        at require (internal/modules/cjs/helpers.js:74:18)
    Emitted 'error' event on Worker instance at:
        at process.<anonymous> (internal/cluster/worker.js:31:12)
        at process.emit (events.js:223:5)
        at process.EventEmitter.emit (domain.js:475:20)
        at internal/child_process.js:810:39
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      errno: 'EPIPE',
      code: 'EPIPE',
      syscall: 'write'
    }

That second command execution about half way through the terminal output acually got there on it's own a few seconds after the first one. I didn't even hit enter.

npm install gives me 

        actuday@PUTER:~/Dev_Stuff/Habitica/habitica$  npm install
    
    > habitica@4.129.2 postinstall /home/actuday/Dev_Stuff/Habitica/habitica
    > gulp build && cd website/client && npm install
    
    [18:14:04] Using gulpfile ~/Dev_Stuff/Habitica/habitica/gulpfile.js
    [18:14:04] Starting 'build'...
    [18:14:04] Starting '<anonymous>'...
    [18:14:04] Finished '<anonymous>' after 445 μs
    [18:14:04] Finished 'build' after 1.81 ms
    
    > habitica-client@1.0.0 postinstall /home/actuday/Dev_Stuff/Habitica/habitica/website/client
    > node ./scripts/npm-postinstall.js
    
    npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    audited 83139 packages in 7.198s
    
    26 packages are looking for funding
      run `npm fund` for details
    
    found 2 moderate severity vulnerabilities
      run `npm audit fix` to fix them, or `npm audit` for details
    
    ┌───────────────────────────────────────────────────────────┐
    │                  npm update check failed                  │
    │            Try running with sudo or get access            │
    │           to the local update config store via            │
    │ sudo chown -R $USER:$(id -gn $USER) /home/actuday/.config │
    └───────────────────────────────────────────────────────────┘
    npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
    
    audited 21908 packages in 14.788s
    
    7 packages are looking for funding
      run `npm fund` for details
    
    found 3 vulnerabilities (1 low, 2 high)
      run `npm audit fix` to fix them, or `npm audit` for details
    
    ┌───────────────────────────────────────────────────────────┐
    │                  npm update check failed                  │
    │            Try running with sudo or get access            │
    │           to the local update config store via            │
    │ sudo chown -R $USER:$(id -gn $USER) /home/actuday/.config │
    └───────────────────────────────────────────────────────────┘

**Comment by paglias** [comment]
Hi @actuday6418 have you tried increasing the number of allowed file watches as described here https://github.com/HabitRPG/habitica/issues/11592#issuecomment-564304863?

**Comment by actuday6418** [comment]
YES!! It works now! Thank you!
