### ISSUE TITLE
highlightMentions crashes when square brackets are used

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12118]
Still investigating exactly what causes this but:

```
TypeError: Cannot read property 'references' of undefined
    at Array.link (/usr/src/habitrpg/node_modules/markdown-it/lib/rules_inline/link.js:101:26)
    at ParserInline.tokenize (/usr/src/habitrpg/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/usr/src/habitrpg/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/usr/src/habitrpg/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
    at Core.process (/usr/src/habitrpg/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/usr/src/habitrpg/node_modules/markdown-it/lib/index.js:523:13)
    at findTextAndCodeBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:98:44)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:139:29)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/chat.js:246:88)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

^ note that the line numbers might not match exactly the source files

It seems ton  happen when square brackets are used outside of links, for example:

```
[1] more text here
```

```
[test]
```

**Comment by paglias** [comment]
Looks like markdown-it requires the env parameter to be passed even when not used when using `.parse`, see https://markdown-it.github.io/markdown-it/#MarkdownIt.parse and https://github.com/markdown-it/markdown-it/issues/593

The strange thing is that they don't throw an error even if it's mandatory and it only fails in some cases

cc @benkelaar
