### ISSUE TITLE
chat messages containing ( or ) or [ inside backticks can't be posted: highlightMentions.js problem

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12138]
If a chat message contains `(` and/or `)` and/or `[` inside backticks, then the message can't be posted.

The user sees "An unexpected error occurs" and the errors below appear in the server logs.

If the message contains `[` inside backticks, the server error is:
```
httpCode:500
isHandledError:false
level:error
message:SyntaxError: Invalid regular expression: /` ?[ ?`/: Unterminated character class
    at new RegExp (<anonymous>)
    at createCodeBlockRegex (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:88:10)
    at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:106:28
    at Array.forEach (<anonymous>)
    at findTextAndCodeBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:105:14)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:141:29)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/chat.js:246:88)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
method:POST
originalUrl:/api/v4/groups/85dd1be6-336b-4e53-9949-2c09150b4035/chat
timestamp:2020-04-27T08:53:31.558Z
```

If the message contains `(` or `)` inside backticks, the server error is:
```
httpCode:500
isHandledError:false
level:error
message:TypeError: Cannot read property 'index' of null
    at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:109:15
    at Array.forEach (<anonymous>)
    at findTextAndCodeBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:105:14)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:141:29)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/chat.js:246:88)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
method:POST
originalUrl:/api/v4/groups/85dd1be6-336b-4e53-9949-2c09150b4035/chat
```

**Comment by paglias** [comment]
@benkelaar is this something you might be able to look into? thanks

**Comment by paglias** [comment]
Seems to happen with asterisks as well `{"message":"`*hello*`"},"query":{},"httpCode":500,"isHandledError":false,"fullError":{},"level":"error","message":"SyntaxError: Invalid regular expression: /` ?*hello* ?`/: Nothing to repeat` and ``{"message":"`*`"},"query":{},"httpCode":500,"isHandledError":false,"fullError":{},"level":"error","message":"SyntaxError: Invalid regular expression: /` ?* ?`/: Nothing to repeat``

**Comment by Alys** [comment]
@Nakonana has done some additional testing and says:
"asterisk * and \ inside of backticks don't seem to work either :o"

Here's the errors for * and \ respectively:

```
"SyntaxError: Invalid regular expression: /` ?* ?`/: Nothing to repeat\n at new RegExp (<anonymous>)
at createCodeBlockRegex (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:88:10)
```

```
"message":"TypeError: Cannot read property 'index' of null
 at /usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:109:15
```

**Comment by Alys** [comment]
From @SuperSaraA:

"I also found through trial and error that ?^$ + between backticks make my Andriod app say server connection lost the same way it does with the * and \ signs."

Looks like it's any character that has special meaning in a regex.

**Comment by benkelaar** [comment]
Ah, of course, forgot regex escape! Fix should be fairly simple. Great catch! Thanks!

**Comment by benkelaar** [comment]
Sorry about that. That pull request should fix it.
