### ISSUE TITLE
npm ERR! habitica@4.141.1 start: `gulp nodemon` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12198]
Hi, I am using NodeJS 12.10.0 and running the **npm start** server start command and getting the following error.

```
$ npm start

> habitica@4.141.1 start /home/liga/habitica
> gulp nodemon

[19:31:08] Using gulpfile ~/habitica/gulpfile.js
[19:31:08] Starting 'nodemon'...
[19:31:08] Finished 'nodemon' after 28 ms
[19:31:08] [nodemon] 2.0.2
[19:31:08] [nodemon] to restart at any time, enter `rs`
[19:31:08] [nodemon] watching dir(s): *.*
[19:31:08] [nodemon] watching extensions: js,mjs,json
[19:31:08] [nodemon] starting `node ./website/server/index.js`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.141.1 start: `gulp nodemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.141.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liga/.npm/_logs/2020-05-12T17_31_11_881Z-debug.log
```

My log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v12.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle habitica@4.141.1~prestart: habitica@4.141.1
6 info lifecycle habitica@4.141.1~start: habitica@4.141.1
7 verbose lifecycle habitica@4.141.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle habitica@4.141.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/liga/habitica/node_modules/.bin:/home/liga/bin:/home/liga/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle habitica@4.141.1~start: CWD: /home/liga/habitica
10 silly lifecycle habitica@4.141.1~start: Args: [ '-c', 'gulp nodemon' ]
11 silly lifecycle habitica@4.141.1~start: Returned: code: 1  signal: null
12 info lifecycle habitica@4.141.1~start: Failed to exec start script
13 verbose stack Error: habitica@4.141.1 start: `gulp nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid habitica@4.141.1
15 verbose cwd /home/liga/habitica
16 verbose Linux 4.4.0-142-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.10.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error habitica@4.141.1 start: `gulp nodemon`
22 error Exit status 1
23 error Failed at the habitica@4.141.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by paglias** [comment]
what happens if you try to run `node ./website/server/index.js ` instead of `npm start`?

**Comment by sergey-prosvirnin** [comment]
Amazingly, it works! Thank you!

**Comment by sergey-prosvirnin** [comment]
By the way, I noticed another mistake when launching **npm start**.

```
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:676:19)
    at sendHelper (internal/cluster/utils.js:22:15)
    at send (internal/cluster/child.js:190:10)
    at EventEmitter.cluster._getServer (internal/cluster/child.js:89:3)
    at listenInCluster (net.js:1359:11)
    at Server.listen (net.js:1434:7)
    at Object.<anonymous> (/home/liga/habitica/website/server/server.js:29:8)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._compile (/home/liga/habitica/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.newLoader [as .js] (/home/liga/habitica/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:27:12)
    at process.emit (events.js:209:13)
    at process.EventEmitter.emit (domain.js:476:20)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by sergey-prosvirnin** [comment]
Why is your solution working?

**Comment by sergey-prosvirnin** [comment]
Yes, as far as I can see in docker-compose.yml.

**Comment by paglias** [comment]
Hmm I haven't worked with docker for a while, could you check your config.json file exists and has the same content as config.json.example?

**Comment by sergey-prosvirnin** [comment]
https://github.com/HabitRPG/habitica/issues/12199 - here I tried to run the docker, but it didn't work.

**Comment by sergey-prosvirnin** [comment]
> Hmm I haven't worked with docker for a while, could you check your config.json file exists and has the same content as config.json.example?

#12199 - here I tried to run the docker, but it didn't work.

**Comment by paglias** [comment]
Which operating system are you on? Based on your OS there are separate guides here https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally and each of them has a section to troubleshoot issues

**Comment by sergey-prosvirnin** [comment]
> На какой операционной системе вы работаете? В зависимости от вашей ОС здесь есть отдельные руководства [https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally,](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally) и у каждого из них есть раздел для устранения проблем.

I am using Ubuntu Xenial 16.04 and I see that my problem with Docker is similar to MongoDB not working properly. And by the way, the link to solve the problem is broken now.

![image](https://user-images.githubusercontent.com/24830345/81790257-d4787900-950d-11ea-8137-28129c3592f3.png)

**Comment by paglias** [comment]
For the error with `npm start` have you tried this section?

<img width="720" alt="Schermata 2020-05-13 alle 10 37 42" src="https://user-images.githubusercontent.com/589911/81790521-ccb4d680-9505-11ea-9924-667f4f50b866.png">

**Comment by Alys** [comment]
> And by the way, the link to solve the problem is broken now.

@sergey-prosvirnin Thanks for telling us! The "Install MongoDB" section was removed when the installation process was made an automatic part of the docker install, however you're right that it's still needed for troubleshooting. I've added it back to the Docker instructions with a link to MongoDB's manual.

If you notice other documentation problems, you'd be welcome to fix them yourself if you wish or tell us here and we'll fix them.

**Comment by sergey-prosvirnin** [comment]
> За ошибку с `npm start`вы пробовали этот раздел?
> 
> <img alt="Schermata 2020-05-13 алла 10 37 42" width="720" src="https://user-images.githubusercontent.com/589911/81790521-ccb4d680-9505-11ea-9924-667f4f50b866.png">

Thank you, it worked for me! Now the npm start works!

**Comment by paglias** [comment]
That's great @sergey-prosvirnin !
