### ISSUE TITLE
buffer.js:293 throw new ERR_INVALID_ARG_TYPE(   ^  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12202]
Hey, it's me again! I'm trying to deploy the habitica server and get an exception.

```
> habitica@4.141.2 start /home/liga/habitica
> gulp nodemon

[19:50:52] Using gulpfile ~/habitica/gulpfile.js
[19:50:52] Starting 'nodemon'...
[19:50:52] Finished 'nodemon' after 32 ms
[19:50:52] [nodemon] 2.0.2
[19:50:52] [nodemon] to restart at any time, enter `rs`
[19:50:52] [nodemon] watching dir(s): *.*
[19:50:52] [nodemon] watching extensions: js,mjs,json
[19:50:52] [nodemon] starting `node ./website/server/index.js`
buffer.js:293
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:293:9)
    at Object.<anonymous> (/home/liga/habitica/website/server/libs/encryption.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module._compile (/home/liga/habitica/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.newLoader [as .js] (/home/liga/habitica/node_modules/pirates/lib/index.js:104:7)
```

**Comment by sergey-prosvirnin** [comment]
It's a simple mistake, I just forgot to copy. If you have the same problem, do **cp config.json.example config.json**.
