### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module. Habitica and the habitrpg-email-server.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12310]
Hello! I'm trying to use **habitica** and the **habitrpg-email-server** in a productive mode. I directly use **process.env.NODE_ENV = 'production';** in **index.js**, but still get errors of the following type.

```
> habitica@4.141.2 start C:\Users\Sergei\WebstormProjects\liga
> gulp nodemon

[18:54:46] Using gulpfile ~\WebstormProjects\liga\gulpfile.js
[18:54:46] Starting 'nodemon'...
[18:54:46] Finished 'nodemon' after 49 ms
[18:54:46] [nodemon] 2.0.2
[18:54:46] [nodemon] to restart at any time, enter `rs`
[18:54:46] [nodemon] watching dir(s): *.*
[18:54:46] [nodemon] watching extensions: js,mjs,json
[18:54:46] [nodemon] starting `node ./website/server/index.js`
production
C:\Users\Sergei\WebstormProjects\liga\website\server\libs\gcpTraceAgent.js:1
import nconf from 'nconf';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Sergei\WebstormProjects\liga\website\server\index.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
[18:54:46] [nodemon] app crashed - waiting for file changes before starting...
```

 Attempts were made to fix this by adding **"type": "module"** to package.json, running **--experimental-modules** and changing the **_index.js_** extension to **_index.mjs._** How do they arise and why can't I use all the features of the product mode implicitly?

P.S. I use Node.js v12.11.1.

**Comment by paglias** [comment]
Hi @sergey-prosvirnin , as mentioned in the previous issue we don't use Github as a support platform so these questions should be posted in the Aspiring Blacksmiths guild, moreover running Habitica in production mode is not documented publicly and we don't have plans to keep up to date docs for that in the near future. I'm going to answer this time but from the next one the issue will be closed.

That being said when running in production you should first run `gulp build:prod` then you'll find the compiled code in `website/transpiled-babel` and it should be run with `node ./website/transpiled-babel/index.js`
