### ISSUE TITLE
Entering "[]()" in chat causes "unexpected error"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12586]
If you try to post a message containing "[]()" you see "An unexpected error occured". This applies to private messages or posts to any group (Tavern, Guilds, Party).

The server error is `Cannot read property 'map' of undefined at toSourceMapRegex` (full error below), referring to (I assume) this code:
https://github.com/HabitRPG/habitica/blob/9adf5160feb0e5379d62c79a6aee1a5dd29a9874/website/server/libs/highlightMentions.js#L85-L105

```
httpCode:500
isHandledError:false
level:error
message:TypeError: Cannot read property 'map' of undefined
    at toSourceMapRegex (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:117:38)
    at Array.map (<anonymous>)
    at findTextBlocks (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:137:55)
    at highlightMentions (/usr/src/habitrpg/website/transpiled-babel/libs/highlightMentions.js:187:22)
    at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/chat.js:246:88)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
method:POST
originalUrl:/api/v4/groups/85dd1be6-336b-4e53-9949-2c09150b4035/chat
timestamp:2020-09-15T07:03:02.113Z
```

**Comment by benkelaar** [comment]
I'll look in to it.
