### ISSUE TITLE
setup/install under xubuntu

### ISSUE THREAD

**Issue by quaasi** [HabitRPG/habitica#1277]
Hi @lefnire,

I've seen this great project and found that this is exactly was I was looking for all the years. I started immediatly using the app. As I'm a JS developer I felt I want to give somthing back and I wanted to help and fix some bugs. But unfortunately I could not get it run locally. I followed the instructions on the wiki page

```
$ node --version
v0.8.25
$ npm --version
1.2.30
$ sudo service mongodb start
start: Job is already running: mongodb
$ npm install
npm WARN package.json habitrpg@0.0.0-151 No repository field.
npm WARN package.json habitrpg-shared@0.0.0 No repository field.
npm WARN package.json racer-db-mongo@0.3.14 No repository field.
npm WARN package.json icalendar@0.6.4 No repository field.
npm WARN package.json expect.js@0.2.0 No repository field.
npm WARN package.json uglify-js@2.3.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json ansi-color@0.2.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json fresh@0.1.0 No repository field.
npm WARN package.json cookie-signature@1.0.1 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json bytes@0.2.0 No repository field.
npm WARN package.json uid2@0.0.2 No repository field.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN unmet dependency /home/micha/projects/habitrpg/node_modules/nconf requires async@'0.1.x' but will load
npm WARN unmet dependency /home/micha/projects/habitrpg/node_modules/async,
npm WARN unmet dependency which is version 0.2.9
npm WARN unmet dependency /home/micha/projects/habitrpg/node_modules/nconf requires optimist@'0.3.x' but will load
npm WARN unmet dependency /home/micha/projects/habitrpg/node_modules/optimist,
npm WARN unmet dependency which is version 0.5.2

$ node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/micha/projects/habitrpg/node_modules/nconf/lib/nconf/formats.js:8:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

Do you have any ideas?

**Comment by lefnire** [comment]
Strange, all your steps look fine. Let's try again from scratch to see if it makes a difference:

``` shell
$ rm -rf node_modules && npm cache clean
$ npm install
$ node server.js
```

I've seen this before, but I remember it being erratic / irregular (couldn't pinpoint the cause, but then it suddenly getting fixed for no reason)

**Comment by quaasi** [comment]
Thanks for your fast answer. Will test this soon.

**Comment by quaasi** [comment]
It works! Great! 
Thanks
