### ISSUE TITLE
Undefined userId error

### ISSUE THREAD

**Issue by glenwinters** [HabitRPG/habitica#133]
I received a pop-up with this error:

```
TypeError: Cannot read property 'userId' of undefined
at $.sortable.dropOnEmpty (/src/app/index.coffee:32:52)
at onRoute (/node_modules/derby/lib/derby.browser.js:71:5)
at run (/node_modules/derby/node_modules/tracks/lib/router.js:109:3)
at onMatch (/node_modules/derby/node_modules/tracks/lib/router.js:85:14)
at renderQueued (/node_modules/derby/node_modules/tracks/lib/router.js:126:12)
at renderTransitional (/node_modules/derby/node_modules/tracks/lib/router.js:119:10)
at render (/node_modules/derby/node_modules/tracks/lib/router.js:93:10)
at Object.History.refresh (/node_modules/derby/node_modules/tracks/lib/History.js:55:5)
at SocketNamespace.eval (/node_modules/derby/lib/refresh.js:35:24)
at SocketNamespace.EventEmitter.emit [as $emit] (https://habitrpg.com/gen/tJtrSRVvE3k3pH5tiWlJGQ.js:633:15)
```

I was not able to click out of the error, but a refresh brought everything back to normal. I did not have to log back in.

**Comment by lefnire** [comment]
This should be fixed now, re-open if anyone has this issue again
