### ISSUE TITLE
TypeError: Cannot set property 'text' of undefined at module.exports.dotSet

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1415]
Seen periodically. I think this is for Racer corrupted tasks. It's on beta (current API), so not a rewrite issue. 

``` shell
TypeError: Cannot set property 'text' of undefined
    at module.exports.dotSet (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/habitrpg-shared/script/helpers.coffee:276:22)
    at Function.reduce (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/lodash/dist/lodash.js:2952:25)
    at Object.module.exports.dotSet (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/habitrpg-shared/script/helpers.coffee:274:16)
    at api.updateUser.user.save.res.json.err (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/src/server/api.coffee:582:17)
    at forOwn (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/lodash/dist/lodash.js:1301:15)
    at Function.forEach (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/lodash/dist/lodash.js:2595:9)
    at Object.api.updateUser (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/src/server/api.coffee:575:7)
    at api.batchUpdate.performAction (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/src/server/api.coffee:668:22)
    at api.batchUpdate.async.series.res.json (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/src/server/api.coffee:678:18)
    at async.series.results (/var/www/vhosts/habitrpg.com/releases/5017be09848a5e473103c012967c68133103b7a6/node_modules/async/lib/async.js:548:21)
```

**Comment by lefnire** [comment]
cleanup migration at https://github.com/lefnire/habitrpg/issues/1491 run, this should no longer happen
