### ISSUE TITLE
Server 500 error after midnight on Heroku

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#1417]
Don't know if this happened before but since it's 00.09 and some hours ago it didn't give this error, I think it's related to something that happen at midnigt like the cron that adjusts hp which had not been updated after midnight even though I had a non completed daily. 

But the error refers to `exp`.

```
500: MongoError: can't append to array using string field name [exp] 
at Object.toError (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:110:11) 
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:494:24 at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41) 
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18 
at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) 
at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20) 
at EventEmitter.emit (events.js:95:17) 
at null.<anonymous (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13) 
at EventEmitter.emit (events.js:98:17) 
at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22) 
at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:736:14) at Socket.EventEmitter.emit (events.js:92:17) 
at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) 
at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:526:21)(see Chrome console for more details).
```

![schermata del 2013-09-04 00 16 18](https://f.cloud.github.com/assets/589911/1076646/7d5dafae-14e6-11e3-8bd4-784fb00bd20f.png)

**Comment by lefnire** [comment]
Definitely cron. Something in habitrpg-shared/algos/cron conflicting with https://github.com/lefnire/habitrpg/blob/angular_rewrite/src/models/user.js . I'll start digging

**Comment by lefnire** [comment]
fixed, i think early users had a `user.history=[]` schema, where now it's `user.history={exp:[], todos:[]}`. I updated all users in the db, let's keep an eye if it happens again
