### ISSUE TITLE
Win 8 Local Install Issues

### ISSUE THREAD

**Issue by Shaners** [HabitRPG/habitica#1429]
After a fresh local install of the angular rewrite branch following the instructions as outlined in readme here: https://github.com/lefnire/habitrpg/tree/angular_rewrite
Everything seemed to work but attempting to auth using the FB user details in the copied over config.json (maybe I was supposed to set up a fresh user in the db instead?) it seemed to hang and upon refreshing it would show me the landing page but direct the url to "http://localhost:3000/static/front#/tasks". 
So it kind of seemed like the authentication worked but it kept serving me the landing page.
On win 8 pro.

**Comment by paglias** [comment]
Do you have problem with a normal signup, without facebook?

In config.json you must set you're facebook app api & secret.

If you open the browser console do you see any error?

**Comment by Shaners** [comment]
The more I think about it, it is probably just me not knowing how to properly setup users. When I try to sign up with any method it throws a js alert error about validators. Should I be manually creating users in the mongo HabitRPG db? Or is there another step after copying over example.config.json to config.json? Perhaps actually changing the details in config.json... 

-Shane

**Comment by paglias** [comment]
Have you set the mongodb path in config.json?

**Comment by Shaners** [comment]
Yea mongodb to server seems fine:
![server-log](https://f.cloud.github.com/assets/2374703/1092709/017c541e-1688-11e3-96dc-916787ac217b.png)
![mongo-log](https://f.cloud.github.com/assets/2374703/1092712/284a1cde-1688-11e3-83a6-2096a8cadf34.png)

Do get a browser console error on this strange page:
[17:01:18.751] Error: Permission denied to access property 'toString'
[17:01:20.028] "Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

The registration error:
![register-error](https://f.cloud.github.com/assets/2374703/1092864/c69e3cd0-168d-11e3-8790-8080e03fdab4.png)

**Comment by Shaners** [comment]
Weird I can go to //#/tasks and get this:
![tasks](https://f.cloud.github.com/assets/2374703/1092832/f6110250-168c-11e3-81a9-593cbaa99ae2.png)

**Comment by lefnire** [comment]
ok, part of this looks like you don't have the proper modules installed. do a `git pull origin angular_rewrite` to make sure you have our latest changes, and then do a `npm install` to make sure you have the latest modules.

The other part looks like bugs. Particularly I think it has to do with https://github.com/lefnire/habitrpg/issues/1422 . I'm going to be working on a fix for this right now, I'll notify you when it's done and see if it addresses the issue

**Comment by Shaners** [comment]
Weird now play button doesn't prompt for login and //#/tasks renders like this (all on one page):
![habitrpg_2013-09-05_19-23-06](https://f.cloud.github.com/assets/2374703/1093399/a0a36ace-169b-11e3-9b81-e6d5f424bf8d.png)

**Comment by lefnire** [comment]
Chrome errors? looks like something isn't getting loaded properly. I can skype you through this if you want.

**Comment by Shaners** [comment]
Gave it a go in a different environment (vista) and everything worked perfectly the first attempt. This could just be a Windows 8 thing, I think related Bower. I might just throw a VM on my laptop for on the go testing.
@lefnire should we keep this open?
*edit: closing this since it's not really a bug.

**Comment by Shaners** [comment]
weird:

```
Error: c:\Projects\habitrpg\views\index.jade:18
    16|     link(rel='stylesheet', href='/bower_components/bootstrap/docs/assets/css/bootstrap-responsive.css')
    17|     link(rel='stylesheet', href='/bower_components/angular-ui/build/angular-ui.css')
  > 18|     != css('index')
    19| 
    20|     // HabitRPG Shared
    21|     link(rel='stylesheet', href='/bower_components/habitrpg-shared/spritesheets.css')

c:\Projects\habitrpg\assets\css\index.styl:4
   1| @import "nib/vendor"
   2| 
   3| // Vendor Includes - include first so we can override
 > 4| @import "../../../public/bower_components/bootstrap-datepicker/css/datepicker.css"
   5| 
   6| // Custom includes
   7| @import "./tasks.styl"

failed to locate @import file ../../../public/bower_components/bootstrap-datepicker/css/datepicker.css

    at Evaluator.visitImport (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\evaluator.js:697:21)
    at Evaluator.Visitor.visit (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\evaluator.js:93:18)
    at Evaluator.visitRoot (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\evaluator.js:552:27)
    at Evaluator.Visitor.visit (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\evaluator.js:93:18)
    at Evaluator.evaluate (c:\Projects\habitrpg\node_modules\stylus\lib\visitor\evaluator.js:168:15)
    at Renderer.render (c:\Projects\habitrpg\node_modules\stylus\lib\renderer.js:79:26)
    at Object.exports.cssCompilers.cssCompilers.styl.compileSync (c:\Projects\habitrpg\node_modules\connect-assets\lib\assets.js:513:68)
    at ConnectAssets.compileCSS (c:\Projects\habitrpg\node_modules\connect-assets\lib\assets.js:333:37)
    at context.css (c:\Projects\habitrpg\node_modules\connect-assets\lib\assets.js:139:51)
    at eval (eval at <anonymous> (c:\Projects\habitrpg\node_modules\jade\lib\jade.js:152:8), <anonymous>:71:33)
    at c:\Projects\habitrpg\node_modules\jade\lib\jade.js:153:35
    at Object.exports.render (c:\Projects\habitrpg\node_modules\jade\lib\jade.js:197:10)
    at Object.exports.renderFile (c:\Projects\habitrpg\node_modules\jade\lib\jade.js:233:18)
    at View.exports.renderFile [as engine] (c:\Projects\habitrpg\node_modules\jade\lib\jade.js:218:21)
    at View.render (c:\Projects\habitrpg\node_modules\express\lib\view.js:76:8)
    at Function.app.render (c:\Projects\habitrpg\node_modules\express\lib\application.js:506:10)
    at ServerResponse.res.render (c:\Projects\habitrpg\node_modules\express\lib\response.js:760:7)
    at router.get.res.render.env (c:\Projects\habitrpg\src\routes\pages.js:8:14)
    at callbacks (c:\Projects\habitrpg\node_modules\express\lib\router\index.js:164:37)
    at param (c:\Projects\habitrpg\node_modules\express\lib\router\index.js:138:11)
    at pass (c:\Projects\habitrpg\node_modules\express\lib\router\index.js:145:5)
    at Router._dispatch (c:\Projects\habitrpg\node_modules\express\lib\router\index.js:173:5)
    at Object.router (c:\Projects\habitrpg\node_modules\express\lib\router\index.js:33:10)
    at next (c:\Projects\habitrpg\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at next (c:\Projects\habitrpg\node_modules\express\node_modules\connect\lib\proto.js:192:9)
    at resume (c:\Projects\habitrpg\node_modules\express\node_modules\connect\lib\middleware\static.js:60:7)
    at SendStream.error (c:\Projects\habitrpg\node_modules\express\node_modules\connect\lib\middleware\static.js:73:37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (c:\Projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:147:51)
    at SendStream.onStatError (c:\Projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:248:48)
    at c:\Projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:320:26
    at Object.oncomplete (fs.js:107:15)
```

**Comment by lefnire** [comment]
Can you try from the #develop branch now? We moved things around a bit: moved #develop/#master to #derby, moved #angular_rewrite to #develop/#master, deleted #angular_rewrite. #develop now tracks "edge" (all the newest changes), one of which was a big push by @paglias using grunt instead of our previous asset pipeline. Now you run `grunt start` instead of `npm install`. We'll need to update the readme to reflect this, but there's to get you started @Shaners

**Comment by Shaners** [comment]
@lefnire is it really `grunt start` instead of `npm install`? or `grunt start` instead of `npm start`?

**Comment by lefnire** [comment]
Sorry, #2

**Comment by Shaners** [comment]
Win8 spitting this out:

```
$ grunt start
Running "exec:start" (exec) task
6 Sep 23:53:20 - [nodemon] v0.7.10
6 Sep 23:53:20 - [nodemon] to restart at any time, enter `rs`
>> Error: spawn Unknown system errno 193
>>     at errnoException (child_process.js:980:11)
>>     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
6 Sep 23:53:20 - [nodemon] watching: c:\Projects\habitrpg
6 Sep 23:53:20 - [nodemon] starting `./start.sh ./server.js`
6 Sep 23:53:20 - [nodemon] exception in nodemon killing node
6 Sep 23:53:20 - [nodemon] reading ignore list
```

Going to give vista environment a try(previously has worked.) Also am drinking to see if that helps!

**Comment by Shaners** [comment]
Vista throwing the same error now:

```
Running "exec:start" (exec) task
7 Sep 00:31:56 - [nodemon] v0.7.10
7 Sep 00:31:56 - [nodemon] to restart at any time, enter `rs`
>> Error: spawn Unknown system errno 193
>>     at errnoException (child_process.js:980:11)
>>     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
7 Sep 00:31:56 - [nodemon] watching: C:\projects\habitrpg
7 Sep 00:31:56 - [nodemon] starting `./start.sh ./server.js`
7 Sep 00:31:56 - [nodemon] exception in nodemon killing node
7 Sep 00:31:56 - [nodemon] reading ignore list
```

Might be something similar to this: https://github.com/thingsinjars/Hardy/issues/5
Which looks like it was fixed with: https://github.com/ForbesLindesay/win-spawn

**Comment by paglias** [comment]
@Shaners I realized that there's a better way to start the server without exec:start that may be causing problems on Windows, I'll update the code and repost here when it's ready so you can try.

**Comment by paglias** [comment]
Ok @Shaners  I pushed the new code, try using the branch `paglias/grunt2`, run `npm install` and then `grunt run:dev` to start the server

**Comment by Shaners** [comment]
@paglias initially I was getting this error with grunt2 on npm install:

```
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\projects\habitrpg\node_modules\mongoose\node_modules\mongodb\node_modules\bson\build\binding.sln]
```

Cleared that up with a visual studio install but got this error on `grunt run:dev`

```
$ grunt run:dev
Running "clean:build" (clean) task

Running "stylus:build" (stylus) task
>> Error: public/css/index.styl:5
>>    1| @import "nib/vendor"
>>    2|
>>    3| // Vendor Includes - include first so we can override
>>    4| // Import only styles that do not have urls to images! Include them dir
ectly in the page!
>>  > 5| @import "../bower_components/bootstrap-datepicker/css/datepicker.css"
>>    6| @import "../bower_components/angular-ui/build/angular-ui.min.css"
>>    7| @import "../bower_components/bootstrap/docs/assets/css/bootstrap-respon
sive.css"
>>    8|
>>
>> failed to locate @import file ../bower_components/bootstrap-datepicker/css/da
tepicker.css
Warning: Stylus failed to compile. Use --force to continue.

Aborted due to warnings.
```

Throwing a --force on grunt run:dev worked but isn't rendering the page correctly and the play button wasn't functioning.

**Comment by paglias** [comment]
Check if that file exist in the bower components folder

**Comment by Shaners** [comment]
There we go, simple bower update and it's running now though the register modal isn't displaying correctly. Going to try a develop branch.

**Comment by paglias** [comment]
Fantastic! Yes you can try the develop branch since this code has been
merged now

**Comment by Shaners** [comment]
Develop works perfectly in win8. Instead of 'bower install -f' I used 'bower update' but not completely sure that it's necessary.

**Comment by paglias** [comment]
It should be used after install to update components, it shouldn't be needed unless a new version of a component is required by habit to work

**Comment by Shaners** [comment]
Any clue what is going on here?:

```
ReferenceError: C:\projects\habitrpg\views\index.jade:18
    16| 
    17|     // CSS Remember to update also in Grunfile.js cssmin task!
  > 18|     link(rel='stylesheet', href='/#{env.getBuildUrl("bower_components/bootstrap/docs/assets/css/bootstrap.css")}')
    19| 
    20|     link(rel='stylesheet', href='/#{env.getBuildUrl("app.css")}')
    21| 

filename is not defined
    at Object.getBuildUrl (C:\projects\habitrpg\src\middleware.js:60:10)
    at eval (eval at <anonymous> (C:\projects\habitrpg\node_modules\jade\lib\jade.js:152:8), <anonymous>:68:88)
    at C:\projects\habitrpg\node_modules\jade\lib\jade.js:153:35
    at Object.exports.render (C:\projects\habitrpg\node_modules\jade\lib\jade.js:197:10)
    at Object.exports.renderFile (C:\projects\habitrpg\node_modules\jade\lib\jade.js:233:18)
    at View.exports.renderFile [as engine] (C:\projects\habitrpg\node_modules\jade\lib\jade.js:218:21)
    at View.render (C:\projects\habitrpg\node_modules\express\lib\view.js:76:8)
    at Function.app.render (C:\projects\habitrpg\node_modules\express\lib\application.js:506:10)
    at ServerResponse.res.render (C:\projects\habitrpg\node_modules\express\lib\response.js:798:7)
    at router.get.res.render.env (C:\projects\habitrpg\src\routes\pages.js:8:14)
    at callbacks (C:\projects\habitrpg\node_modules\express\lib\router\index.js:164:37)
    at param (C:\projects\habitrpg\node_modules\express\lib\router\index.js:138:11)
    at pass (C:\projects\habitrpg\node_modules\express\lib\router\index.js:145:5)
    at Router._dispatch (C:\projects\habitrpg\node_modules\express\lib\router\index.js:173:5)
    at Object.router (C:\projects\habitrpg\node_modules\express\lib\router\index.js:33:10)
    at next (C:\projects\habitrpg\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at next (C:\projects\habitrpg\node_modules\express\node_modules\connect\lib\proto.js:192:9)
    at resume (C:\projects\habitrpg\node_modules\express\node_modules\connect\lib\middleware\static.js:60:7)
    at SendStream.error (C:\projects\habitrpg\node_modules\express\node_modules\connect\lib\middleware\static.js:73:37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (C:\projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:147:51)
    at SendStream.onStatError (C:\projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:248:48)
    at C:\projects\habitrpg\node_modules\express\node_modules\send\lib\send.js:320:26
    at Object.oncomplete (fs.js:107:15)
```

bootstrap.css seems to exist in the correct place.

Does it have something to do with this?

```
Running "cssmin:build" (cssmin) task
File build/app.css created.
File build/static.css created.
File build/bower_components/habitrpg-shared/dist/spritesheets.css created.
File build/bower_components/bootstrap/docs/assets/css/bootstrap.css created.
File build/bower_components/bootstrap/docs/assets/css/bootstrap-responsive.css created.
File build/bower_components/bootstrap/docs/assets/css/docs.css created.

Running "copy:build" (copy) task
Copied 1 files

Running "hashres:build" (hashres) task
build/app.css >> app-1613508a.css
build/static.css >> static-a4df1b09.css
build/favicon.ico >> favicon-8b58f6a1.ico
build/bower_components/bootstrap/docs/assets/css/bootstrap-responsive.css >> bootstrap-responsive-522ed013.css
build/bower_components/bootstrap/docs/assets/css/bootstrap.css >> bootstrap-68f33d27.css
build/bower_components/bootstrap/docs/assets/css/docs.css >> docs-2a91975c.css
build/bower_components/habitrpg-shared/dist/spritesheets.css >> spritesheets-d9215e2e.css
```
