### ISSUE TITLE
400: Bad Request when trying to buy hatching potion

### ISSUE THREAD

**Issue by lochnessa** [HabitRPG/habitica#1468]
I can buy eggs, but I cannot buy hatching potions. I have tried to buy three different types of potions, and each time, I get a 400 bad request.

**Comment by paglias** [comment]
Please try the following: open the chrome console, go to the network tab,
then try to buy a potion, a new request (with 400 error) will appear, click
on it and post here the response.

**Comment by lefnire** [comment]
ah yes, i'm able to replicate:

```
POST /api/v1/market/buy?type=hatchingPotion     at Object.exports.error (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/node_modules/express/node_modules/connect/lib/utils.js:62:13)
400 4ms    at IncomingMessage.module.exports (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/node_modules/express/node_modules/connect/lib/middleware/json.js:74:71)

    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
Error: invalid json
    at Object.exports.error (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/node_modules/express/node_modules/connect/lib/utils.js:62:13)
POST /api/v1/market/buy?type=hatchingPotion     at IncomingMessage.module.exports (/Users/lefnire/Dropbox/Sites/personal/habitrpg/website/node_modules/express/node_modules/connect/lib/middleware/json.js:74:71)
400     at IncomingMessage.EventEmitter.emit (events.js:92:17)
1ms    at _stream_readable.js:910:16

    at process._tickCallback (node.js:415:13)
```

I'll work on this right now

**Comment by lefnire** [comment]
pushed fix, refresh & try again
