### ISSUE TITLE
move preen-history from preen_cron.js to individual user cron (habitrpg-shared)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1492]
see migrations/preen_cron.js. When preen was run on the server, it would clean up unnecessarily large history entries for each user. User history objects collectively could constitute many multiple MB per user, making their initial page-load very slow. We need to move this history-preening to individual user cron, since it's now being calculated on the server (previously client-side slowdown was the reason we didn't do this).

**Comment by lefnire** [comment]
it's all js, and pretty thick. Might be best to wait till we have habitrpg-shared ported to js

**Comment by lefnire** [comment]
Now getting `Error: request entity too large`. It's likely because of history (this), or because of many completed Todos. https://github.com/HabitRPG/habitrpg/issues/1644 and https://github.com/HabitRPG/habitrpg/issues/1499

```
2013-11-05T18:07:35.966436+00:00 app[web.2]: Error: request entity too large
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at module.exports (/app/node_modules/express/node_modules/connect/node_modules/raw-body/index.js:16:15)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at json (/app/node_modules/express/node_modules/connect/lib/middleware/json.js:60:5)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at Object.bodyParser [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:53:5)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at Object.module.exports.forceSSL [as handle] (/app/src/middleware.js:14:3)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at Object.module.exports.cors [as handle] (/app/src/middleware.js:28:10)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966436+00:00 app[web.2]:     at Object.favicon [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/favicon.js:77:7)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Object.compress [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/compress.js:182:5)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Object.expressInit [as handle] (/app/node_modules/express/lib/middleware.js:30:5)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Object.query [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Function.app.handle (/app/node_modules/express/node_modules/connect/lib/proto.js:201:3)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Server.app (/app/node_modules/express/node_modules/connect/lib/connect.js:65:37)
2013-11-05T18:07:35.966795+00:00 app[web.2]:     at Server.EventEmitter.emit (events.js:98:17)
2013-11-05T18:07:35.967115+00:00 app[web.2]:     at HTTPParser.parser.onIncoming (http.js:2108:12)
2013-11-05T18:07:35.967115+00:00 app[web.2]:     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
2013-11-05T18:07:35.967115+00:00 app[web.2]:     at Socket.socket.ondata (http.js:1966:22)
2013-11-05T18:07:35.967115+00:00 app[web.2]:     at TCP.onread (net.js:525:27)
```

**Comment by lefnire** [comment]
ok, I added history preening and did as much manual testing as I could. There's some rudimentary automated testing in commit ^ . Let's see if this helps cut things down

Note, it didn't fix `Error: request entity too large`, looks like that was something else
