### ISSUE TITLE
Will not stay alive upon registration if deployed using Kubernetes

### ISSUE THREAD

**Issue by phluxx** [HabitRPG/habitica#15359]
As the title says, habitica will not deploy on Kubernetes in its current state. Logs are as follows:

```
> habitrpg@0.0.0-152 start /habitrpg
> gulp run:dev

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[02:44:14] Using gulpfile /habitrpg/gulpfile.js
[02:44:14] Starting 'nodemon'...
[02:44:14] Finished 'nodemon' after 1.71 ms
[02:44:14] Starting 'browserify'...
[02:44:14] Starting 'prepare:staticNewStuff'...
[02:44:14] Finished 'prepare:staticNewStuff' after 627 ms
[02:44:14] [nodemon] 1.9.2
[02:44:14] [nodemon] to restart at any time, enter `rs`
[02:44:14] [nodemon] watching: *.*
[02:44:14] [nodemon] starting `node ./website/src/server.js`
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[32minfo[39m: Express server listening on port 3000
[32minfo[39m: Connected with Mongoose
[02:44:28] Finished 'browserify' after 15 s
[02:44:28] Starting 'build:dev'...
[02:44:28] Starting 'grunt-build:dev'...
[02:44:28] [nodemon] restarting due to changes...
[02:44:28] [nodemon] starting `node ./website/src/server.js`
[4mRunning "cssmin:dist" (cssmin) task[24m
File common/dist/sprites/habitrpg-shared.css created: 753.85 kB → 652.54 kB → 42.06 kB (gzip)

[4mRunning "stylus:build" (stylus) task[24m
File website/build/app.css created.
File website/build/static.css created.

[32mDone, without errors.[39m
[02:44:32] Finished 'grunt-build:dev' after 4.04 s
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[32minfo[39m: Express server listening on port 3000
[32minfo[39m: Connected with Mongoose
[0mGET / [36m302 [0m21.900 ms - 70[0m
[0mGET /bower_components/css-social-buttons/css/zocial.css [36m304 [0m17.808 ms - -[0m
[0mGET /js/services/notificationServices.js [36m304 [0m15.723 ms - -[0m
[0mGET /js/services/sharedServices.js [36m304 [0m15.213 ms - -[0m
[0mGET /bower_components/jquery/dist/jquery.min.js [36m304 [0m15.138 ms - -[0m
[0mGET /bower_components/jquery-colorbox/jquery.colorbox-min.js [36m304 [0m15.383 ms - -[0m
[0mGET /js/controllers/authCtrl.js [36m304 [0m14.759 ms - -[0m
[0mGET /js/controllers/footerCtrl.js [36m304 [0m14.271 ms - -[0m
[0mGET /js/env.js [36m304 [0m14.158 ms - -[0m
[0mGET /js/services/statServices.js [36m304 [0m13.453 ms - -[0m
[0mGET /common/dist/scripts/habitrpg-shared.js [32m200 [0m47.495 ms - -[0m
[0mGET /common/dist/sprites/habitrpg-shared.css [32m200 [0m47.192 ms - -[0m
[0mGET / [36m302 [0m4.450 ms - 70[0m
[0mGET /static/front [32m200 [0m1627.065 ms - -[0m
[0mGET /bower_components/css-social-buttons/css/zocial.css [32m200 [0m6.473 ms - -[0m
[0mGET /front/staticstyle.css [32m200 [0m3.366 ms - -[0m
[0mGET /app.css [32m200 [0m15.452 ms - -[0m
[0mGET /common/dist/sprites/habitrpg-shared.css [32m200 [0m15.273 ms - -[0m
[0mGET /bower_components/jquery/dist/jquery.min.js [32m200 [0m6.618 ms - -[0m
[0mGET /common/dist/scripts/habitrpg-shared.js [32m200 [0m18.750 ms - -[0m
[0mGET /bower_components/angular/angular.js [32m200 [0m56.012 ms - -[0m
[0mGET /bower_components/angular-ui/build/angular-ui.js [32m200 [0m4.964 ms - -[0m
[0mGET /bower_components/jquery-colorbox/jquery.colorbox-min.js [32m200 [0m2.996 ms - -[0m
[0mGET /bower_components/hello/dist/hello.all.min.js [32m200 [0m6.116 ms - -[0m
[0mGET /bower_components/angular-loading-bar/build/loading-bar.js [32m200 [0m3.893 ms - -[0m
[0mGET /js/env.js [32m200 [0m1.767 ms - 585[0m
[0mGET /js/static.js [32m200 [0m1.820 ms - -[0m
[0mGET /js/services/notificationServices.js [32m200 [0m4.179 ms - -[0m
[0mGET /js/services/analyticsServices.js [32m200 [0m3.192 ms - -[0m
[0mGET /js/services/sharedServices.js [32m200 [0m2.162 ms - 242[0m
[0mGET /js/services/socialServices.js [32m200 [0m1.271 ms - 1023[0m
[0mGET /js/services/statServices.js [32m200 [0m2.661 ms - -[0m
[0mGET /common/script/public/userServices.js [32m200 [0m3.481 ms - -[0m
[0mGET /js/controllers/authCtrl.js [32m200 [0m7.060 ms - -[0m
[0mGET /js/controllers/footerCtrl.js [32m200 [0m6.527 ms - -[0m
[0mGET /favicon.ico [32m200 [0m3.243 ms - -[0m
[31merror[39m: RangeError: Invalid status code: 5739101
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/habitrpg/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/habitrpg/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.res.write (/habitrpg/node_modules/express/node_modules/connect/node_modules/compression/index.js:91:14)
    at ServerResponse.res.end (/habitrpg/node_modules/express/node_modules/connect/node_modules/compression/index.js:112:14)
    at ServerResponse.res.send (/habitrpg/node_modules/express/lib/response.js:176:8)
    at ServerResponse.res.json (/habitrpg/node_modules/express/lib/response.js:224:15)
    at auth.js:139:36
    at Promise.taskCallback (/habitrpg/node_modules/async/lib/async.js:468:21)
    at Promise.<anonymous> (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:172:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.reject (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:111:15)
    at Promise.error (/habitrpg/node_modules/mongoose/lib/promise.js:95:15)
    at Immediate.cb (/habitrpg/node_modules/mongoose/lib/query.js:1152:29)
    at Immediate._onImmediate (/habitrpg/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 ----------------------------


originalUrl: /api/v2/register?lang=en

auth: undefined | undefined

headers: {"host":"137.184.240.135:3000","connection":"keep-alive","content-length":"105","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","x-client":"habitica-web","origin":"http://137.184.240.135:3000","referer":"http://137.184.240.135:3000/static/front","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","cookie":"connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%7D.7AR2orsC%2FobU8JrwHnMo3vFwUIjBmasc%2Bz%2BTK1xeq%2F4"}

body: {"username":"phlux","email":"phlux@ewnix.net","password":"REDACTED","confirmPassword":"REDACTED"}
[domain-middleware] POST /api/v2/register?lang=en throw error 2 times
{ [Error: Can't set headers after they are sent.]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [ [Object], [Object] ],
     _throwErrorCount: 2 },
  domainThrown: true }
[0mPOST /api/v2/register?lang=en [31m5739101 [0m66.251 ms - 219[0m
[31merror[39m: RangeError: Invalid status code: 5739101
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/habitrpg/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/habitrpg/node_modules/express/node_modules/connect/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.res.write (/habitrpg/node_modules/express/node_modules/connect/node_modules/compression/index.js:91:14)
    at ServerResponse.res.end (/habitrpg/node_modules/express/node_modules/connect/node_modules/compression/index.js:112:14)
    at ServerResponse.res.send (/habitrpg/node_modules/express/lib/response.js:176:8)
    at ServerResponse.res.json (/habitrpg/node_modules/express/lib/response.js:224:15)
    at auth.js:139:36
    at Promise.taskCallback (/habitrpg/node_modules/async/lib/async.js:468:21)
    at Promise.<anonymous> (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:172:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.reject (/habitrpg/node_modules/mongoose/node_modules/mpromise/lib/promise.js:111:15)
    at Promise.error (/habitrpg/node_modules/mongoose/lib/promise.js:95:15)
    at Immediate.cb (/habitrpg/node_modules/mongoose/lib/query.js:1152:29)
    at Immediate._onImmediate (/habitrpg/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 ----------------------------


originalUrl: /api/v2/register?lang=en

auth: undefined | undefined

headers: {"host":"137.184.240.135:3000","connection":"keep-alive","content-length":"105","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","x-client":"habitica-web","origin":"http://137.184.240.135:3000","referer":"http://137.184.240.135:3000/static/front","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","cookie":"connect.sess=s%3Aj%3A%7B%22passport%22%3A%7B%7D%7D.7AR2orsC%2FobU8JrwHnMo3vFwUIjBmasc%2Bz%2BTK1xeq%2F4"}

body: {"username":"phlux","email":"phlux@ewnix.net","password":"REDACTED","confirmPassword":"REDACTED"}
[0mPOST /api/v2/register?lang=en [31m500 [0m8.172 ms - 219[0m
[domain-middleware] POST /api/v2/register?lang=en throw error 2 times
{ [Error: Can't set headers after they are sent.]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [ [Object], [Object] ],
     _throwErrorCount: 2 },
  domainThrown: true }
[Sat Nov 09 2024 02:50:53 GMT+0000 (UTC)] [worker:46] kill timeout, exit now.
[02:50:54] [nodemon] app crashed - waiting for file changes before starting...

```

**Comment by SabreCat** [comment]
Production Habitica runs on Kubernetes. What's going on with `/api/v2`? We haven't used v2 API for ages...
