### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1708]
Getting this on the server. Going to add a workaround until I can locate

```
TypeError: Cannot read property 'type' of undefined
    at Object.obj.score (/app/node_modules/habitrpg-shared/script/algos.coffee:240:18)
    at Object.api.scoreTask (/app/src/controllers/user.js:136:21)
    at performAction (/app/src/controllers/user.js:578:13)
    at /app/src/controllers/user.js:621:9
    at /app/node_modules/async/lib/async.js:548:21
    at /app/node_modules/async/lib/async.js:224:13
    at iterate (/app/node_modules/async/lib/async.js:131:13)
    at /app/node_modules/async/lib/async.js:142:25
    at /app/node_modules/async/lib/async.js:226:17
    at /app/node_modules/async/lib/async.js:553:34
    at ServerResponse.res.send.res.json (/app/src/controllers/user.js:574:14)
    at Promise.<anonymous> (/app/src/controllers/user.js:229:16)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.EventEmitter.emit (events.js:98:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
    at handleSave (/app/node_modules/mongoose/lib/model.js:130:13)
    at /app/node_modules/mongoose/lib/utils.js:414:16
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:497:9
    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```

**Comment by lefnire** [comment]
fixed
