### ISSUE TITLE
500 after when editign task via PUT /api/v1/user/task/:tid

### ISSUE THREAD

**Issue by MagicMicky** [HabitRPG/habitica#1726]
Hi there.
I'm trying to edit a task via the /PUT api. Unfortunately, I'm getting a 500 server error.
I don't really know why and where that could come from, knowing that I remember it working a few months ago.
My app is working in Java but here is what I do:
set the URL to `/api/v1/user/task/mytaskid`
set the content type of my request to `application/json`
put my user and api key
set `Accept-Encoding` to `gzip` (tried with and without it).
and finally, I set the body of my request to:
`{"id":"mytaskid","type":"habit","text":"taskedited","value":3.059998296218489,"up":true,"down":true}`

And the result is simply a `500 - internal error` from HabitRPG's server.

Do you have an idea of what could cause this error ?

**Comment by lefnire** [comment]
Will look into this soon as I can, but because we actually don't use this route (we use the batch-api stuff so we can support offline mode) we may need your help jumping in. It's a very strange issue, I think I'm getting some crazy Mongoose edge-case: https://www.evernote.com/shard/s17/sh/112347b2-27f9-48b8-b7be-b4115624152b/408556a7fff3df0dd65420fab3f65819

**Comment by MagicMicky** [comment]
Ok, feel free to ask for my help anytime!

**Comment by jbfp** [comment]
I get the same error when trying to edit (or "complete" a daily), so I'm available as well.

**Comment by lefnire** [comment]
This is the error. Will diagnose when I can, just dumping here for later ref

```
2013-11-05T18:24:04.263364+00:00 app[web.3]: TypeError: Object #<Object> has no method 'save'
2013-11-05T18:24:04.267246+00:00 app[web.3]:     at /app/node_modules/mongoose/lib/document.js:1256:13
2013-11-05T18:24:04.268020+00:00 app[web.3]:     at Array.forEach (native)
2013-11-05T18:24:04.270543+00:00 app[web.3]:     at model.pre.err.stack (/app/node_modules/mongoose/lib/document.js:1238:12)
2013-11-05T18:24:04.270543+00:00 app[web.3]:     at model._next (/app/node_modules/mongoose/node_modules/hooks/hooks.js:50:30)
2013-11-05T18:24:04.271125+00:00 app[web.3]:     at model.proto.(anonymous function) [as save] (/app/node_modules/mongoose/node_modules/hooks/hooks.js:96:20)
2013-11-05T18:24:04.272375+00:00 app[web.3]:     at api.updateTask (/app/src/controllers/user.js:170:8)
2013-11-05T18:24:04.274513+00:00 app[web.3]:     at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
2013-11-05T18:24:04.274765+00:00 app[web.3]:     at api.verifyTaskExists (/app/src/controllers/user.js:64:10)
2013-11-05T18:24:04.274765+00:00 app[web.3]:     at Promise.callbacks (/app/node_modules/express/lib/router/index.js:164:37)
2013-11-05T18:24:04.275542+00:00 app[web.3]:     at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
2013-11-05T18:24:04.275542+00:00 app[web.3]:     at Promise.EventEmitter.emit (events.js:98:17)
2013-11-05T18:24:04.275542+00:00 app[web.3]:     at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
2013-11-05T18:24:04.278560+00:00 app[web.3]:     at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
2013-11-05T18:24:04.278781+00:00 app[web.3]:     at handleSave (/app/node_modules/mongoose/lib/model.js:130:13)
2013-11-05T18:24:04.278781+00:00 app[web.3]:     at /app/node_modules/mongoose/lib/utils.js:414:16
2013-11-05T18:24:04.279208+00:00 app[web.3]:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:497:9
2013-11-05T18:24:04.279208+00:00 app[web.3]:     at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
2013-11-05T18:24:04.279444+00:00 app[web.3]:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
2013-11-05T18:24:04.279962+00:00 app[web.3]:     at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
2013-11-05T18:24:04.280213+00:00 app[web.3]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
2013-11-05T18:24:04.280670+00:00 app[web.3]:     at EventEmitter.emit (events.js:95:17)
2013-11-05T18:24:04.280670+00:00 app[web.3]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
2013-11-05T18:24:04.280823+00:00 app[web.3]:     at EventEmitter.emit (events.js:98:17)
2013-11-05T18:24:04.280823+00:00 app[web.3]:     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)
2013-11-05T18:24:04.281147+00:00 app[web.3]:     at Socket.EventEmitter.emit (events.js:95:17)
2013-11-05T18:24:04.281147+00:00 app[web.3]:     at Socket.<anonymous> (_stream_readable.js:746:14)
2013-11-05T18:24:04.281147+00:00 app[web.3]:     at Socket.EventEmitter.emit (events.js:92:17)
2013-11-05T18:24:04.281147+00:00 app[web.3]:     at emitReadable_ (_stream_readable.js:408:10)
2013-11-05T18:24:04.281296+00:00 app[web.3]:     at emitReadable (_stream_readable.js:404:5)
2013-11-05T18:24:04.281643+00:00 app[web.3]:     at readableAddChunk (_stream_readable.js:165:9)
2013-11-05T18:24:04.281643+00:00 app[web.3]:     at Socket.Readable.push (_stream_readable.js:127:10)
2013-11-05T18:24:04.281643+00:00 app[web.3]:     at TCP.onread (net.js:526:21
```

**Comment by lefnire** [comment]
fixed

**Comment by lefnire** [comment]
@MagicMicky do you use `PUT /api/v1/user/tasks` (plural)? I think I want to remove that route

**Comment by MagicMicky** [comment]
Thanks a lot for this fix!

@lefnire No, I don't think I use PUT /api/v1/user/tasks. Isn't this the route to do batch updates?

**Comment by lefnire** [comment]
cool beans, thanks @MagicMicky
