### ISSUE TITLE
CastError: Cast to number failed for value "04:00" at path "preferences.dayStart"

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1913]
Thought we had sufficient sanitization in place... is it only client-side?

``` shell
No listeners detected, throwing. Consider adding an error listener to your connection.
CastError: Cast to number failed for value "04:00" at path "preferences.dayStart"
    at SchemaNumber.cast (/app/node_modules/mongoose/lib/schema/number.js:172:9)
    at /app/node_modules/mongoose/lib/document.js:289:29
    at model.Document.$__try (/app/node_modules/mongoose/lib/document.js:758:8)
    at init (/app/node_modules/mongoose/lib/document.js:288:16)
    at init (/app/node_modules/mongoose/lib/document.js:282:7)
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:247:3)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1831:10)
    at /app/node_modules/mongoose/lib/query.js:1799:11
    at /app/node_modules/mongoose/lib/utils.js:414:16
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:953:5
    at Cursor.nextObject (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:678:5)
    at commandHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:658:14)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1670:9
    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:301:18)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```

**Comment by paglias** [comment]
#1532, I don't think we ever added sanitization server-side for that

**Comment by lefnire** [comment]
I'm losing my memory @paglias :(
