### ISSUE TITLE
Tasks duplication

### ISSUE THREAD

**Issue by l-j-krupa** [HabitRPG/habitica#2216]
Tasks are duplicated, all at once. User: mada. Cannot tell which action caused this error. Chrome/Iron v27.

Here are logs but not sure if relevant (I made some others actions after tasks were duplicated):

Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"], Duplicate key: object:1GM
http://errors.angularjs.org/1.2.7-build.2036+sha.e415e91/ngRepeat/dupes?p0=task%20in%20obj%5Blist.type%2B%22s%22%5D&p1=object%3A1GM
    at https://habitrpg.com/app-5f778c39.js:4:7162
    at C (https://habitrpg.com/app-5f778c39.js:7:13506)
    at Object.m [as fn](https://habitrpg.com/app-5f778c39.js:6:16743)
    at h.$digest (https://habitrpg.com/app-5f778c39.js:6:17205)
    at h.$apply (https://habitrpg.com/app-5f778c39.js:6:18619)
    at https://habitrpg.com/app-5f778c39.js:4:14797
    at Object.h [as invoke](https://habitrpg.com/app-5f778c39.js:4:30266)
    at e (https://habitrpg.com/app-5f778c39.js:4:14705)
    at tb (https://habitrpg.com/app-5f778c39.js:4:14919)
    at sb (https://habitrpg.com/app-5f778c39.js:4:14427) app-5f778c39.js:5
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1388599011955
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1388599011956
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1388599011957
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by paglias** [comment]
Please leave a comment if it happens again
