### ISSUE TITLE
FacebookAuthorizationError: Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2302]
```
FacebookAuthorizationError: Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.
    at Strategy.authenticate (/app/node_modules/passport-facebook/lib/strategy.js:81:23)
    at attempt (/app/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
    at Passport.authenticate (/app/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
    at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
    at param (/app/node_modules/express/lib/router/index.js:138:11)
    at pass (/app/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/app/node_modules/express/lib/router/index.js:33:10)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at pass (/app/node_modules/express/lib/router/index.js:110:24)
    at Router._dispatch (/app/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/app/node_modules/express/lib/router/index.js:33:10)
    at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at resume (/app/node_modules/express/node_modules/connect/lib/middleware/static.js:65:7)
    at SendStream.error (/app/node_modules/express/node_modules/connect/lib/middleware/static.js:80:37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (/app/node_modules/express/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/app/node_modules/express/node_modules/send/lib/send.js:248:48)
    at /app/node_modules/express/node_modules/send/lib/send.js:320:26
    at Object.oncomplete (fs.js:107:15)
 ----------------------------


originalUrl: /auth/facebook/callback?error_code=2&error_message=Sorry%2C%20this%20feature%20isn't%20available%20right%20now%3A%20An%20error%20occurred%20while%20processing%20this%20request.%20Please%20try%20again%20later.

auth: undefined | undefined

headers: ---

body: {}
```

**Comment by Alys** [comment]
Old. Closing in the hope that it's magically fixed itself.
