### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined on api.wizard.fireball.cast

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2640]
```
TypeError: Cannot read property 'value' of undefined
    at api.spells.wizard.fireball.cast (/app/node_modules/habitrpg-shared/script/content.coffee:1049:17)
    at Object.spell.cast (/app/node_modules/habitrpg-shared/script/content.coffee:1317:9)
    at api.cast (/app/src/controllers/user.js:386:13)
    at /app/node_modules/swagger-node-express/Common/node/swagger.js:392:11
    at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
    at api.cron (/app/src/controllers/user.js:205:24)
    at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
    at Promise.<anonymous> (/app/src/controllers/auth.js:33:12)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /app/node_modules/mongoose/lib/query.js:1386:13
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:250:11)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1384:10)
    at Object.cb (/app/node_modules/mongoose/lib/query.js:1143:11)
    at Object._onImmediate (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:126:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
 ----------------------------


originalUrl: /api/v2/user/class/cast/fireball?targetType=task&targetId=b5140337-5cab-49b9-a1f0-8ee82cf2741e
```

**Comment by colegleason** [comment]
So `value` is a property on the task. I have no idea how people are casting on an undefined task.

**Comment by lefnire** [comment]
hmm.... indeed, that's probably what's up. Gotta hunt down where undefined tasks are being made a possibility, I've definitely seen them crop up periodically

**Comment by negue** [comment]
This can be closed due to the workaround?

**Comment by colegleason** [comment]
If this is closed I would add an issue to fix the workaround.
