### ISSUE TITLE
TypeError: Cannot read property 'date' of null

### ISSUE THREAD

**Issue by colegleason** [HabitRPG/habitica#2648]
```
TypeError: Cannot read property 'date' of null
    at /app/src/controllers/dataexport.js:26:55
    at Function.forEach (/app/node_modules/lodash/dist/lodash.js:3039:15)
    at /app/src/controllers/dataexport.js:24:7
    at forOwn (/app/node_modules/lodash/dist/lodash.js:1907:15)
    at Function.forEach (/app/node_modules/lodash/dist/lodash.js:3044:9)
    at dataexport.history (/app/src/controllers/dataexport.js:23:5)
    at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
    at Promise.<anonymous> (/app/src/controllers/auth.js:45:5)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /app/node_modules/mongoose/lib/query.js:1386:13
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:250:11)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1384:10)
    at Object.cb (/app/node_modules/mongoose/lib/query.js:1143:11)
    at Object._onImmediate (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:126:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
 ----------------------------
originalUrl: /export/history.csv

auth: undefined | undefined
```

It seems `task.history` somehow gets a `null` in it. Not sure how that is the case yet. I wonder it it is because of auth being undefined.

**Comment by Alys** [comment]
This is an old report and I can't replicate it so I'm closing this.
