### ISSUE TITLE
Replica Set connection issues

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2725]
We've moved from MongoHQ to MongoLab so we can use Replica Sets for high availability/throughput. (HQ has RS too, but much more expensive). Since the move, I periodically get two connection errors when deploying / restarting the server:

``` shell
2014-02-03T19:05:36.170700+00:00 app[web.2]: /app/src/server.js:42
2014-02-03T19:05:36.170995+00:00 app[web.2]:       if (err) throw err;
2014-02-03T19:05:36.170995+00:00 app[web.2]:                      ^
2014-02-03T19:05:36.170995+00:00 app[web.2]: Error: No valid replicaset instance servers found
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:446:45
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:516:7)
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at EventEmitter.emit (events.js:95:17)
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:168:15)
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at EventEmitter.emit (events.js:98:17)
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:497:10)
2014-02-03T19:05:36.170995+00:00 app[web.2]:     at Socket.EventEmitter.emit (events.js:92:17)
2014-02-03T19:05:36.171238+00:00 app[web.2]:     at Socket._onTimeout (net.js:327:8)
2014-02-03T19:05:36.171238+00:00 app[web.2]:     at Timer.unrefTimeout [as ontimeout] (timers.js:412:13)
```

``` shell
2014-02-03T19:02:44.992752+00:00 app[web.2]: /app/src/server.js:42
2014-02-03T19:02:44.993293+00:00 app[web.2]:       if (err) throw err;
2014-02-03T19:02:44.995060+00:00 app[web.2]:                      ^
2014-02-03T19:02:44.995513+00:00 app[web.2]: Error: No primary found in set
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:449:45
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:516:7)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at EventEmitter.emit (events.js:95:17)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:168:15)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at EventEmitter.emit (events.js:98:17)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:497:10)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at Socket.EventEmitter.emit (events.js:92:17)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at Socket._onTimeout (net.js:327:8)
2014-02-03T19:02:44.995513+00:00 app[web.2]:     at Timer.unrefTimeout [as ontimeout] (timers.js:412:13)
2014-02-03T19:02:47.177374+00:00 app[web.2]: http.Client will be removed soon. Do not use it.
```

At first glance, this leads me to think we're not connecting to RS correctly. However: 
1. we're following the Mongoose connection string specification under [ReplicaSet Connections](http://mongoosejs.com/docs/connections.html) `mongodb://<dbuser>:<dbpassword>@xxx.mongolab.com:nnn,yyy.mongolab.com:nnn/<dbname>` ([code](https://github.com/HabitRPG/habitrpg/blob/e3b5a3978ab1eeeec1b73132ab9a220e9d1eee65/src/server.js#L41))
2. The [database ops avg time](https://rpm.newrelic.com/accounts/565514/applications/3386694/transactions#id=547252277) (ms) has decreased significantly since the move, leading me to believe RS is being used properly
3. A `heroku restart` will typically fix the issue

**Comment by lefnire** [comment]
Response from support:

---

**MongoLab**: 

Sounds like you're using Node? One of the odd things about the Node driver is that the default timeout for replica set connections is only 1 second, so make sure you're setting it to something more like 30s like in this example:

```
{ 
   options: { 
      replset: { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 } }, 
      server: { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 } } 
   } 
}
```

If your connection was fine on a single server and you're only seeing problems after switching to a replica set, then this is probably the reason. Give these settings a try and let us know how it goes.

---

**MongoLab**:

Looking at your number of connections, I noticed that you may not be using connection pooling. The Node driver has some "gotchas" so I wanted to bring it to your attention just in case: http://blog.mongolab.com/2013/11/deep-dive-into-connection-pooling/

---

**Tyler**:
Thanks for the follow-up! The article mentions two things: keep your db connection outside request handlers for a persistent connection singleton (which we're doing, √); (2) possibly increasing connection pool size - is it this #2 you're suggesting? I'll give it a shot if so, we're definitely experiencing some mongo race conditions causing this bug: https://github.com/HabitRPG/habitrpg/issues/2301 (the reason we moved to ReplicaSets), and if connection pools might increase throughput I'll try it out. As for _this_ ticket, I have a hunch Robert's is the solution, seems it's the initial connection that's hitting snags

---

**MongoLab**:

First, I believe you're right. For this ticket, Robert's suggestion should be the solution (we've seen it with many users). My follow-up was on a somewhat unrelated note- sorry for the confusion.

Second, the pool size shouldn't impact your race conditions. I think the default of 5 should be fine, I was more curious about the number of connections you have open at a given time. If you're not initializing new connections with each request there should be no concerns here. Just double-checking connection best practices :).

As for the race condition, here's a thread on SO that I was reading up on: http://stackoverflow.com/questions/17499089/versionerror-no-matching-document-found-error-on-node-js-mongoose. I'll loop in a colleague to see if we have any suggestions on this front.

---

**Tyler**
Thanks again Chris for pointing that out, I wouldn't have noticed it - we definitely have ~160 concurrent connections, that seems _very_ high. I'm currently poking around here http://goo.gl/D3VFkW , could be lack of Mongoose connection-closing, could indeed by unintended per-request new connections (as per your initial hunch). Anyway, thanks again for the heads up - y'all have fantastic support!

---

**MongoLab**

For what it's worth, I've found that it's pretty rare for applications to need to close connections (unless you're running worker processes). Typically you initialize the connection when the app starts up and re-use the singleton for the lifetime of the app; the driver should grab connections from the pool as necessary (I am admittedly more familiar with the node native driver).

I would suggest writing a small test app and spinning up a local MongoDB/creating a new database on your cluster for testing. You can then stream the logs and watch how the driver connections behave when you make requests and/or terminate the app.

**Comment by lefnire** [comment]
fixed with the `connectTimeoutMS` suggestion.
