### ISSUE TITLE
TypeError: Cannot read property 'collect' of undefined

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2853]
``` shell
TypeError: Cannot read property 'collect' of undefined
    at Promise.<anonymous> (/app/src/models/group.js:187:20)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /app/node_modules/mongoose/lib/query.js:1394:13
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:250:11)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1392:10)
    at Object.cb (/app/node_modules/mongoose/lib/query.js:1151:11)
    at Object.<anonymous> (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:125:16)
    at Object._onImmediate (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
 ----------------------------


originalUrl: /api/v2/user/batch-update?_v=16673&data=1392483799705&siteVersion=1

auth: ...

headers: ...

body: [{}]
```
##

**Comment by lefnire** [comment]
Seems to be an issue of the first day a quest begins, some users aren't getting their `party.quest.progress` initialized properly. Intermittent, could be a worker crashed right when that init step was taking place. Will look into soon
