### ISSUE TITLE
NPM install does not include app.json in habitrpg-shared module

### ISSUE THREAD

**Issue by davidhtien** [HabitRPG/habitica#2857]
Not sure if this is the right place to post this but when I try to set up habitrpg locally and do grunt run:dev it errors out because app.json is missing in habitrpg-shared/locales/en/. When I check the repo I forked and cloned onto my computer the file is there... Why is this happening?

module.js:340
    throw err;
    ^
Error: Cannot find module '/home/david/Documents/habitrpg/node_modules/habitrpg-shared/locales/en/app.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadTranslations (/home/david/Documents/habitrpg/src/middleware.js:97:15)
    at Object.<anonymous> (/home/david/Documents/habitrpg/src/middleware.js:105:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (/home/david/Documents/habitrpg/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/david/Documents/habitrpg/src/server.js:26:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
15 Feb 23:36:01 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by paglias** [comment]
@davidhtien `app.json` was a file in the habitrpg-shared package that was required some time ago but has been deleted since then. Try to get an updated version of habitrpg, updating your fork.

**Comment by davidhtien** [comment]
Oh ok thanks for the quick reply!
