### ISSUE TITLE
SyntaxError: Unexpected token #

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3122]
``` shell
SyntaxError: Unexpected token #
at Object.parse (native)
at /app/node_modules/express/node_modules/connect/lib/middleware/json.js:75:25
at IncomingMessage.onEnd (/app/node_modules/express/node_modules/connect/node_modules/raw-body/index.js:109:7)
at IncomingMessage.g (events.js:180:16)
at IncomingMessage.<anonymous> (/app/node_modules/newrelic/node_modules/continuation-local-storage/context.js:62:17)
at IncomingMessage.EventEmitter.emit (events.js:92:17)
at IncomingMessage.emitted [as emit] (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
at _stream_readable.js:920:16
at /app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31
at process._tickDomainCallback (node.js:459:13)
at process.<anonymous> (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```
##

**Comment by larouxn** [comment]
Is this an error that occurred when trying to setup your local dev environment?

**Comment by paglias** [comment]
@larouxn no it's an error occurred in production

**Comment by lefnire** [comment]
This is an error we're getting with people using the API (likely experimenting with it while building their 3rd party apps). IIRC this is the error you get when you don't send up proper JSON. Eg, 

Bad:

``` javascript
{keys:"must be quoted"}
```

Good:

``` javascript
{"keys":"must be quoted"}
```

(and other things like you can't use single quotes, must use double, etc etc). @larouxn why, are you experiencing this while setting up local env?

**Comment by larouxn** [comment]
No, I was just wondering what was causing it so we could sort out the issue.

Thanks for the explanation!

**Comment by negue** [comment]
So this can be closed?

**Comment by lefnire** [comment]
nay, I still see it often

**Comment by negue** [comment]
Okay, but what can / should we do to fix it?

I mean isn't this a 3rd party developers fault?

**Comment by lefnire** [comment]
Well, we just need some better validation / sanitization in our express middleware. It's super low prio, because it doesn't crash anything (just throws the error) - but wanna keep here for posterity

**Comment by Alys** [comment]
I'm closing this because we've made some improvements to the code and are part way through a project to make more, so eventually everything that causes this will be fixed. When we get new reports of it, we'll deal with them as they come in.
