### ISSUE TITLE
Can't start quest - no popup

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3221]
On wiki we read:
1.Click on the quest scroll in your inventory.
2. Select the "Invite party" button in the pop-up.

But I don't have any popup when I'm clicking.
I'm using latest Chrome.

**Comment by deilann** [comment]
Refresh

If  that doesn't work, can you open the chrome console (ctrl+shift+j), try again, and tell me if you're seeing any errors?

**Comment by ghost** [comment]
TypeError: Cannot read property 'previous' of undefined
    at i.b.showQuest (https://habitrpg.com/app-845aa4d8.js:23:17884)
    at https://habitrpg.com/app-845aa4d8.js:6:8701
    at https://habitrpg.com/app-845aa4d8.js:7:12167
    at i.$eval (https://habitrpg.com/app-845aa4d8.js:6:19377)
    at i.$apply (https://habitrpg.com/app-845aa4d8.js:6:19664)
    at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-845aa4d8.js:7:12149)
    at HTMLButtonElement.n.event.dispatch (https://habitrpg.com/app-845aa4d8.js:2:6309)
    at HTMLButtonElement.r.handle (https://habitrpg.com/app-845aa4d8.js:2:3084) 

but uff, refresh helped.

**Comment by deilann** [comment]
Yeah, I'm thinking that your cache had missing stuff, so refreshing updated
the cache with the correct code.
