### ISSUE TITLE
Express version

### ISSUE THREAD

**Issue by dekz** [HabitRPG/habitica#3252]
Just following the instruction in the README to get a development environment setup. Looks like my workers are dying because before even being able to start 

```
info: [Fri Apr 11 2014 14:15:27 GMT+1000 (EST)] [master:46022] worker:46030 disconnect! new worker:46033 fork

Error: Most middleware (like logger) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/Users/jacob/projects/habitrpg/habitrpg/node_modules/express/lib/express.js:89:13)
    at Object.<anonymous> (/Users/jacob/projects/habitrpg/habitrpg/src/server.js:96:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

`package.json` seems to state the code should work with absolutely all versions of express `*`. If this is the actual cause of the problem, can the version be pinned to a known working version and tested with new versions as they come out.

Pinning it to `3.5.0` works fine.

**Comment by thepeopleseason** [comment]
This is causing travis builds to fail, too. I think express may have upgraded on npmjs.

**Comment by denis-sokolov** [comment]
In 5ff0b950 version has been pinned to 3.5, so this can be closed.

In #3269 a fix for express 4 has been proposed, feel free to test.

**Comment by deilann** [comment]
I like pressing buttons.
