### ISSUE TITLE
Jade Compile issues

### ISSUE THREAD

**Issue by iKarthik** [HabitRPG/habitica#3458]
Hello,

I forked the source, followed the readme.md steps. I was able to do grunt run:dev, get the server up an running but I when I access localhost:3000, i get a error which reads

error: TypeError: B:\dev\nodeapps\habitrpg-develop\views\static\login-modal.jade:4
    2|   .modal-header
    3|     button.close(type='button', ng-click='$close()') x

> 4|     h4.modal-title=env.t('loginAndReg')
>     5|   .modal-body(ng-controller='AuthCtrl')
>     6|     a(href='/auth/facebook')
>     7|       img(src='/bower_components/habitrpg-shared/img/facebook-login-register.jpeg', alt=env.t('loginFacebookAlt')
> )

Cannot read property 't' of undefined
    at Object.res.locals.habitrpg.t (B:\dev\nodeapps\habitrpg-develop\src\middleware.js:166:25)
    at eval (eval at <anonymous> (B:\dev\nodeapps\habitrpg-develop\node_modules\jade\lib\jade.js:152:8), <anonymous>:88:
81)

Can anyone explain to me what this is how I could resolve them.
PS: (Am a newbie to all these technologies, so please bear with my ignorance

Thanks
Kay

**Comment by iKarthik** [comment]
It looks like I had commented out the line 

shared.i18n.translations = translations; in i18n.js, 

which might be the reason for the above error. When I un-commented the above line and I did my  grunt run:dev am getting

 shared.i18n.translations = translations;
                                              ^
 ^
TypeError: Cannot set property 'translations' of undefined
    at Object.<anonymous> (B:\dev\nodeapps\habitrpg-develop\src\i18n.js:89:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (B:\dev\nodeapps\habitrpg-develop\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:3
6)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (B:\dev\nodeapps\habitrpg-develop\src\server.js:31:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Any help would be greatly appreciated

Thanks
Kay

**Comment by paglias** [comment]
Have you installed dependencies with npm installa?
Il 13/mag/2014 17:52 "iKarthik" notifications@github.com ha scritto:

**Comment by iKarthik** [comment]
Yes I have. I think I did every single step that was given in the readme file.

Thanks
Kay

**Comment by paglias** [comment]
Strange... make sure the repo is up to date `git fetch && git pull origin develop`

**Comment by lefnire** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/commit/d5409172e3beeb281cab905bc9839cedbffacfc1
