### ISSUE TITLE
Error Running Locally (when logged in as a user)

### ISSUE THREAD

**Issue by caycefischer** [HabitRPG/habitica#356]
When running the app locally, loading the page in the browser hangs indefinitely when  logged into a user account. Seems to only happen when logged in to a user that has the **parties** feature enabled, when I clear cookies the page loads fine, then starts hanging again after logging in.

This didn't happen a few days ago, when I was able to log into and out of multiple accounts just fine. **Maybe I should just nuke my database, re-clone the repo and start over?**

Here is the output from the terminal window running the node thing when I try to refresh the page, if it helps:

``` bash
9 Feb 10:49:28 - [nodemon] v0.7.1
9 Feb 10:49:28 - [nodemon] watching: /Users/zakkain/Sites/habitrpg
9 Feb 10:49:28 - [nodemon] starting `node server.js`
   info  - socket.io started
Expressions in require() statements:
    require('./lang/' + key)
Error: You have not declared any query motifs for the namespace "parties". You must do so via store.query.expose before you can query a namespaced collection of documents
    at Object.QueryMotifRegistry.queryTupleBuilder (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/query/QueryMotifRegistry.js:179:13)
    at Model.query (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/query/query.Model.js:324:56)
    at module.exports.partySubscribe.partySubscribe (/Users/zakkain/Sites/habitrpg/src/app/party.coffee:37:24)
    at module.exports.proto.subscribe (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/descriptor.Model.js:91:12)
    at Object.module.exports.server._addSub._clientIdPromise.on.res.send (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/descriptor.Model.js:210:13)
    at Object.module.exports.events.middleware.middleware.subscribe.add._res.send (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/pubSub/pubSub.Store.js:130:39)
    at Object.module.exports.events.middleware.middleware.fetch.add._res.send (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/descriptor.Store.js:105:27)
    at module.exports.events.middleware.middleware.fetchQuery.add.store._fetchAndCompileQueryData.done (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/query/query.Store.js:72:17)
    at module.exports.proto._fetchAndCompileQueryData (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/query/query.Store.js:168:9)
    at QueryHub.fetch (/Users/zakkain/Sites/habitrpg/node_modules/racer/lib/descriptor/query/QueryHub.js:207:12)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

**Comment by lefnire** [comment]
interesting, it's not picking up the parties query system.  Your'e definitely on HEAD of master? Yeah, try nuking db:

```
mongo habitrpg
>db.dropDatabase()
>exit()
```

then run `rm -rf public/gen && npm install && node server.js`

**Comment by caycefischer** [comment]
Done. It all works great, I leveled up two characters and it was all normal—until I try making a party with UserOne and adding UserTwo's id to it. Then the error happens on UserOne's account. UserTwo is fine.

**Comment by lefnire** [comment]
woop, i missed a step: `rm -rf node_modules && npm install && node server.js` - maybe due to updates in Racer

**Comment by caycefischer** [comment]
That did it! Awesome, it all works great. Thanks dude

**Comment by lefnire** [comment]
ah yes. racer updates indeed then. cool man, thanks for jumping into this!
