### ISSUE TITLE
MongoError: Connection Closed By Application &

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3607]
In the last few weeks I've been seeing the following two errors very frequently:

``` shell
MongoError: Connection Closed By Application
    at Object.toError (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at ReplSet.close (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:268:36)
    at Db.close (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:358:21)
    at NativeConnection.doClose (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:230:11)
    at NativeConnection.Connection.close (/app/node_modules/mongoose/lib/connection.js:483:12)
    at Object.domainMiddleware.server.close (/app/src/middleware.js:36:29)
    at Domain.<anonymous> (/app/node_modules/domain-middleware/lib/domain.js:67:26)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:249:27)
    at process._asyncFatalException [as _fatalException] (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:199:34)
```

``` shell
No listeners detected, throwing. Consider adding an error listener to your connection.
RangeError: Maximum call stack size exceeded
    at Array.MongooseArray (/app/node_modules/mongoose/lib/types/array.js:29:12)
    at SchemaArray.cast (/app/node_modules/mongoose/lib/schema/array.js:139:15)
    at /app/node_modules/mongoose/lib/document.js:288:29
    at EmbeddedDocument.Document.$__try (/app/node_modules/mongoose/lib/document.js:757:8)
    at init (/app/node_modules/mongoose/lib/document.js:287:16)
    at EmbeddedDocument.Document.init (/app/node_modules/mongoose/lib/document.js:246:3)
    at DocumentArray.cast (/app/node_modules/mongoose/lib/schema/documentarray.js:135:27)
    at /app/node_modules/mongoose/lib/document.js:288:29
    at model.Document.$__try (/app/node_modules/mongoose/lib/document.js:757:8)
    at init (/app/node_modules/mongoose/lib/document.js:287:16)
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:246:3)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1391:10)
    at Object.cb (/app/node_modules/mongoose/lib/query.js:1150:11)
    at Object.<anonymous> (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at Object._onImmediate (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by lefnire** [comment]
https://github.com/LearnBoost/mongoose/issues/1920, https://github.com/LearnBoost/mongoose/issues/1993
