### ISSUE TITLE
local build doesn't run JS on front page

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4288]
I built a local copy of HabitRPG on my system and worked through the typical known issues. However, when I visit the page, I get redirected to `/static/front` with the JS frontend elements seemingly missing. The navigation bar has no stylesheet, and the Play button doesn't respond. Console shows no errors on click event. MongoDB is running, and `habitrpg` is in the list of databases.

![habitrpg](https://cloud.githubusercontent.com/assets/5308179/5214556/f81ef620-75c1-11e4-8744-5e2bee526fdb.png)
### Environment
- OS: Ubuntu 14.04 LTS amd64, current updates
- Browsers: Firefox 33 (noscript whitelisting localhost, etc.) and Chromium 39 (unmodified)
- Branch: develop, current as of this post
- Run command: `grunt run:dev`

Last trace on console, `grunt` still running:

`TypeError: Cannot read property 'metrics' of undefined
    at Request._callback (/home/user/projects/habitrpg/src/middleware.js:46:46)
    at Request.self.callback (/home/user/projects/habitrpg/node_modules/request/request.js:237:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/user/projects/habitrpg/node_modules/request/request.js:1146:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/user/projects/habitrpg/node_modules/request/request.js:1097:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at /home/user/projects/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at /home/user/projects/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:463:13)
    at process.<anonymous> (/home/user/projects/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)`

**Comment by paglias** [comment]
@talexand do you have NODE_ENV variable set to 'production'? Try running it as `NODE_ENV=development grunt run:dev`

Also make sure to have all the modules installed (`npm install && bower install`)

**Comment by ghost** [comment]
Fixed. It looks like `$NODE_ENV` has to be set _and_ exported. Thanks.
