### ISSUE TITLE
Get "cannot read property 'chat' of undefined" when trying to look at challenges

### ISSUE THREAD

**Issue by stephenphillips42** [HabitRPG/habitica#4293]
I found out about the guilds and started signing up to a lot of them. I realized it might have been too much, so I decided to try and get out of some but I got a memory exceeded error. The specific error is:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 35274629 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details).

I restarted the tab in Chrome, but I still got the same message when I tried again. I get the same error when I try to look at a challenge from a specific guild. I get this error in the console:

TypeError: Cannot read property 'chat' of undefined
    at Object.a.chatChanged [as fn](https://habitrpg.com/app-96463577.js:28:17384)
    at j.$digest (https://habitrpg.com/app-96463577.js:7:12891)
    at j.$apply (https://habitrpg.com/app-96463577.js:7:14434)
    at HTMLAnchorElement.<anonymous> (https://habitrpg.com/app-96463577.js:10:1550)
    at HTMLAnchorElement.n.event.dispatch (https://habitrpg.com/app-96463577.js:2:6404)
    at HTMLAnchorElement.r.handle (https://habitrpg.com/app-96463577.js:2:3179) app-96463577.js:6
GET https://habitrpg.com/api/v2/challenges 500 (Internal Server Error) app-96463577.js:6
Object {data: Object, status: 500, headers: function, config: Object, statusText: "Internal Server Error"} app-96463577.js:27
Error: [$resource:badcfg] query
http://errors.angularjs.org/1.3.3/$resource/badcfg?p0=array&p1=object
    at https://habitrpg.com/app-96463577.js:4:21645
    at g.then.B.$resolved (https://habitrpg.com/app-96463577.js:10:4612)
    at j (https://habitrpg.com/app-96463577.js:7:7176)
    at https://habitrpg.com/app-96463577.js:7:7373
    at j.$eval (https://habitrpg.com/app-96463577.js:7:14169)
    at j.$digest (https://habitrpg.com/app-96463577.js:7:12641)
    at j.$apply (https://habitrpg.com/app-96463577.js:7:14434)
    at t (https://habitrpg.com/app-96463577.js:6:10598)
    at v (https://habitrpg.com/app-96463577.js:6:12145)
    at XMLHttpRequest.w (https://habitrpg.com/app-96463577.js:6:11814) app-96463577.js:6

I cannot find anything quite like this in the other errors, so I hope this is not a duplication.

**Comment by crookedneighbor** [comment]
Closed with https://github.com/HabitRPG/habitrpg/commit/522181890e3ce068b518029f1590a9421fd490bd
