### ISSUE TITLE
Tracking Cron Errors

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#4426]
We're getting a lot of `VersionError: No matching document found.` happening inside [api.cron](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L259) with a stack trace similar to this one:

```
VersionError: No matching document found.
at handleSave (/app/node_modules/mongoose/lib/model.js:126:23)
at /app/node_modules/mongoose/lib/utils.js:408:16
at cb_callbackProxy (/app/node_modules/newrelic/lib/instrumentation/mongodb.js:318:39)
at /app/node_modules/newrelic/node_modules/continuation-local-storage/context.js:74:17
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:577:7
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1131:7
at b (domain.js:183:18)
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1847:9
at b (domain.js:183:18)
at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:478:18
at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:436:20)
at emit (events.js:95:17)
at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
at emit (events.js:98:17)
at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
at Socket.emit (events.js:95:17)
at Socket.<anonymous> (_stream_readable.js:764:14)
at Socket.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:426:10)
at emitReadable (_stream_readable.js:422:5)
at readableAddChunk (_stream_readable.js:165:9)
at Socket.Readable.push (_stream_readable.js:127:10)
at TCP.onread (net.js:528:21)
at TCP.onread (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
```

which isn't exactly helpful. It's happening inside a mongoose's `.save()` function but that could be either a group or the user itself.

I hope [this](https://github.com/HabitRPG/habitrpg/commit/85f4a2884a077943ac87d065f2ee26aa521e851c) commit can help tracking down where it's happening.

A search on Google reveals that it's probably due to some concurrent saving of a model but I don't know where it's happening: https://github.com/LearnBoost/mongoose/issues/1844, http://stackoverflow.com/questions/17499089/versionerror-no-matching-document-found-error-on-node-js-mongoose or a problem with the `_v` attr we pass in the request url.

@lefnire in the meantime I noticed a few things:
- [here](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L295) why do we pass saved to `next`? could it be a source of some memory leak? 
-  [here](https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L279) we pass the old `user` object, not the `saved` one from the previous operation. Might it impact quest calculations? Sincerely I'm not sure the `user` object is much different from the `saved` object but then we can avoid passing it to the callback.
##

**Comment by paglias** [comment]
From the commit https://github.com/HabitRPG/habitrpg/commit/85f4a2884a077943ac87d065f2ee26aa521e851c it seems that error happens both when saving the user or running quest updates

**Comment by Alys** [comment]
I'm closing this since the code has changed a lot since it was logged and will soon change even more with API v3, but feel free to reopen if this is still valuable.
