### ISSUE TITLE
TypeError: Cannot read property 'metrics' of undefined

### ISSUE THREAD

**Issue by tohn** [HabitRPG/habitica#4485]
I'm running HabitRPG on my own server. When I run it in production mode by changing NODE_ENV in the config and running `grunt build:prod && grunt nodemon` after a time I get this:

```
TypeError: Cannot read property 'metrics' of undefined
    at Request._callback (/path/to/habitrpg/src/middleware.js:46:46)
    at Request.self.callback (/path/to/habitrpg/node_modules/request/request.js:237:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/path/to/habitrpg/node_modules/request/request.js:1146:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/path/to/habitrpg/node_modules/request/request.js:1097:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at /path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at /path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:486:13)
    at process.<anonymous> (/path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
New Relic for Node.js halted startup due to an error:
Error: Unknown license key
    at StreamSink.parser [as callback] (/path/to/habitrpg/node_modules/newrelic/lib/collector/parse-response.js:81:25)
    at StreamSink.end (/path/to/habitrpg/node_modules/newrelic/lib/util/stream-sink.js:43:8)
    at IncomingMessage.onend (_stream_readable.js:502:10)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at /path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (node.js:442:13)
```

Apart from SESSION_SECRET, ADMIN_EMAIL and NODE_ENV I didn't change anything else in the config. Is there a way to disable relic since I don't use it? (And maybe also some other stuff in the config?) Removing the NEW_RELIC-stuff from the config will bring up this:

```
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at cb_nextTick (/path/to/habitrpg/node_modules/newrelic/lib/agent.js:148:16)
    at /path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:486:13)
    at process.<anonymous> (/path/to/habitrpg/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

My OS: Arch Linux x86_64 (Kernel: 3.17.2-1-ARCH)

**Comment by paglias** [comment]
@tohn hi, the production mode is meant to run HabitRPG on the server used at habitrpg.com or beta.habitrpg.com not on a local machine because it's set to setup a lot of external services that are not avalaible during development like payments, monitor services and email server. You should run it in development mode, it won't affect the performances much if you're using it on your machine for just a few users
