### ISSUE TITLE
TypeError: Cannot read property 'party' of undefined

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#516]
``` shell
TypeError: Cannot read property 'party' of undefined
    at module.exports.partySubscribe.partySubscribe (/var/www/vhosts/habitrpg/node/src/app/party.coffee:42:24)
    at /var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/descriptor.Model.js:271:8
    at Object.module.exports.server._addSub._clientIdPromise.on.res.send (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/descriptor.Model.js:234:13)
    at Object.module.exports.events.middleware.middleware.subscribe.add._res.send (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/pubSub/pubSub.Store.js:120:39)
    at Object.module.exports.events.middleware.middleware.fetch.add._res.send (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/descriptor.Store.js:105:27)
    at module.exports.events.middleware.middleware.fetchQuery.add.store._fetchAndCompileQueryData.done (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/query/query.Store.js:72:17)
    at module.exports.proto._fetchAndCompileQueryData (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/query/query.Store.js:168:9)
    at QueryHub.fetch (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/query/QueryHub.js:207:12)
    at Array.QueryNode.result [as 0] (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/descriptor/query/QueryNode.js:30:12)
    at Object.Promise.resolve (/var/www/vhosts/habitrpg/node/node_modules/racer/lib/util/Promise.js:21:19)
```

**Comment by lefnire** [comment]
fixed it seems. I think this was caused because we were using `model.fetch` instead of `model.subscribe`. When clients attempted reconnection to a restarted server, the fetched objects weren't re-requested, only the subscriptions - so the required data was fragmented
