### ISSUE TITLE
installation on uberspace fails

### ISSUE THREAD

**Issue by MoritzFago** [HabitRPG/habitica#5633]
hello i tried to install habitrpg on my uberspace, i folowed [this](https://gist.github.com/mamiu/cc792b805eec59b224c9) guide but it fails. here is the log of `npm install`

``` npm
npm http GET https://registry.npmjs.org/babel
npm http GET https://registry.npmjs.org/browserify
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/express-csv
npm http GET https://registry.npmjs.org/git-changelog
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-browserify
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-concurrent
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin
npm http GET https://registry.npmjs.org/coffeeify/0.6.0
npm http GET https://registry.npmjs.org/connect-ratelimit/0.0.7
npm http GET https://registry.npmjs.org/coupon-code
npm http GET https://registry.npmjs.org/domain-middleware
npm http GET https://registry.npmjs.org/grunt-contrib-stylus
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-hashres
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/grunt-nodemon
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/image-size
npm http GET https://registry.npmjs.org/grunt-spritesmith
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/in-app-purchase
npm http GET https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/method-override
npm http GET https://registry.npmjs.org/mixpanel
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/mongoose
npm http GET https://registry.npmjs.org/mongoose-id-autoinc
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/nib
npm http GET https://registry.npmjs.org/newrelic
npm http GET https://registry.npmjs.org/nodemailer
npm http GET https://registry.npmjs.org/pageres
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-facebook/2.0.0
npm http GET https://registry.npmjs.org/paypal-ipn/2.1.0
npm http GET https://registry.npmjs.org/paypal-rest-sdk
npm http GET https://registry.npmjs.org/ps-tree
npm http GET https://registry.npmjs.org/push-notify
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/s3-upload-stream
npm http GET https://registry.npmjs.org/stripe
npm http GET https://registry.npmjs.org/universal-analytics
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston-mail
npm http GET https://registry.npmjs.org/validator
npm http GET https://registry.npmjs.org/winston-newrelic
npm http GET https://registry.npmjs.org/coffee-coverage
npm http GET https://registry.npmjs.org/csv
npm http GET https://registry.npmjs.org/coveralls
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/deep-diff
npm http GET https://registry.npmjs.org/expect.js
npm http GET https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/grunt-contrib-imagemin
npm http GET https://registry.npmjs.org/istanbul
npm http GET https://registry.npmjs.org/karma-chai-plugins
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-coffee-preprocessor
npm http GET https://registry.npmjs.org/karma-coverage
npm http GET https://registry.npmjs.org/karma-html2js-preprocessor
npm http GET https://registry.npmjs.org/karma-firefox-launcher
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/karma-mocha/0.1.3
npm http GET https://registry.npmjs.org/karma-mocha-reporter
npm http GET https://registry.npmjs.org/karma-ng-html2js-preprocessor
npm http GET https://registry.npmjs.org/karma-phantomjs-launcher
npm http GET https://registry.npmjs.org/karma-requirejs
npm http GET https://registry.npmjs.org/lcov-result-merger
npm http GET https://registry.npmjs.org/karma-script-launcher
npm http GET https://registry.npmjs.org/phantomjssmith
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/mongoskin
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/rewire
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/sinon-chai
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/vinyl-source-stream
npm http GET https://registry.npmjs.org/superagent-defaults
npm http GET https://registry.npmjs.org/vinyl-transform
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/aws-sdk
npm http 304 https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/browserify
npm http 304 https://registry.npmjs.org/grunt-cli
npm http 304 https://registry.npmjs.org/grunt-concurrent
npm http 304 https://registry.npmjs.org/grunt-contrib-clean
npm http 304 https://registry.npmjs.org/grunt-contrib-copy
npm http 304 https://registry.npmjs.org/babel
npm http 304 https://registry.npmjs.org/git-changelog
npm http 304 https://registry.npmjs.org/grunt-contrib-cssmin
npm ERR! Error: No compatible version found: babel@'^5.5.4'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","4.0.1","4.0.2","4.1.1","4.2.0","4.2.1","4.3.0","4.4.1","4.4.2","4.4.3","4.4.4","4.4.5","4.4.6","4.5.0","4.5.1","4.5.2","4.5.3","4.5.4","4.5.5","4.6.0","4.6.1","4.6.3","4.6.4","4.6.5","4.6.6","4.7.0","4.7.1","4.7.2","4.7.3","4.7.4","4.7.5","4.7.6","4.7.7","4.7.8","4.7.9","4.7.10","4.7.11","4.7.12","4.7.13","4.7.14","4.7.15","4.7.16","5.0.0-beta2","5.0.0-beta3","5.0.0-beta4","5.0.0","5.0.1","5.0.2","5.0.3","5.0.4","5.0.5","5.0.6","5.0.7","5.0.8","5.0.9","5.0.10","5.0.11","5.0.12","5.0.13","5.1.0","5.1.1","5.1.2","5.1.3","5.1.4","5.1.5","5.1.6","5.1.7","5.1.8","5.1.9","5.1.10","5.1.11","5.1.12","5.1.13","5.2.0","5.2.1","5.2.2","5.2.3","5.2.4","5.2.5","5.2.6","5.2.7","5.2.9","5.2.10","5.2.11","5.2.12","5.2.13","5.2.14","5.2.15","5.2.16","5.2.17","5.3.0","5.3.1","5.3.2","5.3.3","5.4.0","5.4.1","5.4.2","5.4.3","5.4.4","5.4.5","5.4.6","5.4.7","5.5.0","5.5.1","5.5.2","5.5.3","5.5.4","5.5.5","5.5.6","5.5.7","5.5.8","5.6.1","5.6.2","5.6.3","5.6.4","5.6.5","5.6.6","5.6.7","5.6.10","5.6.11","5.6.12","5.6.14","5.6.23"]
npm ERR!     at installTargetsError (/package/host/localhost/nodejs-0.10.3/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /package/host/localhost/nodejs-0.10.3/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/package/host/localhost/nodejs-0.10.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! command "/package/host/localhost/nodejs-0.10.3/bin/node" "/package/host/localhost/nodejs-0.10.3/bin/npm" "install"
npm ERR! cwd /home/[username]/habitrpg
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm http 304 https://registry.npmjs.org/express-csv
npm http 304 https://registry.npmjs.org/connect-ratelimit/0.0.7
npm http 304 https://registry.npmjs.org/grunt-browserify
npm http 304 https://registry.npmjs.org/coupon-code
npm http 304 https://registry.npmjs.org/grunt-contrib-uglify
npm http 304 https://registry.npmjs.org/grunt-contrib-watch
npm http 304 https://registry.npmjs.org/grunt-contrib-stylus
npm http 304 https://registry.npmjs.org/grunt-karma
npm http 304 https://registry.npmjs.org/gulp
npm http 304 https://registry.npmjs.org/grunt-nodemon
npm http 304 https://registry.npmjs.org/grunt-hashres
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/image-size
npm http 304 https://registry.npmjs.org/coffeeify/0.6.0
npm http 304 https://registry.npmjs.org/grunt-spritesmith
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/domain-middleware
npm http 304 https://registry.npmjs.org/method-override
npm http 304 https://registry.npmjs.org/in-app-purchase
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/mongoose
npm http 304 https://registry.npmjs.org/js2xmlparser
npm http 304 https://registry.npmjs.org/loggly
npm http 304 https://registry.npmjs.org/mixpanel
npm http 304 https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/nodemailer
npm http 304 https://registry.npmjs.org/nconf
npm http 304 https://registry.npmjs.org/nib
npm http 304 https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/pageres
npm http 304 https://registry.npmjs.org/paypal-ipn/2.1.0
npm http 304 https://registry.npmjs.org/mongoose-id-autoinc
npm http 304 https://registry.npmjs.org/passport-facebook/2.0.0
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/newrelic
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/s3-upload-stream
npm http 304 https://registry.npmjs.org/stripe
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/paypal-rest-sdk
npm http 304 https://registry.npmjs.org/validator
npm http 304 https://registry.npmjs.org/ps-tree
npm http 304 https://registry.npmjs.org/universal-analytics
npm http 304 https://registry.npmjs.org/winston-newrelic
npm http 304 https://registry.npmjs.org/push-notify
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/coveralls
npm http 304 https://registry.npmjs.org/winston-mail
npm http 304 https://registry.npmjs.org/event-stream
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/csv
npm http 304 https://registry.npmjs.org/istanbul
npm http 304 https://registry.npmjs.org/expect.js
npm http 304 https://registry.npmjs.org/karma
npm http 304 https://registry.npmjs.org/karma-chai-plugins
npm http 304 https://registry.npmjs.org/grunt-contrib-imagemin
npm http 304 https://registry.npmjs.org/karma-chrome-launcher
npm http 304 https://registry.npmjs.org/coffee-coverage
npm http 304 https://registry.npmjs.org/karma-coffee-preprocessor
npm http 304 https://registry.npmjs.org/karma-firefox-launcher
npm http 304 https://registry.npmjs.org/karma-jasmine
npm http 304 https://registry.npmjs.org/karma-mocha-reporter
npm http 304 https://registry.npmjs.org/karma-ng-html2js-preprocessor
npm http 304 https://registry.npmjs.org/karma-phantomjs-launcher
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README.md file found!
npm http 304 https://registry.npmjs.org/karma-requirejs
npm http 304 https://registry.npmjs.org/karma-html2js-preprocessor
npm http 304 https://registry.npmjs.org/karma-coverage
npm http 304 https://registry.npmjs.org/karma-script-launcher
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/phantomjssmith
npm http 304 https://registry.npmjs.org/deep-diff
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mongoskin
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/lcov-result-merger
npm http 304 https://registry.npmjs.org/protractor
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/sinon-chai
npm http 304 https://registry.npmjs.org/vinyl-source-stream
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/karma-mocha/0.1.3
npm http 304 https://registry.npmjs.org/rewire
npm http 304 https://registry.npmjs.org/vinyl-transform
npm http 304 https://registry.npmjs.org/aws-sdk
npm http 304 https://registry.npmjs.org/superagent-defaults
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/[username]/habitrpg/npm-debug.log
npm ERR! not ok code 0
```

and here of `npm start`

```

> habitrpg@0.0.0-152 start /home/[username]/habitrpg
> grunt run:dev

grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
npm ERR! habitrpg@0.0.0-152 start: `grunt run:dev`
npm ERR! `sh "-c" "grunt run:dev"` failed with 99
npm ERR!
npm ERR! Failed at the habitrpg@0.0.0-152 start script.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt run:dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! command "/package/host/localhost/nodejs-0.10.3/bin/node" "/package/host/localhost/nodejs-0.10.3/bin/npm" "start"
npm ERR! cwd /home/[username]/habitrpg
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/[username]/habitrpg/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Alys** [comment]
Hi @MoritzFago. We'll try to help you with this, but please note that the uberspace install process is not officially supported by us (in fact, this is the first mention of it that I recall). It's good that it exists, and we'll add a link to it from our wiki, but because we aren't familiar with it, we might not be able to assist with all problems you encounter.

Also, we have recently made several changes to our own install process (e.g., adjusting how package versions are specified), and so it's possible (but not definite!) that the uberspace process is no longer valid.

It's looking like the installation process was having trouble downloading some of the required packages. When that happens, the best fix is often to start the install process again from scratch. So, try deleting the node_modules directory and all npm temporary files and directories, and then run `npm install` again.

If you get any more errors, report them here again.

**Comment by Alys** [comment]
I'm closing this but let us know if you still need assistance!
