### ISSUE TITLE
Unable to filter challenges

### ISSUE THREAD

**Issue by WezCorp** [HabitRPG/habitica#5645]
User: 6aaf4e6d-0395-49fb-bd6b-641a82b73df9

Unable to filter challenges - it doesn't show any of the guilds I'm in, so the filter doesn't work at all, can't clicked owned or participating and have it change.
Currently using an up to date version of chrome - but getting loads of java errors. I've submitted a request for unable to leave guilds, it might be related to this java error but as I said in that request, I don't know java well enough. See below java error.

TypeError: Cannot read property 'habitrpg' of undefined
    at n (https://habitrpg.com/app-d0549504.js:32:20332)
    at b.filterChallenges (https://habitrpg.com/app-d0549504.js:32:19819)
    at Array.filter (native)
    at https://habitrpg.com/app-d0549504.js:7:26882
    at g (https://habitrpg.com/app-d0549504.js:7:2023)
    at Object.f (https://habitrpg.com/app-d0549504.js:7:9077)
    at j.$digest (https://habitrpg.com/app-d0549504.js:7:15836)
    at j.$apply (https://habitrpg.com/app-d0549504.js:7:17528)
    at $$debounceViewValueCommit (https://habitrpg.com/app-d0549504.js:8:19143)
    at $setViewValue (https://habitrpg.com/app-d0549504.js:8:18829)
##

**Comment by crookedneighbor** [comment]
Hmmm... that's a curious error. I wonder if there's something about a guild you're in that's mucking up the filter.

**Comment by Alys** [comment]
Could be related to #5644 (I asked WezCorp to log the issues separately, but he's right that the errors are the same). I'm troubleshooting in that other issue.

**Comment by Alys** [comment]
closed in favour of https://github.com/HabitRPG/habitrpg/issues/5644
