### ISSUE TITLE
Application Error appears when I tick off items, and other functions

### ISSUE THREAD

**Issue by joyfuldarkness** [HabitRPG/habitica#6180]
Here is a screen shot of what I get.  
![habitica](https://cloud.githubusercontent.com/assets/15656435/10946402/1a63ca1c-82f0-11e5-946c-6c8beb006323.png)

I also see this in the log of the console when I use inspect element
app-a203edf3.js:37 gp
https://api.github.com/repos/habitrpg/habitrpg?callback=callback Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
app-a203edf3.js:37 Base Bear Cub really likes the Basic Candy!
app-a203edf3.js:37 info
app-a203edf3.js:37 Cotton Candy Blue Wolf really likes the Sour Blue Candy!
app-a203edf3.js:37 info
app-a203edf3.js:37 Cotton Candy Pink Panda Cub really likes the Sour Pink Candy!
app-a203edf3.js:37 info
app-a203edf3.js:37 Desert Fox really likes the Sand Candy!
app-a203edf3.js:37 info
app-a203edf3.js:37 You have tamed Skeleton Wolf, let's go for a ride!
app-a203edf3.js:37 info
app-a203edf3.js:6 Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
    at https://habitica.com/app-a203edf3.js:4:22855
    at o (https://habitica.com/app-a203edf3.js:7:18157)
    at j.$apply (https://habitica.com/app-a203edf3.js:7:16613)
    at HTMLDivElement.y (https://habitica.com/app-a203edf3.js:20:4991)
    at HTMLDivElement.o.event.special.(anonymous function).handle (https://habitica.com/app-a203edf3.js:2:9681)
    at HTMLDivElement.o.event.dispatch (https://habitica.com/app-a203edf3.js:2:6109)
    at HTMLDivElement.r.handle (https://habitica.com/app-a203edf3.js:2:2884)
    at j.b.choosePet (https://habitica.com/app-a203edf3.js:38:28159)
    at g (https://habitica.com/app-a203edf3.js:7:3746)
    at e (https://habitica.com/app-a203edf3.js:8:11787)
    at j.$eval (https://habitica.com/app-a203edf3.js:7:16402)
    at j.$apply (https://habitica.com/app-a203edf3.js:7:16637)
    at HTMLButtonElement.<anonymous> (https://habitica.com/app-a203edf3.js:8:11848)
    at HTMLButtonElement.o.event.dispatch (https://habitica.com/app-a203edf3.js:2:6109)
    at HTMLButtonElement.r.handle (https://habitica.com/app-a203edf3.js:2:2884)(anonymous function) @ app-a203edf3.js:6
app-a203edf3.js:37 Skeleton Fox really likes the Bare Bones Candy!
app-a203edf3.js:37 info
https://habitica.com/api/v2/user/batch-update?_v=1028&data=1446657785482 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-a203edf3.js:37 danger
app-a203edf3.js:37 Objectconfig: Objectdata: "<!DOCTYPE html>↵    <html>↵    <head>↵      <meta name="viewport" content="width=device-width, initial-scale=1">↵      <style type="text/css">↵        html, body, iframe { margin: 0; padding: 0; height: 100%; }↵        iframe { display: block; width: 100%; border: none; }↵      </style>↵    <title>Application Error</title>↵    </head>↵    <body>↵      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">↵        <p>Application Error</p>↵      </iframe>↵    </body>↵    </html>"headers: (c)status: 503statusText: "Service Unavailable"**proto**: ObjectresponseError @ app-a203edf3.js:37

Browser and Version - Chrome - Version 46.0.2490.80 m
USER ID - 932d9507-c12b-4dc1-bcdf-2d084457cf75

**Comment by Alys** [comment]
Thank you for telling us about this! It indicates a temporary problem on Habitica's server, often associated with high levels of usage. We're investigating the cause of this particular occurrence and you should find it's already stopped. If not, it will stop soon. I'm very sorry about the inconvenience!
