### ISSUE TITLE
Errors when running server.js

### ISSUE THREAD

**Issue by switz** [HabitRPG/habitica#645]
Not sure what spawned this, but I'm seeing it every time. Perhaps using node v0.10.0?

Also model bundling errors :(

```
(inventory)habitrpg dsaewitz$ node server.js
   info  - socket.io started
Expressions in require() statements:
    require('./lang/' + key)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/Users/dsaewitz/y/habitrpg/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:455:7)
    at SendStream.send (/Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:347:8)
    at /Users/dsaewitz/y/habitrpg/node_modules/gzippo/node_modules/send/lib/send.js:322:10
    at Object.oncomplete (fs.js:93:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
Error: Model bundling took longer than 40000 ms
    at onBundleTimeout [as _onTimeout] (/Users/dsaewitz/y/habitrpg/node_modules/racer/lib/bundle/bundle.Model.js:63:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

**Comment by switz** [comment]
I should add that the page loads initially (I can see content), but never fully finishes loading. Eventually the model bundling timeout throws and the page doesn't complete. Might try rolling back a node version.

**Comment by switz** [comment]
Switched back to version 0.8 and it's now working. Must be something in derby or racer that doesn't play nicely with the newest node. So, be wary of updating just yet.

**Comment by lefnire** [comment]
oi, good to know! :o
