### ISSUE TITLE
Error when I log in

### ISSUE THREAD

**Issue by egastfriend** [HabitRPG/habitica#6717]
My account must be in a weird state -- whenever I log in, I get an error ("Yikes, an error occurred!").  On Win8 tried using both Chrome and Firefox.

User ID: f98c3d89-2a2b-46d1-abb8-79d9e6743175

It takes a long time for the loading bar to fill up all the way (even though my internet is fine), and this is the console output I get once it loads:

https://habitica.com/api/v2/groups/party Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-c14655c7.js:6 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.na [as fromJson](https://habitica.com/app-c14655c7.js:4:28377)
    at b.get.transformResponse (https://habitica.com/app-c14655c7.js:32:27856)
    at uc (https://habitica.com/app-c14655c7.js:6:9564)
    at n (https://habitica.com/app-c14655c7.js:6:11232)
    at j (https://habitica.com/app-c14655c7.js:7:9455)
    at https://habitica.com/app-c14655c7.js:7:9652
    at j.$eval (https://habitica.com/app-c14655c7.js:7:16402)
    at j.$digest (https://habitica.com/app-c14655c7.js:7:14865)
    at j.$apply (https://habitica.com/app-c14655c7.js:7:16678)(anonymous function) @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'code' of undefined
    at responseError (app-c14655c7.js:32)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)(anonymous function) @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (app-c14655c7.js:11)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)

**Comment by egastfriend** [comment]
This resolved itself.

**Comment by Alys** [comment]
@egastfriend Thanks for letting us know! It's an example of the frequent server errors we are having, and we're documenting our progress on preventing them in this issue: https://github.com/HabitRPG/habitrpg/issues/6700

This comment in that issue has our latest update: https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-184375608
