### ISSUE TITLE
spawn ENOENT error when running npm run sprites

### ISSUE THREAD

**Issue by nrbunn** [HabitRPG/habitica#6800]
When trying to run npm run sprites if fails shortly after clean up finishes.
Windows 10 / Vagrant
develop branch

[npm-debug.log](https://github.com/HabitRPG/habitrpg/files/153997/npm-debug.log.txt)

Output
vagrant@habitrpg:/vagrant$ npm run sprites

> habitrpg@0.0.0-152 sprites /vagrant
> gulp sprites:compile

[Error: /vagrant/node_modules/mongoose/node_modules/bson/build/Release/bson.node: invalid ELF header]
js-bson: Failed to load c++ bson extension, using pure JS version
[02:36:58] Using gulpfile /vagrant/gulpfile.js
[02:36:58] Starting 'sprites:clean'...
[02:36:58] Starting 'sprites:main'...
[02:37:06] Starting 'sprites:largeSprites'...
[02:37:06] Finished 'sprites:clean' after 8.45 s

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/home/vagrant/.nvm/v0.10.40/bin/npm" "run" "sprites"
npm ERR! node v0.10.40
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! habitrpg@0.0.0-152 sprites: `gulp sprites:compile`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the habitrpg@0.0.0-152 sprites script 'gulp sprites:compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp sprites:compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs habitrpg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log

**Comment by nrbunn** [comment]
So after debugging i found out it was bombing out due to gulp-imagemin. So looking around on there issues list i saw someone have something similar but not exact. work around was to uninstall gulp-imagemin and reinstall. So did that and it started working. Woot!. 

Before posting i wanted to double check i could reproduce so i destroyed my vagrant image and rebuilt. ran npm run sprites to get the issue but it worked. Sooo yeah.. not sure. closing
