### ISSUE TITLE
[API v3] Searing Brightness - Invalid Target

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7210]
General Info
- UUID: 7bde7864-ebc5-4ee2-a4b7-1070d464cdb0
- Browser: Safari
### Description

When Searing Brightness is cast, the target associated with using a skill on a specific task incorrectly appears. If you try to click on anything, it tells you that it is an "Invalid target." The cross persists through different tabs, and the button for Searing Brightness remains highlighted on the task page. Reloading resolves the issue.

**Comment by taldin** [comment]
Seconded, ran into this one too.

**Comment by TheHollidayInn** [comment]
@paglias @crookedneighbor I am pushing a fix that should fix the invalid target.

As for the persistent target `spell.immediateUse` is not being populated, and I am looking into it.

**Comment by paglias** [comment]
@TheHollidayInn is this fixed at least partially?

**Comment by TheHollidayInn** [comment]
Yea, not completely though.

**Comment by ghost** [comment]
Warrior skills: gaze and valorous presence - produce `Invalid request parameters.` error.

Please tell me if this should better be reported to a separate issue

**Comment by paglias** [comment]
@GitHubSphinx  about gaze and valorous presence can you open the console before you try to cast them, then switch to the Network tab. Once the error appears you should see a new red request, click on it and copy what you can find in the Response tab, thanks!

**Comment by ghost** [comment]
```
400 Post https://v3.habitica.com/api/v3/user/class/cast/valorousPresence [HTTP/1.1 400 Bad Request 229ms]

URL: https://v3.habitica.com/api/v3/user/class/cast/valorousPresence?targetType=party&targetId=undefined
Method: POST
Remote address: 52.0.71.148:443

Request:
Host: v3.habitica.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: application/json, text/plain, */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
x-api-user: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
x-api-key: deleted
x-client: habitica-web
x-user-timezoneOffset: -300
Referer: https://v3.habitica.com/
Cookie: _ga=GA1.2.807327335.1462612750; amplitude_idhabitica.com=eyJkZXZpY2VJZCI6IjBjZjc5MDE4LWUwNDYtNDFjMy1hYTYwLWY2YjY2NjdlMTZjMCIsInVzZXJJZCI6ImZmYTI2ZjkwLWY0Y2YtNDBiNS04YjNiLWFjYTk4OGFiOGVkMiIsImdsb2JhbFVzZXJQcm9wZXJ0aWVzIjp7IlVVSUQiOiJmZmEyNmY5MC1mNGNmLTQwYjUtOGIzYi1hY2E5ODhhYjhlZDIiLCJDbGFzcyI6ImhlYWxlciIsIkV4cGVyaWVuY2UiOjEyNSwiR29sZCI6MzAsIkhlYWx0aCI6MTIsIkxldmVsIjo4LCJNYW5hIjozNTEsInR1dG9yaWFsQ29tcGxldGUiOnRydWUsIk51bWJlciBPZiBUYXNrcyI6eyJoYWJpdHMiOjgsImRhaWx5cyI6MTksInRvZG9zIjo0LCJyZXdhcmRzIjoxM30sImNvbnRyaWJ1dG9yTGV2ZWwiOjcsInBhcnR5U2l6ZSI6MTF9LCJvcHRPdXQiOmZhbHNlfQ==; connect:sess=eyJwYXNzcG9ydCI6e30sInVzZXJJZCI6ImZmYTI2ZjkwLWY0Y2YtNDBiNS04YjNiLWFjYTk4OGFiOGVkMiJ9; connect:sess.sig=qU0vhBiRyOyrd4t69Gl77vzqXn0; _ga=GA1.3.807327335.1462612750; session-set=true; __atuvc=15%7C19%2C22%7C20; __atuvs=5738ae80425a5e5e004
X-Compress: 1
Proxy-Authorization: 5596afc6d6b6faaefe1f7746b4199dd864c19ecd09509c6e2a298ab1174b20ad3359341b257e2e35
Connection: keep-alive
Content-Length: 0

Response:
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 177
Content-Type: application/json; charset=utf-8
Date: Sun, 15 May 2016 18:08:03 GMT
Etag: W/"b1-dfgC6+10PgpRviazKgre0A"
Server: nginx/1.8.1
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Powered-By: Express
```

And response for Valorous Presence (https://v3.habitica.com/api/v3/user/class/cast/intimidate?targetType=party&targetId=undefined)

```
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 177
Content-Type: application/json; charset=utf-8
Date: Sun, 15 May 2016 18:18:24 GMT
Etag: W/"b1-dfgC6+10PgpRviazKgre0A"
Server: nginx/1.8.1
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Powered-By: Express
```

**Comment by GitHubSphinx** [comment]
response for Valorous Presence added above:
(https://v3.habitica.com/api/v3/user/class/cast/intimidate?targetType=party&targetId=undefined)

```
Access-Control-Allow-Headers: Content-Type,Accept,Content-Encoding,X-Requested-With,x-api-user,x-api-key
Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,HEAD,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 177
Content-Type: application/json; charset=utf-8
Date: Sun, 15 May 2016 18:18:24 GMT
Etag: W/"b1-dfgC6+10PgpRviazKgre0A"
Server: nginx/1.8.1
Vary: X-HTTP-Method-Override, Accept-Encoding
X-Powered-By: Express
```

**Comment by ghost** [comment]
@paglias Oh, I'm afraid that's not what you've asked for (

Maybe this responce:

![pic](https://snag.gy/VW4wUb.jpg)

**Comment by paglias** [comment]
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

**Comment by quin-jay** [comment]
@paglias I'm still seeing the 'Invalid target' error with Searing Brightness. When I click on the skill, these errors show up:

```
angular.js:11594 ReferenceError: task is not defined
    at https://v3.habitica.com/js/controllers/rootCtrl.js:297:20
    at Array.filter (native)
    at Scope.$scope.castStart (https://v3.habitica.com/js/controllers/rootCtrl.js:295:23)
    at $parseFunctionCall (https://v3.habitica.com/bower_components/angular/angular.js:12332:18)
    at callback (https://v3.habitica.com/bower_components/angular/angular.js:21389:17)
    at Scope.$eval (https://v3.habitica.com/bower_components/angular/angular.js:14384:28)
    at Scope.$apply (https://v3.habitica.com/bower_components/angular/angular.js:14483:23)
    at HTMLAnchorElement.<anonymous> (https://v3.habitica.com/bower_components/angular/angular.js:21394:23)
    at HTMLAnchorElement.o.event.dispatch (https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:6055)
    at HTMLAnchorElement.r.handle (https://v3.habitica.com/bower_components/jquery/dist/jquery.min.js:3:2830)
```

**Comment by paglias** [comment]
@lynnyliz sorry for all the problems with this, it should work now!

**Comment by quin-jay** [comment]
@paglias Oh dear, the Invalid Target error is gone, but it looks like the spell doesn't actually work for some reason. I'll open a new issue for that, with screenshots

**Comment by paglias** [comment]
@lynnyliz it works fine for me
