### ISSUE TITLE
[API v3] Progress graph not working 

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#7214]
Clicking on the progress graph on Habits/Dailies does nothing.

**Comment by paglias** [comment]
```
Error: Container is not defined
    at Error (native)
    at mk (https://www.google.com/uds/api/visualization/1.0/3aac6319fc4653f92eff596244212066/format+it,default+it,ui+it,corechart+it.I.js:110:37)
    at yP.Ms [as constructor] (https://www.google.com/uds/api/visualization/1.0/3aac6319fc4653f92eff596244212066/format+it,default+it,ui+it,corechart+it.I.js:371:98)
    at yP.pP [as constructor] (https://www.google.com/uds/api/visualization/1.0/3aac6319fc4653f92eff596244212066/format+it,default+it,ui+it,corechart+it.I.js:1333:698)
    at new yP (https://www.google.com/uds/api/visualization/1.0/3aac6319fc4653f92eff596244212066/format+it,default+it,ui+it,corechart+it.I.js:1359:372)
    at Scope.$rootScope.toggleChart (https://v3.habitica.com/js/controllers/rootCtrl.js:201:15)
    at $parseFunctionCall (https://v3.habitica.com/bower_components/angular/angular.js:12332:18)
    at callback (https://v3.habitica.com/bower_components/angular/angular.js:21389:17)
    at Scope.$eval (https://v3.habitica.com/bower_components/angular/angular.js:14384:28)
    at Scope.$apply (https://v3.habitica.com/bower_components/angular/angular.js:14483:23)(anonymous function) @ angular.js:11594(anonymous function) @ angular.js:8544Scope.$apply @ angular.js:14485(anonymous function) @ angular.js:21394o.event.dispatch @ jquery.js:4371r.handle @ jquery.js:4057
```

**Comment by paglias** [comment]
Fixed in https://github.com/HabitRPG/habitrpg/tree/api-v3
