### ISSUE TITLE
reset memberCount attribute for all groups - guilds and parties (was: Guild has negative members?)

### ISSUE THREAD

**Issue by froggily** [HabitRPG/habitica#7506]
General Info
- UUID: 634ef54c-8d52-4293-8adc-f0e810dd85dc
- Browser: Chrome Version 50.0.2661.86 (64-bit)
- OS: OS X Yosemite 10.10.5
### Description

The guild [Faithful Heroes](https://habitica.com/#/options/groups/guilds/db8fabb5-f07c-434c-bbcc-35d1081ad495) appears to [have -5 members.](https://www.dropbox.com/s/4kblmmjc6eaq2qi)
#### Console Errors

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app-5d6051d5.js:6 TypeError: Cannot read property 'timestamp' of undefined
    at h (https://habitica.com/app-5d6051d5.js:44:12439)
    at https://habitica.com/app-5d6051d5.js:44:12628
    at ma (https://habitica.com/app-5d6051d5.js:6:7459)
    at pa (https://habitica.com/app-5d6051d5.js:6:3005)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at pa (https://habitica.com/app-5d6051d5.js:6:2949)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at pa (https://habitica.com/app-5d6051d5.js:6:2949)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at h (https://habitica.com/app-5d6051d5.js:5:28270) <span from-now="::message.timestamp" tooltip="{{::message.timestamp | date:user.preferences.dateFormat.concat(' HH:mm:ss')}}" class="muted time">(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at s (app-5d6051d5.js:6)
    at w (app-5d6051d5.js:6)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at j.$eval (app-5d6051d5.js:7)
    at app-5d6051d5.js:8
    at app-5d6051d5.js:5
    at j.$eval (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at s (app-5d6051d5.js:6)
    at w (app-5d6051d5.js:6)(anonymous function) @ app-5d6051d5.js:6
2app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at app-5d6051d5.js:7
    at p (app-5d6051d5.js:5)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at HTMLButtonElement.<anonymous> (app-5d6051d5.js:8)
    at HTMLButtonElement.o.event.dispatch (app-5d6051d5.js:2)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at app-5d6051d5.js:7
    at p (app-5d6051d5.js:5)(anonymous function) @ app-5d6051d5.js:6
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=1144336897&_v=j43&z=1340163844 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=305580734&_v=j43&z=604658887 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/#/options/groups/guilds/0393624e-65f0-40c1-8e87-360955fcebca:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/0393624e-65f0-40c1-8e87-360955fcebca' was loaded over HTTPS, but requested an insecure image 'http://c2.staticflickr.com/6/5798/20762427198_f5198680b3.jpg'. This content should also be served over HTTPS.
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=1760683537&_v=j43&z=1179776007 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e' was loaded over HTTPS, but requested an insecure image 'http://20px.com/wp-content/uploads/2013/09/field_guide_to_procrastinators_20px.jpg'. This content should also be served over HTTPS.
/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e' was loaded over HTTPS, but requested an insecure image 'http://www.network-marketing-mlm-success-system.com/images/SMART-Goals-1.gif'. This content should also be served over HTTPS.
/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/3d5c008e-664a-4cc6-a1bd-34d1baccc31e' was loaded over HTTPS, but requested an insecure image 'http://s15.postimg.org/4b6zmjsm3/Procrastinators_logo_1_Copia.png'. This content should also be served over HTTPS.
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=1337340240&_v=j43&z=1878243108 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/#/options/groups/guilds/dea7a124-9e69-4163-a708-d3e961a96159:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/dea7a124-9e69-4163-a708-d3e961a96159' was loaded over HTTPS, but requested an insecure image 'http://www.photoshopcreative.co.uk/users/1220/thm1024/ghostship800.jpg'. This content should also be served over HTTPS.
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=248019584&_v=j43&z=327498772 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app-5d6051d5.js:6 TypeError: Cannot read property 'timestamp' of undefined
    at h (https://habitica.com/app-5d6051d5.js:44:12439)
    at https://habitica.com/app-5d6051d5.js:44:12628
    at ma (https://habitica.com/app-5d6051d5.js:6:7459)
    at pa (https://habitica.com/app-5d6051d5.js:6:3005)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at pa (https://habitica.com/app-5d6051d5.js:6:2949)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at pa (https://habitica.com/app-5d6051d5.js:6:2949)
    at r (https://habitica.com/app-5d6051d5.js:5:29222)
    at h (https://habitica.com/app-5d6051d5.js:5:28270) <span from-now="::message.timestamp" tooltip="{{::message.timestamp | date:user.preferences.dateFormat.concat(' HH:mm:ss')}}" class="muted time">(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at s (app-5d6051d5.js:6)
    at w (app-5d6051d5.js:6)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at j.$eval (app-5d6051d5.js:7)
    at app-5d6051d5.js:8
    at app-5d6051d5.js:5
    at j.$eval (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at s (app-5d6051d5.js:6)
    at w (app-5d6051d5.js:6)(anonymous function) @ app-5d6051d5.js:6
2app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at app-5d6051d5.js:7
    at p (app-5d6051d5.js:5)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at z (app-5d6051d5.js:23)
    at HTMLSpanElement.x (app-5d6051d5.js:23)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (https://habitica.com/app-5d6051d5.js:44:27177)
    at g (https://habitica.com/app-5d6051d5.js:7:3746)
    at D.|| (https://habitica.com/app-5d6051d5.js:6:27173)
    at Array.f (https://habitica.com/app-5d6051d5.js:7:161)
    at d (https://habitica.com/app-5d6051d5.js:7:4491)
    at Object.h (https://habitica.com/app-5d6051d5.js:7:7813)
    at j.$digest (https://habitica.com/app-5d6051d5.js:7:14986)
    at j.$apply (https://habitica.com/app-5d6051d5.js:7:16678)
    at HTMLSpanElement.y (https://habitica.com/app-5d6051d5.js:23:9950)
    at HTMLSpanElement.o.event.special.(anonymous function).handle (https://habitica.com/app-5d6051d5.js:2:9681)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at app-5d6051d5.js:7
    at p (app-5d6051d5.js:5)(anonymous function) @ app-5d6051d5.js:6
app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at HTMLButtonElement.<anonymous> (app-5d6051d5.js:8)
    at HTMLButtonElement.o.event.dispatch (app-5d6051d5.js:2)(anonymous function) @ app-5d6051d5.js:6
2app-5d6051d5.js:6 TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j.a.isUserMentioned (app-5d6051d5.js:44)
    at g (app-5d6051d5.js:7)
    at D.|| (app-5d6051d5.js:6)
    at Array.f (app-5d6051d5.js:7)
    at d (app-5d6051d5.js:7)
    at Object.h (app-5d6051d5.js:7)
    at j.$digest (app-5d6051d5.js:7)
    at j.$apply (app-5d6051d5.js:7)
    at app-5d6051d5.js:7
    at p (app-5d6051d5.js:5)(anonymous function) @ app-5d6051d5.js:6
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=39056946&_v=j43&z=1036965198 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/#/options/groups/guilds/16b96e1b-0b59-4b49-b9a7-05f20ff760e6:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/16b96e1b-0b59-4b49-b9a7-05f20ff760e6' was loaded over HTTPS, but requested an insecure image 'http://i16.photobucket.com/albums/b22/Istra_/FullSizeRender_1.jpg'. This content should also be served over HTTPS.
/#/options/groups/guilds/b2be8bd2-9545-438c-8fd3-13e08c2ca723:1 Mixed Content: The page at 'https://habitica.com/#/options/groups/guilds/b2be8bd2-9545-438c-8fd3-13e08c2ca723' was loaded over HTTPS, but requested an insecure image 'http://41.media.tumblr.com/80225056d2991b2ac12828450e3b2f0e/tumblr_inline_o4ivp6WOvY1qmklf1_250.png'. This content should also be served over HTTPS.
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=1681984174.1462985724&jid=97328581&_v=j43&z=375306912 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by citrusella** [comment]
The guild currently has -3. Joining brings the number higher (i.e. -2), but leaving brings it back down.

**Comment by Alys** [comment]
I've adjusted the guild's memberCount to 4 so the immediate problem is fixed. 

We'll do a migration script for correcting the member counts of all guilds.

**Comment by paglias** [comment]
Is this still needed?

**Comment by Alys** [comment]
Yes. I haen't had a chance to do it yet. :(

**Comment by TheHollidayInn** [comment]
Should we close this in favor of #7454?

**Comment by Alys** [comment]
Yes, good idea. Closing.
