### ISSUE TITLE
Overwriting item from list with the text from previous position

### ISSUE THREAD

**Issue by Zajec** [HabitRPG/habitica#7559]
General Info
- UUID: Zejec
- Browser: Chrome
- OS: Win7 x64
### Description

The bug exists while editing the list under a task in To-Do.
After filling the last empty field and pressing enter, new line is created but the text from the field I just finished is replaced with the text from the previous point. It happens once for each edition of the Task (next lines are created normally). 
#### Console Errors

app-c45ccd28.js:40 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-c45ccd28.js:40:27273)
    at Object.u.authenticate (https://habitica.com/app-c45ccd28.js:44:8863)
    at Object.<anonymous> (https://habitica.com/app-c45ccd28.js:44:10013)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-c45ccd28.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16822)
    at https://habitica.com/app-c45ccd28.js:5:14868
    at g (https://habitica.com/app-c45ccd28.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-c45ccd28.js:5:16789)
    at D.instance (https://habitica.com/app-c45ccd28.js:6:8436)

**Comment by crookedneighbor** [comment]
This has been fixed, but it is not yet deployed.
