### ISSUE TITLE
PhantomJS! PhantomJS!  PhantomJS no found again.

### ISSUE THREAD

**Issue by mistkafka** [HabitRPG/habitica#7666]
General Info
- UUID: 
- Browser: 
- OS: CentOS7 (on VM)
### Description

I have read [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally). And I read [#7090](https://github.com/HabitRPG/habitrpg/issues/7090#issuecomment-214714317). Yes, we need swap file, and I create a 8GB swap file. But, it still error when I run npm install.
#### Console Errors

```
Considering PhantomJS found at /media/psf/mistkafka/Code/node.js/habitrpg/node_modules/.bin/phantomjs
Looks like an `npm install -g`
Error checking path, continuing { [Error: Cannot find module '/media/psf/mistkafka/Code/node.js/habitrpg/node_modules/.npminstall/phantomjs/1.9.20/phantomjs/lib/location'] code: 'MODULE_NOT_FOUND' }
Phantom installation failed [TypeError: Path must be a string. Received undefined] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at findSuitableTempDirectory (/media/psf/mistkafka/Code/node.js/habitrpg/node_modules/.npminstall/phantomjs-prebuilt/2.1.7/phantomjs-prebuilt/install.js:127:30)
    at /media/psf/mistkafka/Code/node.js/habitrpg/node_modules/.npminstall/phantomjs-prebuilt/2.1.7/phantomjs-prebuilt/install.js:476:19
    at nextTickCallback (/media/psf/mistkafka/Code/node.js/habitrpg/node_modules/.npminstall/kew/0.7.0/kew/kew.js:47:28)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
    at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.4.5/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Alys** [comment]
Can you please delete the node_modules directory, do `npm cache clean`,
then `npm install` again, twice if the first one gives any errors, and then
if the second one fails as well, show us the full output of both install
attempts.

**Comment by Alys** [comment]
I'm closing this now but if you'd like more help, see my previous post, and let us know how that goes. We'll still see your reply and can reopen this if necessary.
