### ISSUE TITLE
Page Freeze After Submitting Post in Party/Guild

### ISSUE THREAD

**Issue by cmontello** [HabitRPG/habitica#7675]
General Info
- UUID: fa5b431d-140f-4a53-9938-3782e4389932
- Browser: Chrome
- OS: Mac OSX 10.11.5
### Description

Whenever I submit a message/post in my party or a guild on the website the page freezes and I have to reload it. I tried disabling all my extensions and it still froze. When I did it on Safari everything worked fine and nothing froze.
#### Console Errors

Not sure if this is what you're talking about as far as JavaScript console errors, but I thought I would include it just in case:
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-3c5f424b.js:40:28193)
    at Object.w.authenticate (https://habitica.com/app-3c5f424b.js:44:11295)
    at Object.<anonymous> (https://habitica.com/app-3c5f424b.js:44:12445)
    at Object.i [as invoke](https://habitica.com/app-3c5f424b.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-3c5f424b.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-3c5f424b.js:5:16822)
    at https://habitica.com/app-3c5f424b.js:5:14868
    at g (https://habitica.com/app-3c5f424b.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-3c5f424b.js:5:16789)
    at D.instance (https://habitica.com/app-3c5f424b.js:6:8436)

**Comment by paglias** [comment]
Confirmed on OS X with Chrome. In My case it happens only with guilds, not with my party and only freeze for a few seconds.

I'd say this is a perf problem that will be addresses with the redesign. But it's pretty annoying so if someone has a fix for it, please submit it

**Comment by Alys** [comment]
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by librarianmage** [comment]
Does this still happen?

**Comment by paglias** [comment]
can reopen if it happens again
