### ISSUE TITLE
Character not leveling up after quest

### ISSUE THREAD

**Issue by juanpflores** [HabitRPG/habitica#7751]
General Info
- UUID: f3c5f608-ff31-4bf4-9bee-7be8ed3465aa
- Browser: Chrome
- OS: Mac OS X "El Capitan" 10.11.5
### Description

My party just finished a Quest. I have enough XP to level up though I'm not getting to the next level. I refreshed the browser and there was no change on it. 

![image](https://cloud.githubusercontent.com/assets/6200135/16538237/edeafa62-3fe3-11e6-8965-5530be3f3dc9.png)
#### Console Errors

Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
2VM10638:5 Uncaught TypeError: Cannot read property 'removeAttribute' of null(anonymous function) @ VM10638:5(anonymous function) @ VM10638:20
app-b03dbe0f.js:41 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-b03dbe0f.js:41:4614)
    at Object.authenticate (https://habitica.com/app-b03dbe0f.js:44:20010)
    at Object.<anonymous> (https://habitica.com/app-b03dbe0f.js:44:21231)
    at Object.i [as invoke](https://habitica.com/app-b03dbe0f.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-b03dbe0f.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-b03dbe0f.js:5:16822)
    at https://habitica.com/app-b03dbe0f.js:5:14868
    at g (https://habitica.com/app-b03dbe0f.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-b03dbe0f.js:5:16789)
    at D.instance (https://habitica.com/app-b03dbe0f.js:6:8436)
13VM10944:5 Uncaught TypeError: Cannot read property 'removeAttribute' of null

**Comment by juanpflores** [comment]
It took a couple of hours to level up

**Comment by Alys** [comment]
Please see https://github.com/HabitRPG/habitrpg/issues/2433 for this issue.
