### ISSUE TITLE
local install error: fs.js:808 - return binding.readdir(pathModule._makeLong(path));

### ISSUE THREAD

**Issue by dpaczewski** [HabitRPG/habitica#7758]
General Info
- UUID: n/a
- Browser: n/a
- OS: Ubuntu 14.04
- node: v4.4.7
- npm: 3.10.3
- grunt: grunt-cli v1.2.0
- habitica build: I think it's the latest
### Description

I try to install habitica on fresh Ubuntu installation (v 14.04) running on VMwave. I follow the instructions found on the local installation page. Once I run the 'npm start' command I get the information that:

[nodemon] app crashed - waiting for file changes before starting...
#### Console Errors

night@nemesis:~/habitrpg$ npm start

> habitica@3.20.0 start /home/night/habitrpg
> gulp run:dev

[07:31:52] Using gulpfile ~/habitrpg/gulpfile.js
[07:31:52] Starting 'nodemon'...
[07:31:52] Finished 'nodemon' after 2.73 ms
[07:31:52] Starting 'browserify'...
[07:31:52] Starting 'prepare:staticNewStuff'...
[07:31:54] Finished 'prepare:staticNewStuff' after 1.41 s
[07:31:54] [nodemon] 1.9.2
[07:31:54] [nodemon] to restart at any time, enter `rs`
[07:31:54] [nodemon] watching: _._
[07:31:54] [nodemon] starting `node ./website/server/index.js`
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/night/habitrpg/website/build'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at _walk (buildManifest.js:13:18)
    at Object.<anonymous> (buildManifest.js:36:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (locals.js:5:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (dataexport.js:15:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
[07:32:39] [nodemon] app crashed - waiting for file changes before starting...
[07:32:40] [nodemon] restarting due to changes...
[07:32:40] [nodemon] starting `node ./website/server/index.js`
[07:32:40] Finished 'browserify' after 48 s
[07:32:40] Starting 'build:dev'...
[07:32:40] Starting 'grunt-build:dev'...
Running "cssmin:dist" (cssmin) task
File common/dist/sprites/habitrpg-shared.css created: 804.02 kB → 696 kB → 45.26 kB (gzip)

Running "stylus:build" (stylus) task

> > Error: website/client/css/index.styl:6:9
> >     2| //@import "nib/vendor"
> >     3| 
> >     4| // Vendor Includes - include first so we can override
> >     5| // Import only styles that do not have urls to images! Include them directly in the page!
> >     6| @import "../bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css"
> > --------------^
> >     7| @import "../bower_components/angular-loading-bar/build/loading-bar.css"
> >     8| @import "../bower_components/select2/select2.css"
> >     9| 
> > 
> > failed to locate @import file ../bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css
> > Warning: Stylus failed to compile. Used --force, continuing.
> > Error: website/client/css/static.styl:5:9
> >    1| @import "nib"
> >    2| 
> >    3| // Vendor Includes - include first so we can override
> >    4| // Import only styles that do not have urls to images! Include them directly in the page!
> >    5| @import "../bower_components/angular-loading-bar/build/loading-bar.css"
> > --------------^
> >    6| @import "./shared.styl"
> >    7| @import "./footer"
> >    8| 
> > 
> > failed to locate @import file ../bower_components/angular-loading-bar/build/loading-bar.css
> > Warning: Stylus failed to compile. Used --force, continuing.

Done, but with warnings.
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[07:32:50] Finished 'grunt-build:dev' after 9.95 s
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/night/habitrpg/website/build'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at _walk (buildManifest.js:13:18)
    at Object.<anonymous> (buildManifest.js:36:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (locals.js:5:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (dataexport.js:15:1)
    at Module._compile (module.js:409:26)
    at loader (/home/night/habitrpg/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js](/home/night/habitrpg/node_modules/babel-register/lib/node.js:168:7)
[07:32:52] [nodemon] app crashed - waiting for file changes before starting...

**Comment by Alys** [comment]
Can you please show us the full output of the earlier steps in the installation process? It's likely that errors started there, and we'll need to fix the earliest errors first. Also tell us how much swap space is on your nemesis machine.

**Comment by dpaczewski** [comment]
OK, but I will have to go through the installation process once again, so I will have the time to do this in a couple of hours.

I don't think I have swap unless Ubuntu creates it on it's own.

If it comes to installation then I had to perform one additional step which was the installation of g++ which wasn't installed by default and which is not mentioned in wiki - I think that was the reason I had to run the installation process twice.

I will attach all the details in the evening.

**Comment by paglias** [comment]
@dpaczewski can you try creating manually the folder `/home/night/habitrpg/website/build`?

**Comment by dpaczewski** [comment]
@paglias - this sovled the problem. Looks like the system is up and running! Thank you :)

![image](https://cloud.githubusercontent.com/assets/15254143/16590997/2cca1cba-42da-11e6-89a6-1a5907e1dae9.png)

**Comment by paglias** [comment]
@dpaczewski great!

**Comment by EightsCuh** [comment]
i use os=Windows 8.1
