### ISSUE TITLE
GETTING ERROR IN GULP FILE

### ISSUE THREAD

**Issue by sonydaman** [HabitRPG/habitica#8108]
Can you please help in the issue

C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code>gulp
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code\gulp'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at readdirSyncRecursive (C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code\node_modules\wrench\lib\wrench.js:37:23)
    at Object.exports.readdirSyncRecursive (C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code\node_modules\wrench\lib\wrench.js:51:20)
    at Object.<anonymous> (C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code\gulpfile.js:16:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

C:\Users\SA355398\Downloads\Vistadesk\Vistadesk\new-1.5-source-code\new-1.5-source-code>

**Comment by crookedneighbor** [comment]
This doesn't look related to Habitica. Did you mean to post here? 

Going to close this, but reopen it if I am mistaken.
