### ISSUE TITLE
First time sync doesn't work

### ISSUE THREAD

**Issue by nehaagarwald** [HabitRPG/habitica#8136]
General Info
- UUID: 30028856-a5cc-4b37-a32e-97f31040aa44
- Browser: Safari
- OS: Mac
### Description

Checked out habitRPG for the first time.
When I run the command "habitsync", I gett eh folloing error in the console.
#### Console Errors

If this is OK with you, type the word yes in full
prompt: okToContinue:  yes
Now syncing with habitrpg.com...
readline.js:982
            throw err;
            ^

SyntaxError: Syntax error in line 1
    at IniReaderCore.parseFile (/usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/inireader/lib/inireadercore.js:313:44)
    at IniReaderCore.load (/usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/inireader/lib/inireadercore.js:244:32)
    at startSync (/usr/local/lib/node_modules/habitrpg-todo-sync/main.js:116:14)
    at /usr/local/lib/node_modules/habitrpg-todo-sync/main.js:93:7
    at /usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/prompt/lib/prompt.js:316:32
    at /usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/async/lib/async.js:142:25
    at assembler (/usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/prompt/lib/prompt.js:313:9)
    at /usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/prompt/lib/prompt.js:322:32
    at /usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/prompt/lib/prompt.js:597:5
    at Interface.onLine (/usr/local/lib/node_modules/habitrpg-todo-sync/node_modules/read/lib/read.js:111:5)
➜  ~

**Comment by SabreCat** [comment]
Hi @nehaagarwald -- this appears to be an issue with https://github.com/wizonesolutions/habitrpg-todo-sync , not with the main Habitica site. Given that repository hasn't been updated since June of last year, it's likely it needs (at a minimum) to be updated to use the current version of Habitica's API! Please reach out to the maintainers there to see if the script is likely to be updated.
