### ISSUE TITLE
ubntu 14.04 npm install error: invalid name: '@slack/client' npm start error: cannot find module 'babel-register'

### ISSUE THREAD

**Issue by DoraEx** [HabitRPG/habitica#8141]
General Info
- UUID:  -
- Browser:  -
- OS:  Ubunto 14.04
### Description

Sorry if this is a repeat issue, I tried searching issues but couldn't find anything. 
After getting most of the other errors to go away by re-running `npm install` (7 times) and increasing my swap file size, there is still one that will not go away . The output looks like this:

`npm ERR! Error: Invalid name: "@slack/client`
`npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)`
`npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)`
`npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38`
`npm ERR!     at Array.forEach (native)`
`npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)`
`npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)`
`npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)`
`npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:234:40`
`npm ERR!     at fs.js:268:14`
`npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5`

I decided to move on anyway, and when running `npm start` I got this:

```
>habitica@3.48.0 start /home/adora/Habitica/habitica
 >gulp run:dev


Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/adora/Habitica/habitica/gulpfile.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

so then i ran `npm install babel-register` and `npm start`again and got this instead: 

```
ReferenceError: Unknown plugin "transform-async-to-module-method" specified in "/home/adora/Habitica/habitica/.babelrc" at 0, attempted to resolve relative to "/home/adora/Habitica/habitica"
    at /home/adora/Habitica/habitica/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/home/adora/Habitica/habitica/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/adora/Habitica/habitica/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:36)
    at OptionManager.init (/home/adora/Habitica/habitica/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at compile (/home/adora/Habitica/habitica/node_modules/babel-register/lib/node.js:102:45)
    at loader (/home/adora/Habitica/habitica/node_modules/babel-register/lib/node.js:146:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/adora/Habitica/habitica/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

I'm not sure about the WARN though, because node links to nodejs

**Comment by DoraEx** [comment]
so after looking more into other issues, i tried 
`sudo npm install -g`
and this was at the top of the output file...
`npm WARN engine habitica@3.48.0: wanted: {"node":"^4.3.1","npm":"^3.8.9"} (current: {"node":"v0.10.25","npm":"1.3.10"})` so i will try updating first?

**Comment by crookedneighbor** [comment]
You just have an old version of node and npm. Node should be at least v4 and npm should be at v3. Reopen if you still have trouble after updating. 

You will likely need to delete the node_modules folder and then reinstall the modules with npm 3
