### ISSUE TITLE
Habitica does not build as a docker container after upgrade to npm@4

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica#8288]
General Info
  * UUID: 30983c37-52c3-415d-977c-38af6c7db91c
  * OS: docker

### Description
Because each line of a Dockerfile runs as a separate container in cache, the environment that installs npm@4 does not carry over to subsequent commands, resulting in a failure of npm commands.

#### Console Errors
    Step 11 : RUN npm install -g gulp grunt-cli bower
     ---> Running in 1a82edfe5612
    module.js:471
        throw err;
        ^

    Error: Cannot find module 'semver'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
    The command '/bin/sh -c npm install -g gulp grunt-cli bower' returned a non-zero code: 1

**Comment by DrStrangepork** [comment]
This appears to be a known bug with npm: https://github.com/npm/npm/issues/15225
