### ISSUE TITLE
Unable to Export to CSV Challenge Data

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#8350]
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 42.0.2393.85
Windows 10 32-bit

## Description

When export CSV challenge data receiving error message on screen:
{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}

Example Challenge:
[Clean the Dungeon (dailies slayer) – December – Winter Wonderland (Snowball all the monsters of the day) ID: 3f0be455-990c-49b0-90cc-2ef3b9214949](https://habitica.com/#/options/groups/challenges/3f0be455-990c-49b0-90cc-2ef3b9214949)

No Console error messages,

----

**edit by Alys 2017-08-10:**

## Suggested Fix

**The explanation for this bug and a suggested fix is in [this comment below](https://github.com/HabitRPG/habitica/issues/8350#issuecomment-321517442).**

----

## What to do if this happens to you

Post to the Report a Bug guild and copy the URL of the challenge into your post. An admin will probably be able to make the CSV file available.

**Comment by Alys** [comment]
Confirmed. I get the same error with https://habitica.com/api/v3/challenges/3f0be455-990c-49b0-90cc-2ef3b9214949/export/csv

I can't find any errors in the data downloaded by `eb logs --all`

**Comment by paglias** [comment]
From logs

```
error: TypeError: Cannot read property 'push' of undefined
    at /var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:747:32
    at Array.forEach (native)
    at _callee7$ (/var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:741:21)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:355:22)
```

Probably due to https://github.com/HabitRPG/habitica/blob/1985d04bcf2de0931c77d92a4da49e694749a2c7/website/server/controllers/api-v3/challenges.js#L560

**Comment by Alys** [comment]
I'd been assuming that cTheDragons's User ID would be in the log file record. :( 

@cTheDragons Can you try again now?  I think this was a side effect of the profile name bug.

**Comment by cTheDragons** [comment]
Still no joy. Same screen as before.

`{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}`

**Comment by cTheDragons** [comment]
Since this appears to only be affecting me and this particular challenge may I close the challenge please?

**Comment by Alys** [comment]
I'm really sorry we never solved this. :(  Is there any data we can give you to help you assess the challenge?

**Comment by cTheDragons** [comment]
No I'm good. I think :) As you know using my own "ways" to see if I can find the answers I need.

**Comment by Alys** [comment]
From the Report a Bug guild by maxmoon (12631f31-5d3f-4796-b315-ad7115749beb) :

**I wanted to download the csv file of one of my challenges to choose a winner, but the export button always gives me an unexpected error. The download works for all of my other challenges, but not this one. It is this challenge: https://habitica.com/#/options/groups/challenges/b63d1fdd-8588-4317-8cfe-37419e750f14**
 
**I tried to get the csv with api queues, but still the same error: "{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}"**

From our logs:
```
2017-03-01T15:12:11.703Z - error: TypeError: Cannot read property 'push' of undefined
    at /var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:751:32
    at Array.forEach (native)
    at _callee7$ (/var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:745:21)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:355:
22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-ru
ntime/runtime.js:116:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/var/app/current/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/var/app/current/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
at processImmediate [as _immediateCallback] (timers.js:582:5) method=GET, originalUrl=/api/v3/challenges/b63d1fdd-8588-4317-8cfe-37419e750f14/export/csv, host=habitica.com, x-real-ip=, x-forwarded-for=, , accept=*/*, accept-encoding=deflate, gzip, content-type=application/csv, user-agent=curl/7.52.1, x-api-user=12631f31-5d3f-4796-b315-ad7115749beb, x-forwarded-port=443, x-forwarded-proto=https, , httpCode=500, isHandledError=false,
```

I haven't had time to look further into this today but will try to later if another admin can't look at it first. I might not be able to get to it for 24 hours though - full day today. :(

maxmoon, please don't delete the challenge yet. We'll let you know when we've finished investigating.

**Comment by therealmaxmoon** [comment]
@Alys Sorry, I have read your message to not close the challenge to late. I had to choose a winner for the challenge, because people are going crazy if my challenges will not end at the last day of a month. But my first guess was the api has problems with usernames, because I had participants from all over the world and the usernames contain foreign signs.

**Comment by Alys** [comment]
Also happened with the March TakeThis challenge:

2017-04-01T22:38:09.235Z - error: TypeError: Cannot read property 'push' of undefined
    at /var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:747:32
    at Array.forEach (native)
    at _callee7$ (/var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:741:21)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:116:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/app/current/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/app/current/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5) method=GET, originalUrl=/api/v3/challenges/630018a7-49ab-4e95-ac26-12417b746e1c/export/csv, host=habitica.com, accept=*/*, user-agent=curl/7.47.0, x-api-user=d904bd62-da08-416b-a816-ba797c9ee265, x-forwarded-port=443, x-forwarded-proto=https, , httpCode=500, isHandledError=false,

**Comment by Alys** [comment]
Another report.

2017-07-19T01:58:45.566Z - error: TypeError: Cannot read property 'push' of undefined
    at /var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:913:32
    at Array.forEach (native)
    at _callee7$ (/var/app/current/website/transpiled-babel/controllers/api-v3/challenges.js:907:21)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:117:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/app/current/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/app/current/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
at processImmediate [as _immediateCallback] (timers.js:596:5) method=GET, originalUrl=/api/v3/challenges/1bef037c-987e-44fe-9261-33d2bb5f423e/export/csv

**Comment by Alys** [comment]
Solved it. :)  Or at least I know what causes it; I have not written code to prevent this bug but that should be easy now. Also, until the fix is written and live, we could do once-off fixes for each challenge that is affected by this, although for large challenges that would be time consuming.

This bug happens when, at some time in the past, **a challenge participant has left the challenge choosing to either remove or keep the challenge tasks BUT an error occurs that does not delete their copy of the challenge tasks or does not edit their copy of the tasks to remove the challenge's data.**

**The export code finds the challenge tasks belonging to that user and tries to push them into its array of challenge participant data but because that array had been created from the list of current participants, there's no element for the participant who left the challenge, and the code fails.**
https://github.com/HabitRPG/habitica/blob/1985d04bcf2de0931c77d92a4da49e694749a2c7/website/server/controllers/api-v3/challenges.js#L560

**The fix would be to execute that line of code only if `resArray[index]` exists. That new code should also have a comment explaining why it's necessary because it won't be obvious to any future coder (e.g., a link back to this issue).** (A proper fix would be to prevent the underlying problem of the ex-participant's challenge tasks not being deleted/edited correctly, but that would require a work-around for mongodb's lack of transactions, which is a Habitica-wide problem with no easy solution.)

I found an example of this bug in a challenge owned by Ceran, who reported this in the Report a Bug guild. The task below belongs to a user who was not listed in the challenge participants. As you can see, the `challenge` object in the task is still populated, whereas it should have been just `{}`
```
{
	"_id" : "bb5df3e1-814a-4528-ae84-38367045a350",
	"userId" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"text" : "I did .... :tomato:s today. (Fill in the notes)",
	"__v" : 0,
	"updatedAt" : ISODate("2017-08-08T15:27:40.343Z"),
	"createdAt" : ISODate("2017-08-05T19:14:36.001Z"),
	"reminders" : [ ],
	"group" : {
		"approval" : {
			"requested" : false,
			"approved" : false,
			"required" : false
		},
		"assignedUsers" : [ ]
	},
	"challenge" : {
		"taskId" : "aff34fb4-3fb1-4ac6-b917-0c811eff7800",
		"id" : "754a31c9-d4f4-4b36-84f5-ace5a6ba8242",
		"shortName" : ":tomato: 7.8."
	},
	"attribute" : "str",
	"priority" : 1,
	"value" : -3.079244230667636,
	"tags" : [
		"754a31c9-d4f4-4b36-84f5-ace5a6ba8242"
	],
	"notes" : "",
	"type" : "todo",
	"checklist" : [ ],
	"collapseChecklist" : false,
	"completed" : false
}
```

**Comment by jonathanly** [comment]
@Alys If you don't mind, I'd like to take a stab at this issue. This will be my first attempt at contributing to open source, huzzah!

**Comment by Alys** [comment]
@jonathanly Yessss!! It will be great to see this fixed. Thanks! :)

**Comment by jonathanly** [comment]
No problems, excited to work my first contribution!! :)

Spent some time trying to replicate the bug on my local environment with no success. Are there any particular steps to replicate the bug consistently?

Going off your analysis @Alys, would the issue be 'fixed' if I wrapped the failing code in the following conditional statement?
```
if (resArray[index]) {
  resArray[index].push(`${task.type}:${task.text}`, task.value, task.notes);
}
```

**Comment by Alys** [comment]
@jonathanly I think that should be enough.

To replicate the problem, create a challenge with one task (can be more but one is enough), get a user account to join the challenge, confirm that they do have the challenge task in their account, and then manually "remove" them from the challenge by using a mongodb command to $pull the challenge's ID out of the user's `challenge` array. Something like this should do it:
`dbUsers.update({_id:'d904bd62-da08-416b-a816-ba797c9ee265'}, {$pull:{challenges: '754a31c9-d4f4-4b36-84f5-ace5a6ba8242'}});`

On the production server, the bug would probably occur when the server or database was overloaded at the time a user tried to leave the challenge, causing part of the leave process to fail.

**Comment by jonathanly** [comment]
@Alys Awesome thanks for the pointers!

I'm just about ready to submit a pull request, is there any particular format you'd like it in?

**Comment by Alys** [comment]
@jonathanly The only things I think we really care about are:
- the title is descriptive enough for us to recognise the PR when we're looking at a list of them
- the body contains a description of what the PR does and any additional notes that might be relevant (also screenshots for those PRs that change any visible parts of the site, but that's not relevant here)
- the title and body both contain "fixes #8350" so that the PR is linked to this issue

**Comment by ghost** [comment]
Hey @Alys, could I take this issue? Already fixed the bug on my local install, so now I just need to write a clear comment and write tests for it.

**Comment by Alys** [comment]
@asherdale Sorry I only just noticed your comment! Yes, please work on this. I'll remove my own claim. Have a look at the linked PR's comments in case there's anything relevant there.
