### ISSUE TITLE
task sorting order problem not related to tasksOrder discrepancies

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8500]
Issue https://github.com/HabitRPG/habitica/issues/7645 documents a task sorting problem that occurs when there is a discrepancy between the task IDs of a user's tasks and those recorded in the user's `tasksOrder` object. I believe there's another sorting problem as well because it's reported by people who don't have an incorrect tasksOrder object. I realise the tasksOrder sort bug can fix itself, but I've seen many reports now when there's nothing wrong with tasksOrder, even when I've checked it promptly after the sorting bug is reported.

It can also occur when tasks have not been inserted by other processes (which would temporarily make the browser's task order different than the server's). One good example is Katkin (07a1dd1e-effa-43d0-b1f9-99e5d97b9436), who has done some useful troubleshooting, which I've added below.

Since I have no idea what's causing this, I guess the best place to start would be by examining the task sorting code and seeing if there's any logic problems. It looked fine when it was reviewed though so it must be something subtle.

----

### What to do if this happens to you:

Please report all task sorting problems in the [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac) guild (available from Guilds on the app or from Help > Report a Bug on the website). You might be affected by https://github.com/HabitRPG/habitica/issues/7645 instead of by this issue, in which case we can help you in the Bug guild.

----

Conversation with Katkin:

Katkin: "When I drag and drop tasks or when I use the 'push to top' or 'push to bottom' arrows, all my tasks seem to re-order themselves randomly. I can't get them to stick in a particular order. I've tried to re-order them on a different browser, so I know it isn't a browser issue."

Alys: "The next time you see the task sorting bug, immediately go to https://oldgods.net/habitrpg/task_adjustor.html . If you have the usual problem that I can fix, you'll see an orange message near the top of the page just above the list of tasks - paste that here. If you don't see it, please tell me"

Katkin: "A while ago you asked me to check the Task Adjustor page after experiencing the reordering bug - I've checked a couple of times and can confirm I don't see an orange message above the list of tasks."
 
Alys: "When you've seen the sorting bug, has it been very soon after you've been using Habitica on a different platform (e.g., if you were using the mobile app and then moved to the website and saw the bug, or vice versa)? Or does it happen after you've been using the site OR app for many minutes? Have you noticed the sorting bug occurring shortly after new tasks were added to any challenges that you are participating in?"

Katkin: "I only ever use Habitica on the website (on Safari - though I've checked and the bug occurs on different browsers too) and I've never participated in a challenge so it wouldn't be either of those things. I have Habitica open in a tab pretty much all the time, so it would generally be after using the site for many minutes. I've tried reloading the page and logging out and in again and it still seems to happen though"

**Comment by TheHollidayInn** [comment]
Does this seem to only be occurring on the UI side?

**Comment by Alys** [comment]
I don't know and I don't think it would be easy for me to find out. I'd need to get someone who's affected by it to screenshot their tasks and then I'd need to compare them with the orders from the tasksOrder object, doing that soon enough after the screenshot was taken to be certain that nothing else had affected the sort order in the meantime - that means no manual sorting, no adding or deleting tasks, no joining challenges, no using Habitica on a different platform...  I think there'd be a very low chance of me being able to get the data fast enough for any results I find to be reliable.

**Comment by Alys** [comment]
An interesting comment was made in the Report a Bug guild by spartan7886: 

**"sorting behavior. I consistently see that if I make a task and then immediately move it into position it doesn't stick, even if I wait a bit before moving it. If I make the task, manually sync, and then move it, it sticks. I do not have a message** [about the tasksOrder issue #7645] **on the Task Adjuster website. Is this one of the known sorting bugs? As a mildly terrifying side note, I made a dummy ToDo to confirm the message didn't show up and then disappear after I synced. When I deleted the ToDo after my test, the whole list below that disappeared too until I synced again. I have no idea if that was related or not."**

And a follow-up post:

**"I was using the website... Two further points of clarification just in case they help: even when I wait a bit did mean wait for the automatic sync to finish and only the new task reverts to he top, none of the other tasks change order. As far as the deletion bug, it's the first time I've ever seen it, but it's also the first time I've ever deleted a task shortly after making it."**

**Comment by SabreCat** [comment]
Fun related addenda:

1. The loading bar barely twitches when you first create a task. It looks less active than when you do something as simple as checking off a checklist item.

2. If you create a task and immediately drag-drop it, you get this error in the JS console--
```
Uncaught TypeError: Cannot read property 'id' of undefined
    at HTMLUListElement.stop (https://habitica.com/app-15d28b6b.js:50:19603)
    at a.(anonymous function).(anonymous function)._trigger (https://habitica.com/app-15d28b6b.js:28:1593)
    at a.(anonymous function).(anonymous function)._trigger (https://habitica.com/app-15d28b6b.js:29:5640)
    at a.(anonymous function).(anonymous function)._trigger (https://habitica.com/app-15d28b6b.js:27:28658)
    at a.(anonymous function).(anonymous function)._clear (https://habitica.com/app-15d28b6b.js:29:5527)
    at a.(anonymous function).(anonymous function)._clear (https://habitica.com/app-15d28b6b.js:27:28658)
    at a.(anonymous function).(anonymous function)._mouseStop (https://habitica.com/app-15d28b6b.js:28:20875)
    at a.(anonymous function).(anonymous function)._mouseStop (https://habitica.com/app-15d28b6b.js:27:28658)
    at a.(anonymous function).(anonymous function)._mouseUp (https://habitica.com/app-15d28b6b.js:28:13728)
    at a.(anonymous function).(anonymous function)._mouseUp (https://habitica.com/app-15d28b6b.js:27:28658)
    at HTMLDocument.f._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate (https://habitica.com/app-15d28b6b.js:28:12880)
    at HTMLDocument.dispatch (https://habitica.com/app-15d28b6b.js:4:7220)
    at HTMLDocument.r.handle (https://habitica.com/app-15d28b6b.js:4:3995)
```

3. If you then _delete_ that task, there's no additional error. But any tasks from the position you moved it to downward disappear until you sync! (EDIT: Ah, looks like this is what spartan7886 reported in Alys's last comment.)

**Comment by Alys** [comment]
It sounds like when you create a task, the task itself is saved as a new document in the däabase's tasks collection, but the user's own document is not being saved with the task's ID in the user's tasksOrder array. That's a guess but it's probaply a good point for a contributor to start looking at.

**Comment by Regina3000** [comment]
Alys, if it would help, I'd be willing to guinea-pig. We could set up a certain time, then you could direct me what to do, and in what order to do it, so that you can see what's happening. We could coordinate through Hangouts or something.

**Comment by SabreCat** [comment]
This looks likely to be an Angular client issue. Putting it on hold for the Vue redesign.

**Comment by librarianmage** [comment]
Should this still be on hold?

**Comment by lemoness** [comment]
@Alys @sabrecat Was this tasks sorting issue already resolved, or is it the one that we're currently working on?

**Comment by Alys** [comment]
I've marked this as need investigation rather than on hold. It's hard to be sure what causes each report of sort bugs but I think it's likely there's still problems.

**Comment by SabreCat** [comment]
I'm about to merge a partial fix by @TNychka https://github.com/HabitRPG/habitica/pull/8928 , and @TheHollidayInn has some additional fixes in the works! Hopefully those will cover it.

**Comment by Alys** [comment]
#8928 is for the tasksOrder bug so it won't help with this issue (other sorting bugs).

**Comment by SabreCat** [comment]
ah, right!

**Comment by TheHollidayInn** [comment]
I've seen another issue that is similar to this but now I can't find it. I'm pretty sure this error is caused by lifecycle functions in Vue attempting restore the due setting, but I will investigate further.

**Comment by Alys** [comment]
Another report of this from Glanlotiel (8ef30926-2e2a-4285-8a34-bce130acd61b) in the Report a Bug guild:

"I'm trying to get my dailies organized, but every time I move one, other things move from one random spot to another without any rhyme or reason. (I mean they're going up, down, and just all over the place without my even touching them.)"

Glanlotiel later confirmed that no Tag/Due filters were active while sorting and there were no tasksOrder errors shown in the Task Adjustor. They use Google Chrome. Their `preferences.dailyDueDefaultView` setting was false when I checked it just now.

**Comment by Alys** [comment]
There's been several reports of this in the Report a Bug guild over the past two days (not sure about earlier since SabreCat now does the admin support in the Bug guild except on weekends). All of the users listed below didn't have tasksOrder errors when I checked.

Ellen (e8f7c866-bee2-414d-a797-6395ed2999e5): "Almost every time I try rearranging any of my tasks without using the "To Top" or "To Bottom" buttons, they always seem to want to jump somewhere else in the order and it's super annoying and frustrates me endlessly. I uploaded a video to display exactly what happens: https://www.youtube.com/watch?v=2nouhZO8OKg"

Aidan Ryan (8a60ccd7-16f0-42cb-b1a4-3a6d2ddbeb54): "When I order my To-Do's they randomly jump up and down. Could you fix this because it has really started to bug me?"

Miechelle (63707306-cd62-4f60-95d4-d176abcadc45): "... I want to raise the matter of my habits and dailies being rearranged every single time I leave the page. I like to organize my dailies into time slots which I naturally then keep chronologically and my habits are in groups like health related, house cleaning related - I am sure you get the picture. Every single time I leave my tasks page - I am deadly serious about this, if I leave to go to a guild or for the day - if I leave that page, it reorganizes that stuff. I have given up on the habits and now just waste the time scrolling around until I find the one I want to tick but always have to go and find whichever timeslot daily I am working on to drag it to the top again so I can work my way through my checklist. It is more time-consuming than I think an app/site designed for productivity should be."
"... I just checked for filters, none. I then tried a re-order and hit All (I prefer to keep things on the due tab - is this considered a filter?) Merely switching from "due" to "all" re-ordered my dailies once again - and it is completely random btw, it is not as if they re-order to the same order every time this happens - absolutely random re-ordering multiple times a day - whenever I switch tabs. The order only stays the way I have put it if I stay on the tasks page and do not change between all and due for dailies. As to Habits, the same but they don't have the extra layer. My To-Do's stay in the order I have put them.

AnnaB (1d65f292-31fb-4981-8a03-c3a31d7f8f40): "When I'm on the desktop website (Chrome browser) and I try to move tasks up or down a list, they won't stay where I put them but jump around randomly. This is a MAJOR problem for my productivity as I can't mentally deal with a long and unprioritized to-do list."

**Comment by SabreCat** [comment]
I definitely have been seeing this several times throughout each week. I'm a bit at a loss, as I don't know how best to help the users affected. :(

**Comment by SabreCat** [comment]
Raising the priority here. We see this pretty frequently, it's very frustrating to users, and seems not to have any known workaround.

**Comment by TheHollidayInn** [comment]
Can we collect more examples? Are are the new reports still not related to tasksOrder?

We will need to know if it is just a web issue or mobile as well. And we will need to know how to recreate.

**Comment by SabreCat** [comment]
Still not related to tasksOrder. Affected users do sometimes report that the tasks misbehave on mobile as well. I'll add further examples here as they arise! But yeah, reproducibility has been a major block on this. :\

**Comment by SabreCat** [comment]
A couple recent affected account reports:

* Julia Bergius (02369d54-c743-439c-b619-37de5b55f000)
* Noctuana (6ae83a85-f8d5-4fce-b74e-e4067f02499f) 
* Ailurus Fulgens (3e81abbd-20a0-45b5-a4fe-23c0135eb71d)

Affected users have no `tasksOrder` trouble, no Loggly errors recorded, and even if we ask them to check the JS console, they don't turn anything up.

**Comment by SabreCat** [comment]
Some users report that the mobile app works better, or that after sorting and syncing back and forth between Web and mobile, the task order becomes more stable.

> alejandrokennedy (164c8bfe-f32d-4d8c-8c47-9fed50810b51)
> BTW, I'm running Firefox 61.0.1 (64-bit). When I tried ordering things on the mobile app, it behaved properly. I then restarted Firefox and the to-dos were in the same order as in the mobile app. Using the mobile app to sort appears to be a decent workaround. Still, it would be nice to be able to sort on the web app.
> I will definitely look for console errors next time I notice it happening. It may interest you to know that, after sorting on the mobile app and restarting Firefox, I was able to sort in Firefox a little better than before; I only had one glitch where an item or two jumped around. And after refreshing the browser, I had no glitches.

**Comment by Alys** [comment]
As [reported](https://github.com/HabitRPG/habitica/issues/10581#issuecomment-411902783) by @asktree (9ed86aed-d1a0-4618-b5eb-d64d1190b915):

"...  sometimes* occurs when I try to re-order tasks. When the page syncs, the tasks will not be how I ordered them; they may not have moved at all, or they may have moved to the wrong place, or sometimes even a task somewhere else in my list will have moved. This happens even if I'm only doing one move.
I tried to reproduce it with some new tasks, but strangely I couldn't. So, as of writing, I've failed to reproduce."

**Comment by Alys** [comment]
Onyxrose (21d3cf44-9b49-4a12-9408-4aec9bdd57cc) says something that might give a clue about why this happens or how to fix this (in bold):

> EEEKK! I think there is a bug in my dailies list! It was looking a bit messy so I decided to rearrange them a bit and next thing I knew other dailies were moving and popping into different spots all over the list! Now my "Off to work" task is above my "Get kids ready for school task!" That doesn't make much sense. Is there any way I could get an exterminator to come by?

> **Random dailies only seem to jump if I am moving another daily far enough away that the page needs to scroll. Random dailies do not seem to jump if I am moving a daily only a few places up or down.**

**Comment by Alys** [comment]
We still get these reports regularly but this one stands out because none of the usual suggestions have helped:

@Profe (3966ce12-42e3-418d-a86e-9d76941a6b4e) wrote:
"When I try to order my daily tasks, they keep re-ordering themselves! For example, if I have Tasks 1, 2, and 3, when I drag 1 to the top, suddenly 2 and 3 will switch places. With three tasks it wouldn't be a big deal, but I have a long list, and I want to keep them in a certain order."

I checked for tasksOrder errors, found none, and then posted my standard advice:
"I'm sorry, it is a known problem that sorting can be difficult, and you don't have the kind of problem that an admin can directly help with. Before you sort, clear the tag filters, set Habits, Dailies, and Rewards to 'All', and set To-Dos to 'Active'. That alone might be enough to avoid the problem, but if it isn't, on the website click the sync button in the header between each sort action and wait for the sync bar (the purple bar at the top of the screen) to disappear before you try to move another task. If you ever try to sort on the mobile app, drag downwards on your tasks to sync between each sort and if you get sorting problems there, please report it to the app developers through the app's menu at About > Report a Bug. On the website, it might help if you move a task only a few places up or down at a time (not so far that the page needs to scroll)."

@Profe wrote:
"Thank you for the tips. Before I wrote the first time, I had already set the habits, dailies and rewards to all, and the to-dos to active. I had also tried moving the tasks only a very short distance. Since your reply, I tried again, only moving the tasks one space at a time, and waiting for the sync bar to disappear. The tasks I don't touch will still switch around, or the one I am trying to move a single space suddenly jumps to another part of the list. I am using the website on my laptop, not a mobile app."

**Comment by Alys** [comment]
Some observations about this bug from @osberend (bc630499-2941-4c1b-85ed-41fed2e8959e):

"Occasionally a single daily (not always the same one) will pop to the start of the list for unclear reasons. If it's relatively far down, getting it back can be a bit of a hassle, since what does seem to work is to drag it from the top to the bottom of the screen (without attempting to force scrolling), *manually refresh* and then repeat, until it reaches its intended place. (If it's near enough to the bottom, sending it to the bottom and then manually dragging it up would probably work as well, but this tends to happen with dailies that are maybe 1/4 to 1/2 way down.) This happened just today, I believe (might have happened yesterday or the day before and I just skipped over it; I have since moved the daily affected back where it should be).

"Given that I have *far* more dailies than the average Habitican (145 total, something like 110 or 120 active on a typical day), these could in principle be problems that only manifest at a high daily count, but I suspect that it's more likely that they exist regardless, but happen more often and/or are more annoying (e.g., if all your dailies fit on one screen, occasionally having to drag one back to its proper place is a lot less of a both) with a high daily count than with a low one."

**Comment by shanaqui** [comment]
I made some observations about task sorting issues related to sorting while a filter is set, when the staff checked in about this. I thought I'd add it here. 

Here is my starting point:

![image](https://user-images.githubusercontent.com/8144640/115873146-8452a800-a43a-11eb-86ec-ac9edac6d701.png)

Here is what happened when I moved task 5 to the top while I had the due filter applied:

![image](https://user-images.githubusercontent.com/8144640/115873243-9b919580-a43a-11eb-951d-0ca14b18acd8.png)

Two insights from this:

1. The error is consistent: if you start from the tasks in the same order each time, and move them in the same way each time, it looks like you will repeat the exact same incorrect reordering. So there is some underlying logic happening there, the shuffle isn't random.
2. If you don't do anything and just refresh, it will look the way you expect once you've done that. But if you try to sort in the meantime, it'll scramble worse than ever because you're not even seeing where the tasks really are.

**Comment by saraolson** [comment]
staff had a chance to look at the various task sorting issues recently and we came to an agreement on some next steps to try to figure these problems out.

We know that drag and drop doesn't work well when filters are applied, so to start we'd like to attempt to clean that flow up. There seemed to be two options to pick from in this case. Either we do not allow any drag and drop sorting of tasks while filters are applied, or we come up with some logic for how drag and drop should place tasks in a filtered state when not all tasks are visible.

Since filtering to ‘is due’ is extremely common, not allowing drag and drop while any filters are applied would most likely cause a lot of confusion and hurt the expected experience of organizing your tasks. Because of this, we weren't a fan of that solution, so we're proposing a solution that tells the apps(web and mobile) how to correctly place tasks while in a filtered state.

**Proposal:**

When a user tries to drag and drop a task when filters are applied, the moved task will sort of ‘attach’ itself to the task it was placed above. Any invisible filtered tasks will be sorted around it, never between.

If you move a task to the top of a filtered list, it won’t go above invisible tasks. It will just stay above the last visible task. Conversely, if you move a task to the bottom of a  filtered list, it will also not go below invisible tasks. It will slot itself below the last visible task.

(We’re following how trello handles this, so if you’d like an example of how it should work in various circumstances that is a good place to experiment. we used their labeling system and filtered to different labels to recreate our scenarios)

including some visual examples of how we’d like this to work:
<img width="761" alt="Screen Shot 2021-05-26 at 11 11 21 AM" src="https://user-images.githubusercontent.com/12453119/119698641-6ef8e100-be1f-11eb-8c4a-30df59d1e614.png">
<img width="760" alt="Screen Shot 2021-05-26 at 11 11 49 AM" src="https://user-images.githubusercontent.com/12453119/119698645-70c2a480-be1f-11eb-8a7a-2b12a424322b.png">

I'll be making issues on the mobile repos that copies this info over there, as we'll need the logic across platforms. Let me know if it keeping this here is the best option, or if it'd be better for me to make a new issue.
