### ISSUE TITLE
Problem Installing local version

### ISSUE THREAD

**Issue by wardyorgason** [HabitRPG/habitica#87]
I've been trying for the past two days to install habitrpg on my computer I use as a server. I did the install instructions here: https://github.com/lefnire/habitrpg/issues/8 (or at least most of them) and I can't seem to get it to work.

I've tried on Ubuntu and Backtrack and I get the exact same error. This comes after cloning and using npm to install. When I try to run the server it gives me this same error:

/var/www/habitrpg/node_modules/connect-mongo/lib/connect-mongo.js:92
        throw new Error('Required MongoStore option `db` missing');
              ^
Error: Required MongoStore option `db` missing
    at new MongoStore (/var/www/habitrpg/node_modules/connect-mongo/lib/connect-mongo.js:92:15)
    at Object.<anonymous> (/var/www/habitrpg/src/server/index.coffee:80:17)
    at Object.<anonymous> (/var/www/habitrpg/src/server/index.coffee:99:4)
    at Module._compile (module.js:449:26)
    at Object.require.extensions..coffee (/var/www/habitrpg/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/var/www/habitrpg/forever.js:2:1)
[Error: Authentication required, invalid details provided]

Any help at all would be great since I'm new to nodejs and have no idea what is wrong.

**Comment by lefnire** [comment]
See [the wiki](https://github.com/lefnire/habitrpg/wiki/Running-Locally) for the instructions, looks like you're missing a running mongodb instance
