### ISSUE TITLE
"Invalid date" for Daily with weeksOfMonth monthly repeat for 4th (weekday) with everyX 1

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8775]
There's a problem that I think is related to the `weeksOfMonth` monthly repeat option, although I'm not sure of the details yet. In the Report a Bug guild, nonhoration (a82d7efb-a44f-4484-b630-465620623462) said:

***I haven't had a cron rollover in 3 days and whenever I try to check off a daily today I get a "Gateway 504" error. (It looks like I can + or - habits though)"**

The AWS logs from the past day showed the error below, repeated five times (at different times). The post relevant portions of the error are:

`Error: Invalid date supplied to match method: NaN`
`originalUrl=/api/v3/tasks/59d767ec-bbd3-4ab7-8127-b9690b500230/score/up`

```
2017-06-01T02:25:21.146Z - error: Error: Invalid date supplied to match method: NaN
    at Error (native)
    at Recur.matches (/var/app/current/node_modules/moment-recur/moment-recur.js:614:23)
    at Recur.getOccurrences (/var/app/current/node_modules/moment-recur/moment-recur.js:315:26)
    at Recur.next (/var/app/current/node_modules/moment-recur/moment-recur.js:629:35)
    at Object.shouldDo (/var/app/current/website/common/transpiled-babel/cron.js:217:63)
    at setNextDue (/var/app/current/website/transpiled-babel/libs/taskManager.js:296:34)
    at _callee7$ (/var/app/current/website/transpiled-babel/controllers/api-v3/tasks.js:982:43)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:117:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/app/current/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/current/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5) method=POST, originalUrl=/api/v3/tasks/59d767ec-bbd3-4ab7-8127-b9690b500230/score/up, host=habitica.com, content-length=0, accept=application/json, accept-encoding=gzip, deflate, accept-language=en-CA;q=1, user-agent=Habitica/198 (iPhone....), x-api-user=a82d7efb-a44f-4484-b630-465620623462, x-client=habitica-ios, x-forwarded-port=443, x-forwarded-proto=https, , httpCode=500, isHandledError=false, 
```

Here's the repeat settings for the Daily it's referring to:
```
{
    "_id": "59d767ec-bbd3-4ab7-8127-b9690b500230",
    "userId": "a82d7efb-a44f-4484-b630-465620623462",
    "completed": false,
    "frequency": "monthly",
    "everyX": 1,
    "startDate": "2017-05-27T17:34:40.000Z",
    "repeat": {
        "su": false,
        "s": false,
        "f": false,
        "th": false,
        "w": false,
        "t": false,
        "m": false
    },
    "updatedAt": "2017-05-28T17:51:15.794Z",
    "createdAt": "2014-05-02T18:13:02.661Z",
    "daysOfMonth": [],
    "weeksOfMonth": [
        4
    ],
    "isDue": false,
    "nextDue": [
        "Sun Jul 30 2017 00:00:00 GMT+0000",
        "Sun Oct 29 2017 00:00:00 GMT+0000",
        "Sun Dec 31 2017 00:00:00 GMT+0000",
        "Sun Apr 29 2018 00:00:00 GMT+0000",
        "Sun Jul 29 2018 00:00:00 GMT+0000",
        "Sun Sep 30 2018 00:00:00 GMT+0000"
    ]
}
```

An interesting point is that the start date is 27 May, but the first date listed in `nextDue` is 30 July, as if there was some problem with identifying the repeat date for June (it's everyX is 1 so it should have a date in June).

For easy comparison of dates, here's a calendar:
```
       April                  May                   June          
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                   1      1  2  3  4  5  6               1  2  3  
 2  3  4  5  6  7  8   7  8  9 10 11 12 13   4  5  6  7  8  9 10  
 9 10 11 12 13 14 15  14 15 16 17 18 19 20  11 12 13 14 15 16 17  
16 17 18 19 20 21 22  21 22 23 24 25 26 27  18 19 20 21 22 23 24  
23 24 25 26 27 28 29  28 29 30 31           25 26 27 28 29 30     
30                                                                

        July                 August              September        
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
                   1         1  2  3  4  5                  1  2  
 2  3  4  5  6  7  8   6  7  8  9 10 11 12   3  4  5  6  7  8  9  
 9 10 11 12 13 14 15  13 14 15 16 17 18 19  10 11 12 13 14 15 16  
16 17 18 19 20 21 22  20 21 22 23 24 25 26  17 18 19 20 21 22 23  
23 24 25 26 27 28 29  27 28 29 30 31        24 25 26 27 28 29 30  
30 31                                                             
```

@TheHollidayInn Any idea what's going wrong?

**Comment by TheHollidayInn** [comment]
This seems to be the same issue as the last Thursday of the month. The 4 week is actually the 5 week

**Comment by TheHollidayInn** [comment]
And non of the repeat days are selected. So that's an issue as well.

**Comment by TheHollidayInn** [comment]
Well, never mind. The start date should work. So yea, last day of the month issue.

**Comment by TheHollidayInn** [comment]
Okay, after further review, I believe this is because the repeat days are unselected. 

https://github.com/HabitRPG/habitica/blob/develop/website/common/script/cron.js#L155

If you select monthly, weeksOfMonth - you have to have at least on day selected - so it will repeat: 'on the x day of the month'

So, I assume that is causing the issue. I will check to see if I can just return false if the settings are not correctly set.

**Comment by Alys** [comment]
But they aren't supposed to select a day of the week for that case, are they? Isn't it meant to determine the day from the start date? There's no options for selecting the day of the week:

![image](https://cloud.githubusercontent.com/assets/1495809/26705249/5a428210-4778-11e7-8f36-9baea98a934c.png)
 



----

Unrelated to that and just for the record, nonhoration has confirmed that their problem with cron not running went away after I removed the incorrect repeat settings:

"Making that change seems to have made everything roll over properly!"

**Comment by TheHollidayInn** [comment]
Ah, okay. So there must have been an issue while saving from the UI. I put a fix that will ensure the cron and score keeps working. Let me also add a check before save on the client
