### ISSUE TITLE
Error: cannot find module 'habitrpg-shared' (Setting up Habitica locally)

### ISSUE THREAD

**Issue by SalethiNat94** [HabitRPG/habitica#8927]
* UUID: 7a1b0a51-0221-4542-b09f-c5e27ba83f31
  * Browser: Chrome version 59.0.3071.115
  * OS: Windows 10

I'm trying to install Habitica locally: I followed all the instructions provided in the online guide, and everything worked smoothly until I attempted to run `npm start`. `The console told me that various important modules needed to be installed, which looked like this:

 Local Npm module "grunt-contrib-uglify" not found. Is it installed?
 Local Npm module "grunt-contrib-clean" not found. Is it installed?
 Local Npm module "grunt-contrib-stylus" not found. Is it installed?

The program would then "abort due to warnings". 
I used `npm install (module name here)` for each missing module, which seemed to work just fine, until I ran `npm start` again and got this message:

Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
module.js:471
    throw err;
    ^

Error: Cannot find module 'habitrpg-shared'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\models\user.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (C:\users\daniel\desktop\habitica_base\habitrpg\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\i18n.js:4:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (C:\users\daniel\desktop\habitica_base\habitrpg\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\server.js:31:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
info: [Mon Aug 07 2017 00:12:07 GMT-0400 (Eastern Daylight Time)] [master:5556] worker:1216 disconnect! new worker:8420 fork
module.js:471
    throw err;
    ^
`

This chunk of code would then repeat endlessly until I closed the program. Can someone please tell me what's going on here? It appears that I need to install the module 'habitrpg-shared' and that I need the c++ bson extension as well, but I'm not sure how to install either of these. (Does 'habitrpg-shared' refer to the actual repo itself? Using `npm install habitrpg-shared` yielded nothing.)

Here is the full section that appears when I attempt to run `npm start`:

Daniel@ddespins MINGW64 ~
$ cd /c/users/daniel/desktop/habitica_base/habitrpg

Daniel@ddespins MINGW64 /c/users/daniel/desktop/habitica_base/habitrpg (develop)
$ npm start

> habitrpg@0.0.0-152 start C:\users\daniel\desktop\habitica_base\habitrpg
> grunt run:dev

Starting custom mode
Running "stylus:build" (stylus) task
File build\app.css created.
File build\static.css created.

Running "concurrent:dev" (concurrent) task
    Reading git log since pre-i18n
    Executing :  git log  --grep="^fix|^feat|^docs|BREAKING" -E --format=%H%n%s%n%b%n==END== pre-i18n..HEAD
    WARNING: Incorrect message: 176b39a1a017f275aebc9e9b7f8da5289a295a5d fix(typo)
    WARNING: Incorrect message: 93ca6cf6931306793cd4e548d6f59069f51c652f fix(i18n)
    WARNING: Incorrect message: 11eca7e947b0966ded799a95850db5abc4b5212d fix(i18n)
    Parsed 119 commits
    Generating changelog to CHANGELOG.md (  )
Starting custom mode
Starting custom mode
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...Reading git log since pre-i18n
Executing :  git log  --grep="^fix|^feat|^docs|BREAKING" -E --format=%H%n%s%n%b%n==END== pre-i18n..HEAD
WARNING: Incorrect message: 176b39a1a017f275aebc9e9b7f8da5289a295a5d fix(typo)
WARNING: Incorrect message: 93ca6cf6931306793cd4e548d6f59069f51c652f fix(i18n)
WARNING: Incorrect message: 11eca7e947b0966ded799a95850db5abc4b5212d fix(i18n)
Parsed 119 commits
Generating changelog to CHANGELOG.md (  )
7 Aug 00:12:04 - [nodemon] v0.7.10
7 Aug 00:12:04 - [nodemon] to restart at any time, enter `rs`
7 Aug 00:12:04 - [nodemon] watching: C:\users\daniel\desktop\habitica_base\habitrpg
7 Aug 00:12:04 - [nodemon] starting `node ./src/server.js`
7 Aug 00:12:04 - [nodemon] reading ignore list
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
module.js:471
    throw err;
    ^

Error: Cannot find module 'habitrpg-shared'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\models\user.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (C:\users\daniel\desktop\habitica_base\habitrpg\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\i18n.js:4:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (C:\users\daniel\desktop\habitica_base\habitrpg\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\daniel\desktop\habitica_base\habitrpg\src\server.js:31:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
info: [Mon Aug 07 2017 00:12:07 GMT-0400 (Eastern Daylight Time)] [master:5556] worker:1216 disconnect! new worker:8420 forkcd 
module.js:471
    throw err;
    ^

**Comment by Alys** [comment]
@Pizilden Your fork of the repo (https://github.com/Pizilden/habitrpg) is very very old. 

I recommend deleting C:\users\daniel\desktop\habitica_base\habitrpg completely including everything installed under it, then update your fork in github. Once it's identical to https://github.com/HabitRPG/habitica/ , start from the top of http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally again. There might be other ways to get your current local install working, but they would involve several (possibly many) manual fixes, would result in old code remaining in your install, and could cause problems later. Starting from scratch is likely to be much faster and more reliable.

It shouldn't be necessary to do manual workarounds such as installing modules individually so if you find any error messages that make it seem like you might need to, report the errors here first and let us advise you about what might be wrong.

**Comment by SalethiNat94** [comment]
@Alys Wow, holy outdated repos Batman O__O If I remember correctly I forked the old HabitRPG repo way back when I joined in 2014, but at the time never got around to doing anything with it. Attempts at updating this fork gave me nothing (even when I tried to sync the upstream) so I deleted the fork and cloned a completely new one, and the setup worked perfectly this time! Thanks for your help ^__^
