### ISSUE TITLE
Constant need for refresh

### ISSUE THREAD

**Issue by Worky** [HabitRPG/habitica#912]
Lots of times the "edit" and "progress chart" in quests get "stuck", and you can't click on and open them. And only by refreshing you are able to use them again.
Sometimes it happens to all quests, sometimes in to 2 or 3.

**Comment by deiwin** [comment]
Noticed similar behaviour.

For example, after closing and opening the progress graph of a daily/habit and then trying to open the same daily/habit up for editing it gets 'stuck'. That means you can't either view the graph anymore nor edit it. If you just open and close the progress graph multiple times, it works. 

It's the same case when doing it the other way around: opening the edit part before and then trying to view the progress graph.

#### Stuff I have in the console before any interactions:

Error in event handler for 'undefined': Syntax error, unrecognized expression: input#$3b Error: Syntax error, unrecognized expression: input#$3b
    at Error (<anonymous>)
    at Function.st.error (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:9:10926)
    at ft (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:9:17138)
    at wt (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:9:19823)
    at Function.st (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:9:6140)
    at b.fn.extend.find (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:9:20941)
    at b.fn.b.init (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:8:1123)
    at b (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/jquery-1.9.1.min.js:8:203)
    at Object.cipFields.setUniqueId (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/chromeipass.js:802:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/chromeipass.js:835:14) event_bindings:380
Unknown RPC service: widget-interactive-I0_1368612093965

#### Error I get when simply opening and closing the progress graph of a daily/habit (seems to happen when quickly closing and opening the graph; **might be a separate issue**):

Error in event handler for 'undefined': IndexSizeError: DOM Exception 1 Error: Index or size was negative, or greater than the allowed value.
    at P (chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:16:142)
    at null.<anonymous> (chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:18:417)
    at chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content_js_min.js:1:182
    at miscellaneous_bindings:288:9
    at chrome.Event.dispatchToListener (event_bindings:390:21)
    at chrome.Event.dispatch_ (event_bindings:376:27)
    at chrome.Event.dispatch (event_bindings:396:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:254:22) 

#### Software stack:
- Windows 7 64bit
- Chrome

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!
