### ISSUE TITLE
Error occured while trying to proxy to...

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9916]
After the last update, I have such an error:

```sh
$ git pull origin develop
$ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
```
```
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
http://localhost:8080/api/v3/i18n/browser-script
```
![image](https://user-images.githubusercontent.com/4408379/35594819-94a6d75a-0625-11e8-9bef-e9f36823e540.png)

I tried to remove `node_modules` and reinstall the modules, but this did not work. Help me please.

**Comment by paglias** [comment]
Not familiar with docker, but what the logs from the server say?

**Comment by lex111** [comment]
How can I see them?

**Comment by Alys** [comment]
Look in the terminal windows where the npm start and npm run commands are running. The server's output and error messages are there.

**Comment by paglias** [comment]
@lex111 Docker has been updated recently, maybe try to reinstall? See https://github.com/HabitRPG/habitica/pull/9724 for the changes

**Comment by lex111** [comment]
Here is logs:

Client
```
> habitica@4.23.0 client:dev /usr/src/habitrpg
> node webpack/dev-server.js

[HPM] Proxy created: /api/v3  ->  http://server:3000
[HPM] Proxy created: /stripe  ->  http://server:3000
[HPM] Proxy created: /amazon  ->  http://server:3000
[HPM] Proxy created: /paypal  ->  http://server:3000
[HPM] Proxy created: /logout  ->  http://server:3000
Listening at http://localhost:8080

(node:17) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack: wait until bundle finished: /__webpack_hmr
webpack: wait until bundle finished: /index.html
webpack built 0f5ef3b68a3e34bfe56b in 64042ms
Hash: 0f5ef3b68a3e34bfe56b
Version: webpack 2.7.0
Time: 64042ms
                                                       Asset     Size  Chunks                    Chunk Names
                       static/images/restoration.25584fe.png  10.3 kB          [emitted]
                static/images/spritesmith-main-2.e521fb2.png  61.7 kB          [emitted]
                static/images/spritesmith-main-4.578c1d1.png  63.3 kB          [emitted]
                static/images/spritesmith-main-1.2657328.png   362 kB          [emitted]  [big]
                static/images/spritesmith-main-5.64fd008.png   143 kB          [emitted]
                static/images/spritesmith-main-7.ea851f1.png   143 kB          [emitted]
                static/images/spritesmith-main-8.cac2776.png   120 kB          [emitted]
                static/images/spritesmith-main-6.2a1953f.png   133 kB          [emitted]
               static/images/spritesmith-main-11.5b7316b.png   183 kB          [emitted]
               static/images/spritesmith-main-18.552bc6c.png   181 kB          [emitted]
               static/images/spritesmith-main-17.efa6c3e.png   154 kB          [emitted]
               static/images/spritesmith-main-19.4591a46.png   162 kB          [emitted]
                static/images/spritesmith-main-9.5a1f939.png   206 kB          [emitted]
               static/images/spritesmith-main-20.2dc0acc.png   152 kB          [emitted]
               static/images/spritesmith-main-12.7180868.png   160 kB          [emitted]
               static/images/spritesmith-main-15.917ae39.png   145 kB          [emitted]
               static/images/spritesmith-main-14.40b8ccd.png   165 kB          [emitted]
               static/images/spritesmith-main-16.bec7508.png   148 kB          [emitted]
               static/images/spritesmith-main-13.91bf3cf.png   134 kB          [emitted]
                static/images/spritesmith-main-0.447f8b7.png   557 kB          [emitted]  [big]
               static/images/spritesmith-main-10.924ad6d.png   437 kB          [emitted]  [big]
        static/images/spritesmith-largeSprites-0.e098318.png   104 kB          [emitted]
                    static/images/justin_textbox.29cc541.png  18.9 kB          [emitted]
                  static/images/creator-hills-bg.d739925.png  15.4 kB          [emitted]
                               static/images/404.28e204e.png  33.3 kB          [emitted]
        static/images/BackerOnly-Pet-CerberusPup.83717ea.gif  11.1 kB          [emitted]
static/images/ContributorOnly-Equip-CrystalArmor.f221ab1.gif  28.6 kB          [emitted]
                       static/images/basilist@3x.cda4c55.png  24.6 kB          [emitted]
                           static/images/gemfall.f24ae94.png  22.9 kB          [emitted]
                          static/images/party@3x.2ea7938.png  32.8 kB          [emitted]
                    static/images/quest_bewilder.6426869.gif  56.5 kB          [emitted]
                     static/images/quest_burnout.8fe2edd.gif  23.8 kB          [emitted]
          static/images/quest_lostMasterclasser4.8f74d72.gif    69 kB          [emitted]
                      static/images/quest_screen.a95b9ff.png  27.2 kB          [emitted]
    static/images/midground_foreground_extended2.0fe8082.png  13.3 kB          [emitted]
                             static/svg/confetti.4280908.svg  15.8 kB          [emitted]
                    static/images/beingHabitican.dab1b46.png  11.9 kB          [emitted]
                      static/images/consequences.c2c3239.png  25.3 kB          [emitted]
                            static/images/github.3c58d0d.gif  13.4 kB          [emitted]
                        static/images/moderators.b9710f1.png  12.7 kB          [emitted]
                      static/images/publicSpaces.7aad609.png  32.8 kB          [emitted]
                static/images/spritesmith-main-3.264367d.png  75.3 kB          [emitted]
                             static/images/staff.2336e4b.png  11.5 kB          [emitted]
                            static/images/trello.4090740.png  11.1 kB          [emitted]
                       static/images/group-12@3x.32d9fee.png  27.6 kB          [emitted]
                       static/images/group-13@3x.c93e792.png   129 kB          [emitted]
                       static/images/group-14@3x.c812b12.png  31.1 kB          [emitted]
            static/images/grassy-meadow-backdrop.b75d689.png    22 kB          [emitted]
                static/images/battle-monsters@3x.7cd8d3e.png  66.4 kB          [emitted]
                   static/images/earn-rewards@3x.acaba17.png   105 kB          [emitted]
                 static/images/health-fitness@3x.9676cd7.png  29.2 kB          [emitted]
                      static/images/home-main@3x.23eeafe.png  18.7 kB          [emitted]
                 static/images/mobile-preview@3x.422fbec.png   395 kB          [emitted]  [big]
                      static/images/much-more@3x.e3ed259.png  29.9 kB          [emitted]
                    static/images/school-work@3x.d6eb165.png  29.8 kB          [emitted]
                   static/images/track-habits@3x.91fc64d.png  64.4 kB          [emitted]
                    static/images/android_iphone.7e19918.png   224 kB          [emitted]
                         static/images/challenge.f740382.png   155 kB          [emitted]
                             static/images/drops.568ab19.png   169 kB          [emitted]
                             static/images/guild.222c56d.png   413 kB          [emitted]  [big]
                       static/images/integration.4184d98.png  20.3 kB          [emitted]
                           static/images/lefnire.94fc71b.png  66.7 kB          [emitted]
                        static/images/screenshot.fc15c93.png   658 kB          [emitted]  [big]
   static/images/seasonal_shop_closed_background.aa753c7.png  10.2 kB          [emitted]
          static/images/seasonal_shop_opened_npc.b7c8487.png    11 kB          [emitted]
                                                        0.js   700 kB       0  [emitted]  [big]  static
                                                        1.js   917 kB       1  [emitted]  [big]  settings
                                                        2.js  1.26 MB       2  [emitted]  [big]  guilds
                                                        3.js  1.43 MB       3  [emitted]  [big]  challenges
                                                        4.js   841 kB       4  [emitted]  [big]  inventory
                                                        5.js  1.28 MB       5  [emitted]  [big]  group-plans
                                                        6.js   154 kB       6  [emitted]         hall
                                                        7.js   913 kB       7  [emitted]  [big]  entry
                                                        8.js  1.21 MB       8  [emitted]  [big]  userTasks
                                                        9.js   512 kB       9  [emitted]  [big]  shops-market
                                                       10.js   422 kB      10  [emitted]  [big]  shops-quest
                                                       11.js   283 kB      11  [emitted]  [big]  shops-seasonal
                                                       12.js   275 kB      12  [emitted]  [big]  shops-timetravelers
                                                       13.js   588 kB      13  [emitted]  [big]  auth
                                                       14.js  26.7 kB      14  [emitted]         shops
                                                       15.js     9 kB      15  [emitted]         user
                                                      app.js  16.2 MB      16  [emitted]  [big]  app
                                                  index.html  2.67 kB          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0
webpack: Compiled successfully.
[HPM] Error occurred while trying to proxy request /api/v3/i18n/browser-script from localhost:8080 to http://server:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/v3/i18n/browser-script from localhost:8080 to http://server:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

Server
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/libs/encryption.js:11:20)
    at Module._compile (module.js:570:32)
    at loader (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/libs/email.js:4:1)
    at Module._compile (module.js:570:32)
    at loader (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/models/challenge.js:13:1)
    at Module._compile (module.js:570:32)
2018-01-31T13:06:49.702Z - info: [Wed Jan 31 2018 13:06:49 GMT+0000 (UTC)] [master:29] worker:165 disconnect! new worker:171 fork
buffer.js:262
  throw new TypeError(kFromErrorMsg);

...
```

@BradLugo can you help me?

**Comment by paglias** [comment]
Ah that's due to a change in the config file we made. There are two new
keys in the config.json.sample file that you have to add to your
config.json file: session secret IV and session secret key

Il 31 Gen 2018 14:10, "Alexey Pyltsyn" <notifications@github.com> ha
scritto:

**Comment by lex111** [comment]
@paglias thanks for your help. Errors from the server were lost, but did not solve the problem :(

As before, this is:
```
[HPM] Error occurred while trying to proxy request /api/v3/i18n/browser-script from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

However, the server opens in the browser, but ...

```
GET http://localhost:8080/api/v3/i18n/browser-script net::ERR_ABORTED
```

Why `localhost:8080` instead of `localhost:3000`?

**Comment by paglias** [comment]
localhost:8080 is the client server and proxies request to the webserver at port 3000. Can you try to reload after a bit? The webserver might take a bit to start. @TheHollidayInn ideas?

**Comment by paglias** [comment]
Otherwise try by deleting everything and reinstall from scratch. Unfortunately I don't use docker for my local development so I cannot help. Try to post in #9724 but I think the people there said it was working

**Comment by lex111** [comment]
Hooray, everything worked well after I restarted a second time (it's strange, after adding the missing keys to `config.json`, I restarted the server, well, it does not matter). Thanks again @paglias
